### ISSUE TITLE
Rules for multiple annotations on a usage (like `@Nullable @NonNull Foo`)

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#100]
We [say that this is illegal](https://docs.google.com/document/d/15NND5nBxMkZ-Us6wz3Pfbt4ODIaWaJ6JDs4w6h9kUaY/edit#heading=h.ib00ltjpj1xa). But we might need to say more about it someday.

In our docs about specific design issues, we have grown fond of saying:

> For any syntax that is legal Java, we don't have the option to simply declare it to be illegal. Since we will have to deal with code that was compiled outside the purview of compliant checkers anyway, we still need to decide how to deal with it.

That's particularly relevant for `@Nullable @NonNull Foo`: For the _other_ cases in which we declare say an annotation is placed "illegal," checkers can just ignore the annotation, since it's appearing in a bogus place. But here, the annotations are in a valid place: There are just too many of them :)

It's even possible to imagine that this case will arise in practice -- beyond just from human error (which has produced `@Nullable @NonNull` a few times in Google's codebase :)). Consider a code generator that is given the following type...

```java
interface Foo<T> {
  @Nullable T get();
}
```

...and asked to generate an implementation of `Foo<@NonNull T>`. It might well apply naive substitution rules and generate:

```java
  @Nullable @NonNull T get() { ... }
```

Maybe it "shouldn't" (and I haven't tried to find if any tools actually do this). But the only alternatives are:
- to mostly give up on type annotations (which is what most tools do, like AutoValue)
- to have special handling for our nullability annotations

A couple possibilities:

First, maybe `@NonNull @Nullable` should be treated as `@NullnessUnspecified`. This raises a couple questions:

- Should checkers _allow_ writing `@NonNull @Nullable` in code they're checking? I would say no. (But I was briefly tempted to say that we could omit `@NullnessUnspecified` entirely by telling users to write `@NonNull @Nullable` instead :))

- Is it really sensible to interpret `@NonNull @Nullable` as `@NullnessUnspecified`, particularly on type-variables usages, where `@NonNull` is weird (~#89~ #91)?

The other possibility -- my favorite, as usual :) -- is that we pick the "most nullable" specifier. So we'd treat `@Nullable @NonNull` like plain `@Nullable`. (Maybe this feels a little more natural in the case of treating <code>@Nullable **@NullnessUnspecified**</code> as `@Nullable`?)

**Comment by mernst** [comment]
I agree with our current position that incompatible annotations at a location should be illegal.
`@NonNull` and `@Nullable` should have clear definitions, and those definitions are inconsistent.  Adding special rules for when they are both present will muddy the waters and will make it difficult or impossible for checking tools to do their job.

> For any syntax that is legal Java, we don't have the option to simply declare it to be illegal.

There are other situations where we declare legal Java syntax to be illegal.  One example is when a method override does not satisfy behavioral subtyping.  So we should feel free to do so here.

> It [a code generation tool] might well apply naive substitution rules

I don't think we want to lose an important opportunity to find problems in client code, just to handle some tools that might do naive substitution.  I think it is better to notify users of the problem.  This will enable users to work around the problems or at least inform them of the potential problem.  This may also nudge the code generation tools to become more sophisticated.

(Related: https://github.com/jspecify/jspecify/issues/4.)

> we pick the "most nullable" specifier. So we'd treat `@Nullable @NonNull` like plain `@Nullable`.

I have concerns about this proposal.
1. This will be unsound in some circumstances.  That would make Jspecify useless for verification tools.
2. A syntactic rule like "most nullable" is semantically inconsistent.  "most nullable" means "most lenient" on formal parameter types, but it means "most conservative" on return types.  For field types, it doesn't mean either one!

An alternative proposal is to leave `@Nullable @Nonnull` *undefined*, and permit each checking tool to issue a warning or treat it unsoundly, at their preference.

**Comment by cpovirk** [comment]
Thanks. There are a lot of things that deserve a response here, but to focus on one:

I think we all agree that checkers can (and probably _should_, though we don't need to mandate it) treat a source file with `@Nullable @NonNull Foo` as an error.

The remaining concern is that people might write that in code that they compile with a stock compiler. Then our tools might see it in class files.

I suspect that most of us aren't going to want for tools to issue outright _errors_ for problems in _libraries_ used by the code that it's checking, so we need to decide what they should do.

Our assumption [so far](https://docs.google.com/document/d/1HGupJjYkFs6OPjH4tQFmivNr1sPcHicaXDdMVvGfu4A/edit#heading=h.vcpnsbsm2di3) has been that we should define the semantics for anything that we might find in class files, even if our tools would have refused to produce those class files. I am not _personally_ that invested in that assumption: I could probably tolerate leaving cases that are "perverse enough" as undefined, including this one. But it would be a shift in our approach.

@kevinb9n , who I believe wrote our assumption that we need to specify the semantics of any valid Java class files.

**Comment by kevinb9n** [comment]
I suppose we could consider the idea that some annotationings are SO bogus that we would even refuse to compile a file that *depended* on a file that did that.  And maybe `@Nullable @NonNull` would safely be in that category. But surely not everything should be. We hadn't really talked about this idea before, instead just saying "we'll have to do *something* well-defined (when compiling the dependent code) no matter what".

**Comment by kevinb9n** [comment]
If we DO want to have some forgiving treatment of `@Nullable @NonNull` then I'd suggest we can do a thought experiment by analogy:  what if a Java variable was by some mysterious means given two types:  both `Number` AND `Integer`?

This is a bogus scenario, but if we had to choose, wouldn't we simply consider that to be of type `Integer`, since it satisfies both? I think we would do that (whether in an assigning-from or assigning-to context). That would suggest letting `@NonNull` take precedence over `@Nullable`.

**Comment by cpovirk** [comment]
Interesting! I see the argument there. At the same time, I have bought pretty deeply into the idea of annotations as only ever "adding nullness" (hence many of my reservations around `@NonNull`). The behavior of `@Nullable @NonNull Foo` is probably yet another thing that hinges on that idea.

**Comment by cpovirk** [comment]
(I have been meaning to get out of the habit of saying things like "additive nullness" and into the habit of saying "Kotlin-style nullness." I mean the same thing, but I think the latter sounds friendlier :))

**Comment by kevin1e100** [comment]
For most things I've taken the view that we can separate:
- "illegal in source code"
- "what to do with bytecode (e.g., on the classpath) that does it anyway"

Generally it seems we can ask tool owners to error out on illegal source
code.  But since Javac will still compile it, it seems we want to be more
lenient about bytecode.  With conflicting annotations I feel that erroring
out even on bytecode is a fine approach.  In more subtle cases I think we
can sometimes define reasonable fallback behavior, which will generally be
something like "warn on seeing X in bytecode, and do Y to proceed".  Eg,
"warn on seeing @Nullable @NonNull in bytecode and pick the first one to
proceed".  (Again, we may still want to just error out in this particular
case.)

**Comment by kevinb9n** [comment]
#101 is a proposed mechanism for making this combination illegal.

**Comment by kevinb9n** [comment]
I have definitely moved away from "if it's legal Java we have to make a best effort" to "it's okay to define some things as beyond the pale".  `@Nullable @NonNull` being a poster child for the latter.

**Comment by kevinb9n** [comment]
I'm thinking that any time spent trying to decide the right graceful way to handle this baffling scenario would be time wasted.

We should specify that `@Nullable @NonNull` is an illegal combination of annotations and at least strongly encourage checkers to refuse to analyze code that even depends on such a monstrosity.

**Comment by kevinb9n** [comment]
Despite the "time wasted" pronouncement above, we reconsidered this in #242.
