### ISSUE TITLE
Policy toward implementation code

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#114]
"Implementation code" is anything inside either an initializer or the body of an executable, not including local classes (but including their own executable bodies, etc. -- inclusion/exclusion).

Such code is usually delimited by curly braces but we do also include field initializers (the part after the `=`, or an enum constant argument list) -- and note that even these can contain arbitrary statements, thanks to switch expressions. (This implies that the entirety of a lambda expression is also implementation code, which I agree with, but let's not argue over this right here.)

We tend to call everything else (that is not implementation code) "API", without regard to its visibility.

Our project does not have a requirement to standardize any treatment of implementation code, aside from its immediate *interactions* with the APIs outside itself.

But we can't avoid the topic entirely, for at least two reasons:

1. We might feel the need to actively disclaim any semantic implications of our annotations for implementation code, or at least be intentional about what we want to allow checker variation for.

2. We will be teaching users to understand a modified type system -- no more base types, now augmented types -- and they are accustomed to types working in the exact same way for local variables as in APIs, so we will need to counteract their assumptions in some form or another.

I believe the story (which has been well validated by CF [edit: that may have been dead wrong] and others) is something like this: Inside implementation code, type usages and expressions also have augmented types now. However, here the nullness of the root type (only) is *not* expressed declaratively. It is instead inferred by an analyzer, both because the tool doesn't _need_ the information from you as it does for APIs, and because this can allow the nullness of a single variable to actually shift over time based on the latest information. When you do know something the analyzer doesn't -- that a certain expression can't actually be null even though the analyzer assumes it can -- that's what we have things like `assert` for.

Or here's a different way to look at it [edit: which I don't prefer]: if we want to know the static types, then a local variable root types is always the more general nullable kind. As such there is no benefit to annotating them. But analyzers keep careful track of when they can safely "smart cast" for you.

This mostly talks about local variable types. Other cases:
* Instanceof and cast are both considered non-nullable type contexts (or "anullable" if you prefer to think of it that way), so should never be annotated.
* Lambda formal parameter types should be governed entirely by the target type; so again, should never be annotated.

I may have stated this wrong, and I'm not sure whether all analyzer owners would be on board with this in any case?

**Comment by donnerpeter** [comment]
Lambda parameters can be confusing, because they're basically the same as method parameters in an equivalent anonymous class, and AFAIU they're currently subject to the lexically scoped annotations, if present.

Otherwise this seems reasonable to me.

**Comment by kevinb9n** [comment]
(lambdas tangent:  in the case of an anonymous class with a method, that method is a real member, and there can be others, and these can call each other, which makes clear that they must be treated as API. The lambda case seems quite different; there is no class and no member (until runtime, but we're not caring about that in this context). I can't think of any reasonable reason for a lambda to need to choose different annotations on its formal parameters than the functional interface type did.)

**Comment by donnerpeter** [comment]
(lambdas tagent) Looks convincing, thanks!

**Comment by kevinb9n** [comment]
I continue to believe that we can't blindly wash our hands of implementation code.

For any type usage within implementation code:

* A compound type can certainly have a nullness annotation at the non-root level, with the usual well-defined meaning.

* A nullness annotation used at the root position is, I think, fundamentally different. Why? We expect tools to track root-level nullness flow-sensitively, which I think means that any nullness information permitted in these locations would constitute only "hints" or "assertions".

I don't at this point know what all the use cases for such hints or assertions are. If any were to get filed as issues then we could decide whether to specify our annotations as being definitely, definitely-not, or optionally usable in that specific case.

But in the meantime, what should our default be - to specify that the annotations can't be used there, or that they can with no centrally mandated meaning? If the latter, the risk is that different tools may ascribe incompatible meanings.

**Comment by kevinb9n** [comment]
Working decision: Generally, our annotations are unrecognized within implementation code, except as listed below:

1. All usages on non-root component types (e.g. `List<@Nullable String>`, `@Nullable String[]`) are recognized, wherever that type appears.
2. I believe usages as type arguments to a method/constructor, e.g. `Collections.<@Nullable String>singletonList(null)` are okay too.

**Comment by kevinb9n** [comment]
I have raised specific questions in #251 and #252 and #261 and might have more. No need to have this reopened though.
