### ISSUE TITLE
Nullability of a type based on generic parameter depending on the specific argument

### ISSUE THREAD

**Issue by dzharkov** [jspecify/jspecify#13]
Consider the following class:
```
interface Box<T> {
    T get();
    void set(T t);
}
```

Having a type `Box<@Nullable String>` or `Box<String?>` in Kotlin, what's the return type of `Box.get` then?
We had an idea to have a special annotation `@StrictNullness` for type parameters
that makes nullability of types based on them depend on nullability of the specified type argument

**Comment by kevinb9n** [comment]
This is all addressed by more specific issues now.
