### ISSUE TITLE
Consider allowing multiple top-level classes in a sample input

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#133]
Currently, we require a single top-level class. That makes class names more likely to be unique, but it requires any multi-class test to use nested classes or multiple files. The previous discussion was https://github.com/jspecify/jspecify/pull/122#discussion_r480334806.

**Comment by kevinb9n** [comment]
We still follow the Google style guide, right? So that can just settle this....

**Comment by kevinb9n** [comment]
I don't see any real proponents for this change (between here and the linked thread).
