### ISSUE TITLE
Ability to apply unspecified-nullness to an individual type usage (e.g. a type-use annotation like `@UnspecifiedNullness`)

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#137]
It's not time to make a decision on this yet, but I wanted to start collecting links to past discussions on the subject.

- #32 is about the _name_ of such an annotation, assuming that we have one in the first place.
- https://github.com/jspecify/jspecify/issues/128#issuecomment-700214870 points out that developers may write something like `@NullnessUnspecified List<String>` when they mean for the `String` part to have unspecified nullness, too.
- I had been thinking that Android had asked us for `@NullnessUnspecified V get(@Nullable Object o)` for `Map`. But I appear to be [wrong](https://github.com/jspecify/jspecify/issues/71#issuecomment-549883078). Possibly they'd still use `@NullnessUnspecified` for `findViewById`, but (a) I'd have to confirm _that_, and (b) a defaulting annotation ([if available!](https://github.com/jspecify/jspecify/issues/127)) seems sufficient there.
- https://github.com/jspecify/jspecify/issues/32#issuecomment-697920608 (leading into #129) discusses the impact that having such an annotation could have on error messages. Typically, one less annotation is one less annotation for us to name and for users to understand, but here, we may still need to pick a name, and users will still need to understand the concept.
- very minor: If we were to omit _both_ `@NullnessUnspecified` _and_ `@NonNull` (#4), that would make conflicting type annotations (like `@Nullable @NonNull String`) impossible (discussed somewhat in #100 and #101). (But it might still end up being possible for _defaulting_ annotations, depending on what happens with #127 and and #109.)
- I don't _think_ that omitting such an annotation will end up simplifying our rules much: Given a type with an explicit `@NullnessUnspecified` annotation on it, we can generally construct a similar API in which the type has unspecified nullness only _implicitly_ and the rest of the API's types likewise have similar nullness to the original API.

**Comment by cpovirk** [comment]
Writing that up in an appropriate level of detail was one of our objectives for these past few months. Real Life has interfered, but we're going to give it another shot in the coming months.

The too-short explanation of what it means: _We haven't yet considered how to annotate this type for nullness. Either it should have `@Nullable` on it, or it shouldn't. Tools may wish to assume the worst (roughly: don't let code put `null` into the type, but also don't let code dereference it), or they may wish to assume the best (roughly: behave like a stock Java compiler, letting you put `null` into the type _and_ dereference it)._ (Naturally, this all assumes that we've previously defined `@Nullable`.)

My hope has been that the too-long explanation can be based on https://jspecify.dev/tsttcpw.html. (Hopefully it will also be visible within in the next few weeks in our prototype CF checker.) But it's not yet clear whether tool authors will find those rules to provide the appropriate level of detail, nor whether tool authors and end users will approve of the results of those rules on real code.

**Comment by mernst** [comment]
Thanks.  I can see defaulting an entire class or package with such an annotation (is that what "in the club" or "not in the club" means?  I'm not sure), but what is an example where it is good style for a user to write this annotation explicitly?

**Comment by cpovirk** [comment]
> I can see defaulting an entire class or package with such an annotation (is that what "in the club" or "not in the club" means? I'm not sure)

(Yes. Settling on a term for that concept is partially covered by #87 and #109.)

> but what is an example where it is good style for a user to write this annotation explicitly?

The nicest thing that I personally have to say about it is that it's made it simpler to cover some unusual cases in the sample inputs :)

The other two potential uses I know of are:
- I have time to annotate only _part_ of a class right now. (We may provide other ways to do that besides this specific annotation.)
- I know how to annotate this type, but I'm worried that my users will get mad at me when tools start enforcing it. This is "the `findViewById` use case" (among other examples from #71), and it again ties back to questions about what `@Nullable` means.

**Comment by mernst** [comment]
Thanks.  That's very helpful.

> The nicest thing that I personally have to say about it is that it's made it simpler to cover some unusual cases in the sample inputs :)
> 
> The other two potential uses I know of are:
> 
> * I have time to annotate only _part_ of a class right now. (We may provide other ways to do that besides this specific annotation.)

This use case doesn't seem very likely to me.  I expect it is more trouble to go through a class and write `@NullnessUnspecified` on every type in an API, than to write `@Nullable` in those cases where it is needed.  Maybe someone else has evidence that this is a common need, however.

> * I know how to annotate this type, but I'm worried that my users will get mad at me when tools start enforcing it. This is "the `findViewById` use case" (among other examples from #71), and it again ties back to questions about what `@Nullable` means.

I don't think this is good style.  I think we should strongly encourage users to write accurate, honest specifications rather than inaccurate ones that pander to the limitations of some particular tool.  This opinion is independent of the meaning of `@Nullable`.  Tools can always have special-case behavior for known APIs, or they can extend Jspecify with extra annotations of their own.

**Comment by cpovirk** [comment]
We discussed this more in today's meeting. Here are [the notes](https://docs.google.com/document/d/1hr8Ld9cRMFksvA_Uzh61o4bdiVMXl084AR5QAkokEn0/edit#bookmark=id.lx8eisadq1ee).

The primary takeaway is probably:
> General undercurrent of support for a defaulting annotation over a type annotation to start.

**Comment by kevinb9n** [comment]
* The fact that an annotation like this is handy in our extremely artificial conformance tests doesn't make a case for its merit in the real world.
* If we deem it important that you can ever mix all three kinds of nullness in a single signature, then _either_ this or #4 would accomplish that.
* However, I will claim that that argument works much better as a case for #4 than it does for this, though. If it's not strong enough to justify #4 then I'm skeptical that it would justify this. (Note that #43 and #127 are leaning yes.) 
* IF we're yes on #4, then the advantages of _this_ feature are ergonomic only. And as we currently expect "yes" on #43 and #127, it's a small-scale difference.

But atm this seems like the biggest factor to me:

* If we have this, we may find it is rampantly used for #71 whether we have a better solution for that or not.

**Comment by cpovirk** [comment]
Agreed on basically all of that, particularly that this is "really about" #71 but also even that I would add `@NonNull` before adding `@UnspecifiedNullness` -- and you know how much I personally want to avoid adding `@NonNull` until we're absolutely sure we need it :)

Still, to be clear: I think that `@UnspecifiedNullness` provides us with the ability to fully mix all three kinds of nullness in a single signature but that `@NonNull` only _almost_ does. The difficulty is (as usual) type variables: If we want to say "Just this particular usage of this particular type variable has specified nullness," then there's no way to do that with `@NonNull` if the type variable allows nullable types.

Again, I think the best solution to that is to give up on guaranteeing that _every_ possible mix of nullness in a single signature declaration is possible, not to add annotations to make sure it's possible.

**Comment by cpovirk** [comment]
I just [learned](https://youtrack.jetbrains.com/issue/KT-47417#focus=Comments-27-5787640.0-0) from Victor that Kotlin APIs can include platform types. (Thanks, Victor.) It happens if a Kotlin method doesn't declare an explicit return type and the method returns the value of an unannotated Java method. For example:

```
==> j/p/J.java <==
package p;

public interface J {
  Object o();
}

==> k/p/K.kt <==
package p;

fun go(j : J) = j.o() // `go` has a return type that is a platform type.
```

So, if we want Kotlin to use pure JSpecify annotations to annotate its generated bytecode someday, then Kotlin needs support for [the "mixing" case discussed above](https://github.com/jspecify/jspecify/issues/137#issuecomment-1024864197). So either we need to offer `@NullnessUnspecified`, or Kotlin will need to take one of a few alternative approaches, all of them at least somewhat ugly:

- Avoid annotating the whole class with `@NullMarked`. (It could still annotate some types with `@Nullable` (and with `@NonNull` if we provide that -- though that may require additional logic to emit `@NonNull`, which wouldn't be necessary in most normal cases). And it might be able to individually annotate _other_ APIs in the class with `@NullMarked` -- but only if we allow that annotation on smaller scopes.)
- Annotate the whole method with `@NotNullMarked` (if we provide that). (Again, it's possible to then annotate some of the other types in the method.)
- Annotate the return type with `@Nullable` (which is _arguably sort of_ "never wrong" for the case of return types -- certainly safer than "non-null") and some other annotation that tells consumers not to strongly enforce that annotation on callers. (We don't know if we'll provide an annotation like that or not.)

(Or Kotlin could define its own annotation, which could "imply" `@Nullable` but explain that it "really means" something more like "unspecified.")

Would it make sense for us to file an explicit issue about "mixing all kinds of nullness in one signature" and/or "having Kotlin emit JSpecify annotations" -- the latter of which would also help with our goal of filing bugs to track which tasks block other tasks?

**Comment by kevinb9n** [comment]
If we do this (have an annotation I abbreviate as `@Unspec`), there is an awkwardness.

(I currently think) we would have to make `ImmutableList<@Unspec Foo>` an error even in null-unmarked code, even though it would _appear_ to just be redundant. (This because the type named doesn't actually exist, since the type parameter extends non-nullable Object.)

**Comment by cpovirk** [comment]
I think you're advocating for making `ImmutableList<@Unspec Foo>` an error in null-unmarked code but `ImmutableList<Foo>` _not_ an error in null-unmarked code? I see the logic in that, but I wouldn't go so far as to say that we'd "have to" even encourage it:
- It seems unlikely to come up often enough to be much trouble.
- It seems strange to treat code differently for naming the same type in two different ways (aside from merely warning about redundancy, which I think you're arguing is different from this): I'd say that "the type named doesn't actually exist" in _both_ cases. We could still encourage tools to treat it differently, but would this be the only such rule that would be stronger than the redundancy one?
- It seems like a way to trigger somewhat unhelpful errors in generated code that writes `@Unspec` automatically and happens to sometimes be generated in a null-unmarked package. (Maybe that's not too likely, though, if we assume that the code generator would write `@NullMarked` on its own class? But maybe it would come up when, e.g., someone moves a method from one class to another?)

If a tool wants to tell users about this kind of declaration, I would personally discourage it, but I wouldn't fight them on it. I think that going the other direction and _encouraging_ it is unlikely to be worth the effort, but if it's just "encouragement," I don't object to having some page somewhere that summarizes this discussion and explains why it could be a useful feature.

**Comment by kevinb9n** [comment]
I'm making the call that this annotation is the perfect example of the kind of annotation we should only add if dragged kicking and screaming into it. And sure, something like #71 could do it, but until then I'm closing. That will encourage a cogent argument to be put forth by someone wanting to reopen it.

**Comment by cpovirk** [comment]
This issue is going to get replaced with a new issue soon enough, but I'll drop two more notes for us to potentially pick up later.

The first note ties together two conversations that came up in meetings I was in today:

As we roll out nullness annotations inside Google, one of the things that we're doing is looking at tables of the APIs that have the most users but that lack nullness information. It's a little sad to imagine that, in order to find the APIs we actually want to annotate, we'd have to filter through a bunch of APIs that are _technically_ unspecified, not because we don't know their nullnesses but rather because annotating them would just be too painful:

```
// Spot the one method we actually want to go annotate now!
android.view.View#findViewById(int)
android.support.v7.app.AppCompatActivity#findViewById(int)
java.util.Map#get(Object)
com.google.common.collect.ImmutableMap#get(Object)
com.google.common.collect.ImmutableBiMap#get(Object)
com.google.some.foo.generateddatastore.Foo#lookup(Object)
java.util.HashMap#get(Object)
java.util.TreeMap#get(Object)
android.app.Activity#findViewById(int)
android.app.Dialog#findViewById(int)
java.util.regex.Matcher#group(int)
javax.inject.Provider#get()
com.google.some.bar.generateddatastore.Bar#lookup(Object)
java.lang.reflect.Method#invoke(Object, Object[])
android.view.Window#findViewById(int)
com.google.some.baz.generateddatastore.Baz#lookup(Object)
...
```

The hope would be that features like #26 or #27 could offer a way to say "nullable, but don't create a bunch of pain for callers." Even if nullness checkers ultimately treated that much like "unspecified," it would be nice for the code to contain the "honest" `@Nullable` annotation so that our stats can distinguish between "We don't know the nullness" and "We know the nullness but don't want to annoy callers" (or "haven't gotten around to updating all the callers yet").

**Comment by cpovirk** [comment]
The other note was specifically about generic methods, like `Map.get`:

The nice thing about saying that `Map.get` has an `@UnspecifiedNullness` return type (not that we're likely to decide to say that!) is that you can call `get(foo)` on a `Map!<Foo!, Bar!>` and get a `Bar*` out, at which point you see behavior basically like what you'd see with a `Bar!`. That makes sense if our goal is for checkers to behave like `foo` is a key that is present in the map: In that case, every call will return a `Bar!`.

But now consider a `Map!<Foo!, Bar?>`. We really want you to get a `Bar?` out of that: Even if `foo` is a key that is present in the map, `get(foo)` can return `null` because the value associated with that key can be... `null`.

So that brings us back to https://github.com/jspecify/jspecify/issues/248: What happens if we have the following:

```java
@NullMarked
interface Map<K extends @Nullable Object, V extends @Nullable Object> {
  @UnspecifiedNullness V get(@Nullable Object k);
}

@NullMarked
void x(Map<Foo, @Nullable Bar> map) {
  map.get(foo).something();
}
```

Does `map.get(foo)` return `Bar?` (current behavior, good from the narrow perspective of an unspec `Map.get`) or `Bar*` (possible future behavior)?

My guess is that this won't turn out to be a key point in either this issue or #248, but it feels notable as another way that withholding nullness information could have concrete negative effects.
