### ISSUE TITLE
Propagation of nullability info from overridden methods in supertypes

### ISSUE THREAD

**Issue by dzharkov** [jspecify/jspecify#14]
If there's an unannotated method having an annotated overridden method in a supertype, should we treat the former one as having the same nullability annotations as the latter? I.e, propagating the nullability info 

In Kotlin, we already do this for supported annotations

**Comment by kevinb9n** [comment]
Today, as long as you understand whether you're in a null-marked context or not, you can read code and know what the nullness of every type usage is. At most, you may have to scroll up to where a variable, type variable, etc. was declared to know it.

Any kind of automatic propagation/inheritance defeats that. If we did that even in a few odd cases, users would lose their ability to trust their own eyes, and nullness semantics would become mysterious.

Put simply: "`String` means `String`." Full stop. This is a core value of the project.

Here's another, more minor (but still real) issue: suppose we have, in null-marked context:

```
interface Foo<T extends @Nullable Object> {
    @Nullable T method(@NonNull T t);
}

interface Bar<T extends @Nullable Object> extends Foo<T> {
    T method(T t);
}
```

If either of the nullness annotations were automatically inherited from `Foo.method` to `Bar.method` ... how would `Bar.method` express that it doesn't want that inheritance in this case - that it wants `T` to be parametric? It's perfectly valid contractually (it is expanding the set of what it accepts, and refining the type of what it returns).
