### ISSUE TITLE
Samples formatting

### ISSUE THREAD

**Issue by mernst** [jspecify/jspecify#147]
The samples should use the recommended Java formatting style in which type annotations are written immediately before the type they modify, not on a separate line.  For example, `ClassToObject.java` should contain

```java
  @Nullable Object x6(ClassToObject x) {
    return x;
  }
```

rather than

```java
  @Nullable
  Object x6(ClassToObject x) {
    return x;
  }
```

This is important because we should not distribute sample code that is known to be written in poor style.

The samples could even contain a warning about mal-formatted code like the latter.  That seems more general (less specific to one particular implementation of JSpecify) than some of the current warnings like `jspecify_unrecognized_location`.

**Comment by cpovirk** [comment]
Maybe we should swap out `google-java-format` for something else until they let us hardcode a list of annotations to consider as type annotations. Any suggestions?

**Comment by mernst** [comment]
I think the best solution is to fix https://github.com/google/google-java-format/issues/5.  It requires reading a side file that lists "known type annotations".

Failing that, there is [run-google-java-format](https://github.com/plume-lib/run-google-java-format), which does the same thing, just in a less efficient and more hacky way.

**Comment by kevinb9n** [comment]
Thanks, I've poked at google/google-java-format#5; this samples issue is just the harbinger.

**Comment by kevinb9n** [comment]
Technically this could stay open until we have a solution that _keeps_ the samples formatted right - should we?
