### ISSUE TITLE
Should our default annotation to "undo" defaulting accept a "reason?"

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#149]
Assuming that we _have_ a `@NotNullAware`/`@DefaultNullnessUnspecified` annotation at all (#127), we may want to allow (or force!) users document _why_ they've left the method unspecified by having that annotation accept a value.

Here are [some notes from a meeting discussion](https://docs.google.com/document/d/1hr8Ld9cRMFksvA_Uzh61o4bdiVMXl084AR5QAkokEn0/edit#bookmark=id.vw9fnt1gqnh).

I had promised to look up a past Guava discussion about [our `@GwtIncompatible` annotation](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/annotations/GwtIncompatible.html). `@GwtIncompatible` used to _require_ a reason (a free-form string), but we removed that requirement. Our notes say that that was for 2 reasons:

- First, the reason is very frequently "I didn't get to it yet." Users can just type that, but it's friction. And we really want for it to be easy for users to apply the "positive" defaulting annotation (`@NullAware`/`@DefaultNonNull`) in the first place, without having to do "busy work" on each method that they opt back out. (There are arguably 2 sub-cases: "I didn't even try," and "I tried for a little, but it wasn't obvious." There's some value in capturing this, but perhaps it's good enough for the "I tried for a little" people to leave a comment (or an optional annotation value), since they've already demonstrated a willingness to invest time.)
- Annotation values get rendered in Javadoc. And they get rendered in an ugly code font and with `\"` every time someone uses a double quote in the value :( Guava no longer has any particularly ugly examples (because we removed them :)), but you can see a small example on [`newWeakInterner`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/Interners.html#newWeakInterner--).

**Comment by cpovirk** [comment]
Another reason to be nervous about this: Tools might starting using the `reason` value to do... something. I'm uncertain exactly _what_ they might try to do, but that uncertainty is reason itself not to provide the information in the first place: If we don't know how it will be used, we're unlikely to design it correctly, and different tools are likely to disagree on how to interpret it.

**Comment by cpovirk** [comment]
Also: If the "reason" were an enum value (rather than a free-from string), that [makes it more dangerous for downstream users to omit JSpecify from their classpath](https://github.com/jspecify/jspecify/issues/50#issuecomment-520468335).

**Comment by mernst** [comment]
I think there should not be a `reason` element.
You noted these negatives:
 * programmers may misuse the string
 * it adds clutter
 * other annotations like `@Deprecated` don't have a `reason` element

**Comment by kevinb9n** [comment]
I feel the same as with our old `@GwtIncompatible`: the text this would collect is exactly the sort thing `//` implementation comments are for.

**Comment by kevinb9n** [comment]
This appears decisive to me; reopen if desired.

**Comment by netdpb** [comment]
**Current decision**: No, because it would add complexity and serve no purpose not already served by a regular comment.

**Argument for changing**: None.

**Timing**: This must be decided before version 1.0 of the jar.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: `@NullUnmarked` will not have a "reason" parameter.
