### ISSUE TITLE
Error tag for uninitialized fields

### ISSUE THREAD

**Issue by mernst** [jspecify/jspecify#152]
Some of the sample `.java` files contain nullness errors.
For example, class `AnnotatedInnerOfNonParameterized` does not initialize the non-null fields `x5`, `x7`, `x8`, `l1`, `l2`, and `l3`.

This is a feature request to add new `// jspecify_*` tags indicating these errors.

(Alternately, change the code so that it initializes these fields.  But that does not seem to be in line with the current philosophy of the samples.)

To see the classes that are affected:

1. Clone and build the Checker Framework as usual.  (This will also clone and build JSpecify.)
2. In file `NullnessJspecifySamplesTest.java`, remove the statement that contains "initialization.fields.uninitialized".
3. Run `./gradlew :checker:NullnessJspecifySamples`

The result contains a number of differences between the Checker Framework and the JSpecify samples.  Some of these may be Checker Framework bugs or limitations, but it would be good to fix the ones that are not.

**Comment by cpovirk** [comment]
Thanks for the easy repro instructions.

I have put together a change to switch them all from fields to methods. It passes the CF test, but I may take this opportunity to make sure that a check or two is able to handle both fields _and_ methods. I should be able to finish it up Monday morning.

**Comment by cpovirk** [comment]
Oops, probably I should have just made them all *parameters*. Anyway, Monday.

**Comment by cpovirk** [comment]
Sorry, I should have left this open until addressing it more fully. I'll rehash part of the thread above and part of the discussion from Tuesday's meeting, and I'll add an update:

1. The existing samples weren't intended to demonstrate uninitialized fields. So, in the interest of avoiding "controversial" features except in samples that are specifically "about" those features, I changed the samples in fe68b72.

2. I do think that a sample containing uninitialized fields is a useful thing to have. I just now added one in ab0bd81fbb26b6935ef6e5656a9c5d905beba244.

3. Someday, we may hear from another tool owner who does _not_ want to report errors on uninitialized fields (and who doesn't want to branch our sample inputs to remove the relevant `jspecify_*` comments). I think it makes sense to add tags for such cases; I am just hoping to get away with doing so "on demand" -- that is, only _when_ the second tool vendor begins running tests that uses these samples and feels that the tag would be useful. At that point, we can reopen this issue (and then quickly re-close it with a commit to add the tag to the appropriate samples :)).

**Comment by mernst** [comment]
Thanks.  Rather than "controversial", I might say "tool-specific".  Segregating those makes sense.  That is why, for example, any file that contains jspecify_unrecognized_location errors contains *only* errors of that variety.  And similarly for uninitialized fields and other tool-specific errors.  Maybe writing a note about that could be helpful to others (though I am now on board :-).  Thanks again.
