### ISSUE TITLE
Terminology: "containing scope" -> "enclosing scope?"

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#154]
https://github.com/jspecify/jspecify/blob/v0.1/docs/spec.rst#defaulting-annotations-in-effect (which is derived from https://docs.google.com/document/d/15NND5nBxMkZ-Us6wz3Pfbt4ODIaWaJ6JDs4w6h9kUaY/edit#heading=h.u8phmghg96wr) says:

> For a given type usage, we define the defaulting annotation in effect to be the one located at the _nearest containing scope_ surrounding the type usage.

My impression is that the Java compiler APIs use the term "enclosing" for a similar concept. It might be nice to use that. That would also help distance us from [our concept of "containment" of type components](https://docs.google.com/document/d/1KQrBxwaVIPIac_6SCf--w-vZBeHkTvtaqPSU_icIccc/edit#bookmark=kix.erta3rcajlpm) and [the JLS concept of type-argument containment](https://docs.oracle.com/javase/specs/jls/se14/html/jls-4.html#jls-4.5.1) \[edit: and [yet another concept of "containment" possibly to come in a future JLS](https://bugs.openjdk.java.net/browse/JDK-8215321)\].

But there's a chance that there are subtleties here in what the compiler API considers to be "enclosed" by what, so I am filing an issue instead of making the change now.

**Comment by cpovirk** [comment]
But possibly the Java compiler APIs do _not_ consider a _package_ to be enclosed by a _module_? I haven't verified. Our concept of "containing scope" _does_ have that edge, so it may be a difference from Java's "enclosing scope."

(Java at least does not consider one package to be enclosed by another package. That much aligns with our usage.)

**Comment by cpovirk** [comment]
The Java compiler API does indeed consider packages to be enclosed by modules. See [`Element.getEnclosingElement()`](https://docs.oracle.com/en/java/javase/14/docs/api/java.compiler/javax/lang/model/element/Element.html#getEnclosingElement()).

"Enclosing" is probably the concept that we want.

**Comment by kevin1e100** [comment]
SGTM!

**Comment by kevinb9n** [comment]
This issue header filtered into my subconscious at some point and I started saying "enclosing" instead. It's good. We can keep fixing usages when we see them.

Good to know that modules do enclose packages. So it's just a special quirk of `@SuppressWarnings` that it doesn't respect all forms of enclosure.
