### ISSUE TITLE
Decide JSpecify's policy toward usages of `@Inherited` [working decision: document that we ignore it]

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#155]
We have previously said that annotations are _not_ inherited, but that conversation was about _type_ annotations (#14).

Now, I think it's clear that _our_ defaulting annotations will _not_ be inherited, either: We wouldn't want for the `@NullAware` annotation on `java.lang.Object` to imply that every class has been annotated for nullness :)

Still, a user might define a custom declaration annotation, declare that it "implies" our defaulting annotation, _and_ mark it with `@Inherited`. What do we do?

First, it's worth noting that at least one Java compiler API _automatically_ returns such inherited annotations. See [`Element.getAnnotation(Class)`](https://docs.oracle.com/en/java/javase/14/docs/api/java.compiler/javax/lang/model/element/Element.html#getAnnotation(java.lang.Class)) and [the definition of _present_](https://docs.oracle.com/en/java/javase/14/docs/api/java.compiler/javax/lang/model/AnnotatedConstruct.html) (as distinct from _directly present_) that it uses. So, if what we want to do is "ignore `@Inherited`," we may need to take explicit action in the form of avoiding that specific API. (We might instead use [`getAnnotationMirrors()`](https://docs.oracle.com/en/java/javase/14/docs/api/java.compiler/javax/lang/model/element/Element.html#getAnnotationMirrors()) -- possibly a better choice, anyway, since it avoids loading `Class` objects.)

But maybe we'd want to respect `@Inherited`. After all, if we didn't, we may violate user expectations and/or the contract of `@Inherited`. However, it seems unlikely that any users _actually_ mean for a defaulting annotation to be applied to subtypes. (See `Object` example above.) And [the contract of `@Inherited`](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/annotation/Inherited.html), if we squinted _really_ hard, could be read as a statement about the behavior of `Element.getAnnotation`, not as a statement about the behavior of any particular consumer of annotations.

This thread is also as good a place as any to note that an `@Inherited` annotation is technically inherited only by classes that _extend_ an annotated _class_ -- _not_ by classes/interfaces that implement/extend an annotated _interface_, nor by _methods_ that override an annotated _method_. (This behavior is somewhat surprising and somewhat not-useful, so some tools have chosen to apply their own rules. Maybe this gives us additional cover for doing whatever we want....)

Hopefully this just never comes up. But I learned a bit about it, so I'm writing it down here.

**Comment by netdpb** [comment]
Could we (for now) ban aliases for `@NullMarked` if they're `@Inherited`?

**Comment by kevinb9n** [comment]
I like that. All we really have to do is state in the Implies javadoc not to use it together with `@Inherited` or to expect nothing good if you do.

It's a bummer that there is even one API that does respect this ill-thought-out annotation, but I say the bug is with that API......

**Comment by kevinb9n** [comment]
As a working decision for the time being we will absolutely ignore `@Inherited` (except perhaps to speak to the fact that we absolutely ignore it and recommend users do the same).

**Comment by kevinb9n** [comment]
Reclassifying as doc bug, because I don't think we ever did this.

**Comment by kevinb9n** [comment]
Wait no, filed #493 instead

**Comment by netdpb** [comment]
**Current decision**: Because we are not planing to support annotation implication in 1.0 (#35, #307), this issue is not relevant for 1.0.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.
