### ISSUE TITLE
Configure build process to create a multi-release jar

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#161]
...and then create 2 separate copies of [`@DefaultNonNull`](https://github.com/jspecify/jspecify/blob/4fc89fd49663263394bfde630509056df10a816b/src/main/java/org/jspecify/annotations/DefaultNonNull.java), one that includes `MODULE` in its `@Target` values (for `--release 9` and higher) and one that does not.

Here are [some instructions](https://blog.gradle.org/mrjars#how-to-create-a-multi-release-jar-with-gradle) we could use.

Previous discussion: https://github.com/jspecify/jspecify/issues/34#issuecomment-768453364

**Comment by KengoTODA** [comment]
note: The mrjar provides no support for `javadoc` and `sources` jar. It means that, even to Java 9+ users, the javadoc tells that `@DefaultNonNull` is annotated without `MODULE` in its `@Target`.

When we enhance the javadoc (maybe as a part of #162), it would be better to tell this point to users.

**Comment by cpovirk** [comment]
We can definitely figure out Javadoc later on. I would like to think that Gradle makes it relatively easy to just pass the appropriate `java9` files or directory to `javadoc`. But that is easy for me to say when I have no idea how to do it :) Even if it's hard, I'm confident that we'll get it worked out.
