### ISSUE TITLE
Initial draft of a User Guide

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#162]
We've discussed this a number of times, but we haven't filed an issue. I'm filing one now because we'd ideally like to have this ready before the final release of Kotlin 1.5.

We may also want to produce "JSpecify for people familiar with Kotlin," one of the documents proposed in https://github.com/jspecify/jspecify/issues/123.

**Comment by kevinb9n** [comment]
Thanks Éamonn!
