### ISSUE TITLE
Move module-info.java to multi-release jar Java 9+ directory

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#172]
Now that we have a multi-release jar, we could do this.

I _think_ I heard this pattern suggested somewhere, but I'd want to confirm. But it's the end of the day, so I'm filing this issue and walking away.

(Note to self: If we do this, then I can simplify our internal Java 8 setup to ignore only `java9` instead of both `java9` and `module-info`.)

**Comment by cpovirk** [comment]
A couple suggestions of this pattern:

- https://github.com/google/guava/issues/2970#issuecomment-626684027
- https://openjdk.java.net/jeps/238#Modular-multi-release-JAR-files (despite some confusing wording that initially suggests that the module-info _must_ appear at the top level of the jar)

**Comment by cpovirk** [comment]
It's possible that this would eliminate the need for `modularity.mixedJavaRelease`...
https://github.com/jspecify/jspecify/blob/19961fa5ec1ad822106f52e6a1b427c8c3a111da/gradle/publish.gradle#L31
...which nearly got me into trouble [in 8135398](https://github.com/jspecify/jspecify/commit/81353983747a772e930890f24f72f83edc00c466#diff-d6dec2a6144229896b7142578a46e5aede6004e37b4fbde49f9cd2a129adef54R37), as noted in the description of https://github.com/jspecify/jspecify/commit/6fae6f081e170285eb8decae19249396eab0262c.

**Comment by kevinb9n** [comment]
Is this an issue purely of internal organization or does it affect the product?

**Comment by cpovirk** [comment]
I don't know a ton about this, but my impression is that it _could_ affect the product -- but I'm fuzzy on the details, _and_ we could do it in a patch release anytime.

One thing I've heard in the past is that some build tools blindly scan jars for `.class` files, and some such tools used to get confused by `module-info.class`, if only because it's necessarily built with `-source 9` or higher. Putting `module-info.class` under `META-INF` (as this feature request proposes) typically keeps those tools from discovering it.

That said, I would _hope_ that `module-info`-ignorant tools would be rare nowadays.

_That_ said, I don't know if there are _other_ reasons to move the `module-info.class`.

I'm highly comfortable calling this post-1.0.
