### ISSUE TITLE
Is redundant specification of @NonNull at inherently non-null places allowed?

### ISSUE THREAD

**Issue by amaembo** [jspecify/jspecify#173]
I see tests for warnings where Nullable/NullnessUnspecified annotations are specified at inherently non-nullable places. For example, AnnotatedReceiver.java. However, these tests assert nothing about the use of NonNull at the same places. Is it allowed, for example, to write `void notnullReceiverInvalid(@NonNull AnnotatedReceiver this);`? I'm inclined to forbid such redundant specifications. In either case, this should be covered by tests.

**Comment by cpovirk** [comment]
Thanks. We've been able to ignore this so far because we don't have a NonNull annotation in our repository. Assuming that that changes, we'll have to take care of this issue then.

**Comment by amaembo** [comment]
Oh, indeed there's no NonNull in the repository. Sorry I wasn't aware of recent discussions in this area. Ok, I will ignore this problem for now (though IntelliJ supports org.jspecify.annotations.NonNull if it present)

**Comment by kevinb9n** [comment]
If we do add @Nonnull, I'll spelunk through the resolved issues that mention it.

**Comment by kevinb9n** [comment]
And whatya know, I'm finally looking through the resolved issues.

Current stance: Nullness annotations are "not applicable" to such locations, and have no meaning if used there.

As for whether our tests should validate that a tool can recognize a finding in that location... this seems, at *best*, low-priority, and I'm not sure whether we'd ever really care?

I'm gonna leave this closed for now but if anyone thinks it should be reopened please do.
