### ISSUE TITLE
Define the role of the `samples/` directory

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#178]
I'm copying this from [a comment in #165](https://github.com/jspecify/jspecify/issues/165#issuecomment-776304646) to keep it separate from the other discussions there.

> I think there is some confusion about the role of the `samples/` directory -- certainly on my part.
> 
> I realize that the `samples/` directory says it is not conformance tests, but in reality is is conformance tests.
>  * The JSpecify participants are treating it like conformance tests.
>  * It is written in a machine-readable way to permit determining how an implementation differs from it.
> 
> If it's not conformance tests, why does it have expected errors and expected non-errors?
> 
> What is the process for deciding what to be in it and what should not?  It would be unfortunate if it tracks one particular implementation.
> 
> I think the `samples/` directory would be more useful to everyone if we clearly defined what is in it.
> 
> That's what I was getting at with my "normative" and "non-normative" distinction:  we expect nearly every implementation to issue all the normative errors, and some implementations may also issue other errors (the non-normative ones).
> 
> Maybe the normative vs non-normative distinction is a bad idea, in which case we should not adopt it.  But I feel we do need to do something to define what the samples are and how they should (and should not!) be used.
> 
> Thanks in advance for clarification.

**Comment by cpovirk** [comment]
(@mernst , whom I forgot to CC when initially filing this.)

First, a post with some high-level comments about the problem, without any actual answers to the questions:

I think that a large part of the problem is that the samples are trying to serve multiple objectives. Over time, some of those objectives should be fulfilled by other documents and resources. Over time, other objectives may become less important.

But we'll still have to watch out, as yet other objectives may become _more_ important in time :) Arguably that's what we're seeing here: More tool authors put in more and more support for JSpecify, increasing the demand for test cases.

One particular problem that we will need to watch out for is how the world at large interprets the samples. (I think this is at least part of your concern, though not the entirety of it.) I can try all I want to say "I wrote most of the samples, and even if it were in my power to unilaterally say 'This is the required checker behavior,' I would not do so." But that means very little if end users see "samples" and "mismatch" and then file bugs against the Checker Framework, IntelliJ, and Kotlin because there's no error reported on line _x_ (or there's an error reported on line _y_, where the samples _don't_ have a comment).

**Comment by cpovirk** [comment]
So... what _are_ the samples? On a simple but ultimately unsatisfying level, they're clear about this. We've made some changes to the details, but broadly, the samples show:

- locations for which JSpecify does not specify meaning for its annotations
- cases in which, if a tool applied JSpecify's rules for subtyping, same-type checks, and substitution in all the cases in which the JLS requires their plain-Java equivalents, without layering on any additional knowledge, it would issue an error

We call the latter "mismatches" (or, in some cases, "not enough information") to support the idea that they're not "places tools must issue errors" but rather "places where tools would issue errors, given the assumptions laid out above, none of which are required."

But again, I think this is all unsatisfying without an answer to the question of _why_ the samples are defined that way. As I also teased above, I had multiple reasons for that approach:

First, it lets us write samples that focus on a smaller number of design questions. For perspective, when I started the samples, I don't think we had even made an attempt at formalizing subtyping rules around "unspecified nullness." If every sample related to unspecified nullness had to be stating a proposed rule about _both_ unspecified nullness _and_ whether to apply subtyping/same-type checks _at all_ in this case, that would require resolving questions like #166 (or at least sidestepping them, as we've done for now) before we could speak to questions like "Are `List<@Nullable String>` and `List<@NullnessUnspecified String>` 'the same type?'" (And as you've noted, the potential questions go even beyond "Is this code an error?" and into questions of _where_ the error appears, as in #171.)

And that leads us back to the tension between objectives. As you've noted, tool authors (myself included) have found a need for test cases. Unfortunately, the moment we start saying "This annotation location is unrecognized for reason _X_, and this other one is unrecognized for reason _Y_," then we've begun prioritizing the "test suite" use case at the expense of the "focus on design questions" use case. I think that's a natural progression as the project develops. And I think it's good for the samples to evolve as our needs evolve.

I have made changes in this direction, myself: In my own experimentation, I have written many test cases that go outside the technical definition of what belongs in `samples`. I keep most of them out of that directory. But when I see one that looks uncontroversial enough (`Foo foo = null; foo.bar();`), I put it in there in case it's of value to others as a test case.

All of this leads us into the uncomfortable position we're in now. The good news is that people seem to find the samples useful overall, though there are problems that we should continue to try to address. Nevertheless, I am not sure that we can make a stronger statement about "what the samples are." I am just hopeful that we can muddle along in spite of that.

**Comment by cpovirk** [comment]
Anyway, I don't know if any of that has been clarifying or convincing. But jumping ahead a bit, this should all eventually lead to our updating the readme, making it less coy about what we do with the samples. I think it would be uncontroversial to say something like:

> The samples are designed to be easily adapted into test cases for tools that look for nullness type errors. Because JSpecify does not require or forbid reporting an error for any particular piece of code, tool authors will have to make changes to the samples unless they make all the following choices:
> - They use all information provided by JSpecify annotations.
> - They add no other information from other sources. (For example, when deciding whether to report an error for a dereference on the result of a method, they do not look at the _implementation code_ of the method to determine whether it can return `null` in practice.)
> - They implement all JSpecify rules for subtyping, same-type checks, and substitution, and they apply all those checks in exactly the same cases in which the JLS requires their plain-Java equivalents.
> - When a JSpecify annotation appears in a location not recognized by JSpecify, they either issue an error for all such locations or no such locations. \[We can loosen this one slightly as a result of #135 and future progress on #165, both of which let tools choose a specific behavior for each category of unrecognized location that we define.\]
> - When JSpecify says that the nullness of a type is unspecified, they either consistently make assumptions that preserve soundness, or they consistently make assumptions that are optimistic. If the former, then they should report errors on every line with `jspecify_nullness_mismatch` or `jspecify_nullness_not_enough_information`; if the latter, they should report errors only on every line with `jspecify_nullness_mismatch`.

(I'm ignoring for the moment the question of whether we should remove samples like `Foo foo = null; foo.bar();`. Technically they're outside this definition, but we can try to carve off an exception for samples that "everybody" wants. Or we can put those files in another directory that comes with a less strict definition.)

Hopefully this can express that the samples are a "common reference point" -- not that they're a "baseline" that every tool must implement, just that they provide a mechanical definition so that every tool can say, for example, "I make all of those choice _except_ that I allow contravariant parameters and I forbid covariant array conversions," and it's relatively straightforward to identify whether a give sample falls into those categories.

**Comment by mernst** [comment]
Here are some questions and comments about the test suite:
 * If tool authors are intended to build test suites based upon it, it would be helpful to use a more liberal license to ease reuse.  (The tests would need to be in a separate repository in that case.  This does not seem like a major hurdle.)
 * What gets included in the test suite?  Why is `@NonNull` omitted but `@NullnessUnspecified` included, given that neither of those is currently part of JSpecify?
 * The test suite should not cater to any particular tool or analysis.
    * I think it is desirable to include tests that every current tool fails.  This will emphasize to users that tools may behave differently and that no tool is perfect.

In the meanwhile, we agree not to do any more releases or advertising of JSpecify until this is unambiguous.

**Comment by cpovirk** [comment]
I've tried to incorporate some of the above information into the README in https://github.com/jspecify/jspecify/commit/3c2e870e7e025f86917167b11089a14cd0bb6f40.

I dug up the link to [the earlier discussion of licensing](https://docs.google.com/document/d/1hr8Ld9cRMFksvA_Uzh61o4bdiVMXl084AR5QAkokEn0/edit#bookmark=id.3oezncw7w4i5).

RE: "I think it is desirable to include tests that every current tool fails." I don't have a list of what checkers issue diagnostics where, but I would bet money that this is already the case :)

I don't think we have a plan for what our remaining releases will be, but we will definitely need to resolve some of the remaining issues before a 1.0. We'll have to figure out how we incrementally get from here to there.

**Comment by kevinb9n** [comment]
I admit to not having fully-digested the thread, but am gonna do my thing where I provide a naive viewpoint to find out how far it gets us or where it fails.

So a wild proposal:

"The samples/ *are* conformance tests. To be conformant, a tool must be capable of correctly deriving Conclusion X from Scenario Y. However, having made that inference, the tool is at liberty to surface (or not surface) Conclusion X however it pleases."

Now I'm sure this is damned *unusual* for a conformance test. In technical point of fact it doesn't guarantee any two tools do any one thing the same. But if it steers each vendor to make only *intentional* how-do-we-surface-this decisions, then I think we end up with only *intentional* differences between tools. ?

**Comment by kevinb9n** [comment]
What I see as the next alternative is:

These are the tests for the reference checker, full stop. We share them for vendors' convenience. The spec itself is the authority on what changes vendors can make. If a vendor is maintaining a fork of these tests, it will always be easy for all to see in exactly which ways they diverge.

**Comment by kevinb9n** [comment]
1. so declared (the current name also already supports it)
2. done
3. #232
