### ISSUE TITLE
Not-Null-By-Default semantics

### ISSUE THREAD

**Issue by wmdietlGC** [jspecify/jspecify#18]
In a not-null-by-default context, nearly all type uses are not-null by default:

- Field, parameter, and return types are NotNull
- Type arguments are NotNull
- Array components and array dimensions are NotNull
- Implicit and explicit upper bounds of type parameters are NotNull, see https://github.com/google/codeanalysis-annotations/issues/12#issuecomment-452956700

Exceptions are:
- Local variables are `@Nullable` and flow-sensitive type inference is used to refine the type
- Class declarations are `@Nullable`, see https://github.com/google/codeanalysis-annotations/issues/7#issuecomment-452955826
- Cast and instanceof types depend on the expression type, that is:
```java
	@Nullable Object no = …;
	@NotNull String s = (String) no;
```
will treat the cast as `@Nullable` and therefore the assignment will give a warning.

**Comment by kevinb9n** [comment]
This has been addressed by more specific issues.
