### ISSUE TITLE
Decide on final names for JPMS module and Maven artifact

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#181]
We discussed these questions a bit in the threads linked from https://github.com/jspecify/jspecify/issues/160#issuecomment-786769558, but I don't think we tried to draw the wider group's attention to them. We don't need to do that even now (though people are welcome to chime in anytime!), but I wanted to file this so that we don't forget to come back to it months in the future.

In my commit to rename the _package_ from `org.jspecify.annotations` to `org.jspecify.nullness`, I'm taking the liberty of renaming the JPMS module and the Maven artifact, too:

- `org.jspecify.annotations` -> `org.jspecify` (similar to the package change)
- `org.jspecify:annotations` -> `org.jspecify:jspecify` (likewise, and both the old name and the new were options noted back in https://github.com/jspecify/jspecify/issues/108)

**Comment by kevinb9n** [comment]
Without laying specific odds on it, I think we should assume that `org.jspecify` might sooner or later host additional artifacts besides the annotations; #220 has some _possible_ examples.

I can't really imagine needing to split up annotation artifacts though.

Put together, it surprises me just a bit that we wouldn't call this `org.jspecify:annotations`. That's... exactly what it is and what I expect it to always be, and... well, why not?

I don't think it's a disaster if the annotations artifact grabs the top billing; it just seems subjectively odd/unnecessary to me, that's all.

**Comment by cpovirk** [comment]
The package rename from `org.jspecify.annotations` to `org.jspecify.nullness` was arguably not worth the trouble.... But once we did that, it seemed to make sense to rename the module and Maven artifact, too. And now that the Maven artifact is out there, it would be _nice_ not to rename it (https://jlbp.dev/JLBP-6) -- though we could probably get away with it for a pre-1.0 library if we really wanted.

I don't think there was ever much discussion of the artifact name. One nice feature of plain "jspecify" is that there's no question of whether it's "annotation" (singular) or "annotations" (plural), as debated back in #1.

(Oddly, we have an inverted situation inside Google, where we call the Bazel target "jspecify_annotations" and there's been some discussion of changing it to plain "jspecify" :))

**Comment by kevinb9n** [comment]
I'm more comfortable now with the idea of the annotations artifact getting the primary name of "jspecify" itself, for both the module and the maven artifact. I think we can close this.

**Comment by kevinb9n** [comment]
(also ran this by the group in our meeting. we're good)
