### ISSUE TITLE
Aliasing/implies: What do we say about aliases for non-JSpecify annotations?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#182]
That is: Suppose that some project _other_ than JSpecify declares an annotation `@Foo` _and_ that that project (or even _another_ project) declares an annotation `@Bar` with `@Implies(Foo.class)`. Should this "work?"

Of course it can't possibly fully "work": I can annotate my custom annotation with `@Implies(Deprecated.class)`, but `javadoc` and `javac` are never going to recognize my custom annotation as a way of deprecating things. But if _some_ tools already recognize JSpecify annotations, including aliases in general, then maybe it's useful to be able to be able to define one class-scope annotation that implies both [the JSpecify "defaults" you want](https://github.com/jspecify/jspecify/issues/34#issuecomment-504510728) and any other "defaults" you want (e.g., `@ParametersAreNonnullByDefault` or your custom `@TypeQualifierDefault` annotation). (Granted, if you're still using one of those two annotations in particular, that's probably a sign that you're supporting some tools that don't recognize JSpecify -- and thus won't recognize aliases :))

Of course, one question here is what counts as "a JSpecify annotation." Presumably we'd judge that based on the package name. But if we say that users _can't_ create aliases for non-JSpecify annotations, then will users try to put their custom annotations under `org.jspecify.ext.com.mycompany`? (I guess this is the kind of thing that JPMS exists for.)

I'll file a related issue #183 in a moment.

**Comment by kevinb9n** [comment]
Using your example, `@Implies(Foo.class) public @interface Bar {}`,

And always starting from the naive view:

I use some API, which is documented as "JSpecify-compliant" (#handwave #notangent), to ask whether the `Qux` class has the `@Foo` annotation. Then I would expect to get `true` for either `@Foo Qux` or `@Bar Qux`.

Are there technical obstacles to that working, or other reasons why we might want it to not work?

Note that we can view `@Implies` as a special tool we use to provide behaviors we need, or as a bona fide "product" offering in its own right, that anyone can use in similar ways to how we ourselves use it. I'd always hope first that we can achieve the latter.

**Comment by kevinb9n** [comment]
And so while there's nothing _inherently_ fishy about `@Implies(Deprecated.class)`, it doesn't affect javac because javac is not "JSpecify-complaint". (A savvy user might even guess that it isn't, because it "feels" lower-level than that.)

(Whereas, things you plug into javac (annotation proc? error prone?) are JSpecify-compliant or not depending on whether they call javac APIs _directly_ or go through the neato keen library wrappers we could provide them......)

**Comment by kevinb9n** [comment]
Please reopen if and when there are reasons to exclude non-JSpecify annotations from using `@Implies` with the same semantics we do.
