### ISSUE TITLE
Aliasing/implies: Do we permit levels of indirection?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#183]
If `@Foo` implies `@Bar` and `@Bar` implies `@Baz`, then I'm guessing that we'd treat `@Foo` as implying `@Baz`.

If nothing else, this could be useful in case we ever want to "rename" one of our annotations. For example, if `@NullMarked` still had that name at 1.0 but we decided later that `@NullExplicit` was sufficiently better, we could support both by making `@NullExplicit` an alias for `@NullMarked`. In that case, users would probably like to be able to specify either `@Implies(NullMarked.class)` or `@Implies(NullExplicit.class)`.

(That said, we aren't strictly _forced_ to use aliasing for a "rename": We could always just write a one-off rule that says that `@NullMarked` and `@NullExplicit` are synonyms. However, this won't help users of tools that predate the new name, whereas aliasing would. Plus, it feels a bit like a failure of the aliasing feature if we can't use it for this purpose. Regardless, our preference is going to be not to have to rename anything in the first place, as it would be messy no matter what :))

If we do permit indirection, we should consider how it interacts with non-JSpecify annotations (#182): If `@Baz` is a JSpecify annotation but `@Bar` is not, then does `@Foo` still imply `@Baz`?

**Comment by kevinb9n** [comment]
"Implication" is the simple and useful semantic and is by definition transitive. So that's the wish-list and if technical hurdles come up with we'll have to see what we can do?

**Comment by kevinb9n** [comment]
This issue currently lacks "cons" and whenever either pros or cons are missing it should be closed.

**Comment by kevinb9n** [comment]
This should be seen as a dup of #213, now.
