### ISSUE TITLE
Nullness: Generic type semantics

### ISSUE THREAD

**Issue by wmdietlGC** [jspecify/jspecify#19]
# Type parameter declaration

A type parameter has both an upper and a lower bound.
The top of the type hierarchy is `@Nullable j.l.Object` and the bottom is `@NotNull j.l.Void`.
The `null` literal has type `@Nullable j.l.Void`.

See https://github.com/google/codeanalysis-annotations/issues/12#issuecomment-452956700 for a discussion of upper bounds.

An annotation on the type parameter declaration itself can be used to annotate the lower bound:

```java
class NullonlyData<@Nullable T extends @Nullable Number> { T g; }
```

Note that the lower bound annotation is important to decide what assignments are possible.
Within NullonlyData, `null` can be assigned to field g, because NullonlyData can only be instantiated with an `@Nullable` type argument.
We feel that this is useful in rare cases and propose to forbid annotating a type parameter declaration, even the short form `class C<@Nullable T>`. Instead the explicit `class C<T extends @Nullable Object>` should be used.

# Type parameter use
An annotation on a type parameter use overrides the upper and lower bound annotation.

```java
class Cache<T extends @Nullable Object> { @Nullable T cache; }
```

Within class Cache it is possible to assign `null` to field cache, because of the `@Nullable` annotation.

# Wildcards
A wildcard can have an annotation on the wildcard itself and on the explicit bound. The annotation on the wildcard itself applies to the bound that is not explicitly specified.

```java
class List<T> {  // @Nullable Object upper bound; @NotNull Void lower bound
    T f;
}

- List<?> l1; // @Nullable Object upper bound; @NotNull Void lower bound
    Read of l1.f: @Nullable Object, from upper bound of T
    Write of l1.f: not possible, as lower bound is @NotNull Void

- List<@Nullable ?> l2; // both bounds @Nullable
    Read of l2.f: @Nullable Object
    Write of l2.f: possible, but only with `null`

- List<? extends Number> l3;
    Read of l3.f: The type depends on the upper bound from the type parameter declaration
        and the bound of the wildcard, so here we get the intersection of @Nullable Object
        and @NotNull Number, so in effect we can read @NotNull Number
    Write of l3.f: @NotNull Void lower bound, no writes

- List<? extends @Nullable Number> l4;
    Read of l4.f: effectively @Nullable Number
    Write of l4.f: @NotNull Void lower bound, no writes

- List<? super Number> l5;
    Read of l5.f: Upper bound from type parameter declaration, @Nullable Object
    Write of l5.f: @NotNull Number types or their subtypes can be written.

- List<? super @Nullable Number> l6;
    Read of l6.f: @Nullable Object
    Write of l5.f: @Nullable Number types or their subtypes can be written.
```

**Comment by kevinb9n** [comment]
I'm closing this out as being too broad; I think it is covered by more focused issues. If you made points in here you don't want to get lost, please try to figure out where they more properly belong.
