### ISSUE TITLE
How much do we normatively address whether a specification is "appropriate?"

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#206]
My goal with the term "appropriate" is to avoid using terms like "well-formed" that I think cover more ground than I intend. So, while I don't intend this particular issue to focus on the question of what term to use, I do want to outline what questions I am and am not trying to cover as part of this one discussion. And if there is a better term for what I'm trying to cover, I'm happy to switch to it.

Here are some things that I'm _not_ trying to discuss here:

- [`@Nullable @NonNull String`](https://github.com/jspecify/jspecify/issues/100): I think we all agree that we will not define semantics for this. (We would probably non-normatively encourage tool authors to report such declarations to users.)
- `@Nullable int`: similar, though we might not care as much about bothering with a non-normative statement
- [`class Foo extends @Nullable Bar`](https://github.com/jspecify/jspecify/issues/17): similar, though it's conceivable that an individual tool could find a use for this syntax, in which case tools might not want to report it to users

Here are some things that I _am_ trying to discuss here, as I claim that they touch on the same underlying principle (though, to be clear, they each add their own peculiar concerns on top of that):

- How much do we normatively address [parameter contravariance](https://github.com/jspecify/jspecify/issues/49) and other contractual strengthenings?
- How much do we normatively address [contractual weakenings](https://github.com/jspecify/jspecify/issues/111)?
- How much do we normatively address [type arguments](https://github.com/jspecify/jspecify/issues/158)?
- How much do we normatively address [arrays](https://github.com/jspecify/jspecify/issues/65)?

Setting aside the actual questions of _what our normative text would say_ in any of those cases, we still have questions about _how much we get into these kinds of questions_ in the first place.

I see at least a few options. Each of the options can still be supplemented with non-normative recommendations, but I'm particularly interested in what we _officially specify_:

1. Officially avoid taking a position. Authors of nullness checkers are likely to do what their users expect. But for cases like arrays and parameter contravariance, different tool authors may make slightly different choices, decreasing interoperability. Still, if tools were to reach the point of agreeing about nullness except for those two things, I think we would have made the world a much better place -- if perhaps not _as_ good a place as we could have.
2. Officially list all the language constructs for which JSpecify takes a position, along with the checks that apply to those constructs. This provides a convenient reference for tool authors, and it provides common ground for users to depend on. On the other hand, it limits tools' ability to provide different checking to serve different user preferences. (It also -- and I'm not sure if this is on net a good thing or a bad thing -- may require more updates for future versions of Java. And of course it doesn't cover other languages -- and, for better or for worse.)
3. Officially give an underlying principle that covers all the cases we care about. This is great if we can pull it off, but I fear that it will be tricky identify a principle that is universal _and_ precise enough to serve as a true specification.

I could imagine a future world in which we do (2). But for now, I personally think we have enough on our plates that it makes sense to focus initially on (1).

For specific cases like arrays and parameter contravariance, I think it still makes sense to _supplement_ a normative statement along the lines of "We do not say when you need to check whether `T` is the same type as `U`" with a non-normative comment like "In particular, while we anticipate that many tools will perform checks in the same cases as Java does, they may be able to provide a better experience by performing checks in fewer cases, such as to provide parameter contravariance (which preserves soundness), or in more cases, such as to provide invariant arrays (which increases soundness)."

**Comment by kevinb9n** [comment]
I'd say the basic goal of our annotations is "successful communication from the developer" (like any language or API feature, I think). So that's why:

* The three cases you're _not_ discussing are so easily ruled out
* Disallowing parameter contravariance (while not _wrong_) is sad because it leaves useful information uncollected
* Our same annotations that have such clear meanings for non-array parameter and return types kind of fall apart with array types because the developer can't communicate separately about "if you read from" vs. "if you write to".

**Comment by cpovirk** [comment]
Your comment reminds me that I should note something that's at least been hinted at in various previous discussions:

The most obvious action for a tool to take when it sees an "inappropriate" specification (like a method whose return type is less specific than that of the method it overrides) is to issue an error at the site of that specification.

But there's at least one more action that a tool might take. Let's assume that the user manages to compile code with that "inappropriate" specification, either by suppressing an error or by compiling with a compiler that doesn't perform nullness checking. At that point, a tool still might _not respect_ that specification _at usage sites_. That might mean treating the type in the same way that the tool treats types with unspecified nullness. Or it might mean deferring to another specification, like that from the method that's being overridden.

(For better or for worse, this second action _may_ currently be hypothetical, with the exception of [a Kotlin behavior](https://github.com/jspecify/jspecify/issues/49#issue-471586073) that [I'm not sure matters much in practice](https://github.com/jspecify/jspecify/issues/49#issuecomment-878342831).)

When we decide how much to get into "inappropriate" specifications, we should have both of these possible actions in mind.

**Comment by cpovirk** [comment]
I think that this issue is too general to make progress on any of the specific questions but also not general enough to cover _every_ "bucket" that we might be interested in taking a position on. I'm closing it with the intent of picking up the more specific and more general discussions separately later on, perhaps starting from some ideas that kevinb9n has been batting around.

**Comment by cpovirk** [comment]
(Our [answer](https://docs.google.com/document/d/1Dq1bIGG1-qGj6PapsF5dV3Xr1RlYe4z7ZwMiEfxX7jE/edit) here is going to be to require tools to _identify_ various situations _when running conformance tests_. This doesn't mandate any user-facing behavior, but it acts as a nudge in one direction, one that tools would at least have to knowingly deviate from if they are otherwise attempting to pass the conformance tests. Then we get to make individual decisions about which situations to cover, as we've been doing in various issue threads.)
