### ISSUE TITLE
Eclipse nullness analysis interaction

### ISSUE THREAD

**Issue by wmdietlGC** [jspecify/jspecify#21]
Information at:
- https://help.eclipse.org/2018-12/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_null_annotations.htm
- https://wiki.eclipse.org/JDT_Core/Null_Analysis

See how CodeAnalysis annotations would interact with the Eclipse analysis.

**Comment by kevinb9n** [comment]
No one's going to be working on this for the time being.
