### ISSUE TITLE
Support for one annotation that implies many

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#213]
I'm pretty sure that we've been assuming that we'll do this -- for example, as a way to let projects define a single annotation that implies all the defaults they want, as in:

```
@Implies({NullMarked.class, CheckReturnValue.class, ...})
public @interface MyDefaults {}
```

But I haven't dug up a completely clear statement of that. The closest I've come is:
- a "..." in https://github.com/jspecify/jspecify/issues/35#issuecomment-681124790, which might indicate that the annotation supports multiple values (I guess not technically varargs) or might indicate a pause in speaking :)
- the idea that [annotations might have `@Target(ANNOTATION_TYPE)`](https://github.com/jspecify/jspecify/issues/35#issuecomment-504513291) in order to let you write `@NullMarked @CheckReturnValue public @interface MyDefaults`, which would allow you to have one annotation imply many unless we specifically say that that doesn't work

(Sorry if I just missed some existing direct statement.)

Even assuming that we do this, there is the smaller question of whether the varargs approach of `@Implies({NullMarked.class, CheckReturnValue.class, ...})` is supported or whether you have to employ the `ANNOTATION_TYPE` approach. \[edit: [#215](https://github.com/jspecify/jspecify/issues/215)\]

(And assuming that we do allow this, I'll have a followup issue to file, but I won't do that now.)

**Comment by kevinb9n** [comment]
Being limited to one would seem quite wrong to me. And I think the meta-annotation approach should be rarely needed.

Sure, if someone makes a single MyNullable annotation that implies a whole bunch of other known competing nullable annotations, that doesn't sound great, but I feel like there are disincentives to do that anyway (and there shouldn't be much motivation _to_ do it, either).

Can we just make `@Implies` "repeatable"? That was supported at the same time as type-use annotations. I like that that way there can be no question of what it means. They are independent facts about the annotation type.

**Comment by kevinb9n** [comment]
When it comes to `@Implies` it seems like you have a highly developed view of what you count as "sophisticated".

But from my point of view, by the time the hard part is done of speaking to all the different scenarios that can happen, then handling those scenarios in a slightly more useful way doesn't seem that much harder/riskier. IOW punting doesn't even get us out of that much imho.

The way I see it `@Implies` just simply doesn't give a crap whether the same annotation it's applied to also wants to imply other things too. It's not trying to "own" the whole picture of what this annotation does. It's just expressing one aspect, and another `@Implies` ought to be able to express another.

The one caveat to that is that yeah, it may represent just one additional small wrinkle to speak to when we define how precedence works in general for Implies (including if we define how it _doesn't_ work). If this somehow turns into a disaster we can reevaluate.

**Comment by Mooninaut** [comment]
> When it comes to `@Implies` it seems like you have a highly developed view of what you count as "sophisticated".
> 
> But from my point of view, by the time the hard part is done of speaking to all the different scenarios that can happen, then handling those scenarios in a slightly more useful way doesn't seem that much harder/riskier. IOW punting doesn't even get us out of that much imho.
> 
> The way I see it `@Implies` just simply doesn't give a crap whether the same annotation it's applied to also wants to imply other things too. It's not trying to "own" the whole picture of what this annotation does. It's just expressing one aspect, and another `@Implies` ought to be able to express another.
> 
> The one caveat to that is that yeah, it may represent just one additional small wrinkle to speak to when we define how precedence works in general for Implies (including if we define how it _doesn't_ work). If this somehow turns into a disaster we can reevaluate.

I think a single level of `@Implies` is all that should be permitted. I suspect allowing recursive `@Implies` will add complexity to implementations with _very_ little benefit to real projects, for several reasons.

### Implementation and specification complexity
* Recursively defined annotations require implementations to detect infinite loops.
* Recursive annotations require implementations to resolve potentially large nested trees.
* Recursive annotations will bloat the specification with priorities and conflict resolution rules.

### Lack of use-cases
* Any project should define its aliases in one place, which makes keeping them in sync straightforward.
* Projects shouldn't define more than a handful of default sets, or the benefits of consistent defaults disappear and they might as well use individual annotations.
* Defaults shouldn't change often, or again, the benefits of consistency disappear.
* Recursive annotations create enormous potential for "action-at-a-distance" bugs where a change in one place breaks things far away.

**Comment by kevinb9n** [comment]
> I think an external config file with defaults and match expressions is a likely eventuality, whether it instructs a tool to add/remove annotations or is read by checkers directly. However, it's probably premature as of 1.0.

I think tools will do things like this, and I don't especially expect to be standardizing any of it, but things could change.

I think we've done a good service if such tools are at least able to say "the effect of setting this option is exactly as if <<annotation>> appears on every ... etc.".  That makes the behavior nicely definable.


> A half-step in complexity and expressiveness between an external config, and annotating every single package, could be a recursive package-only annotation that applies its arguments to subpackages.

[... within the same module.]

I think we're unlikely to lean more into package annotations, and unlikely to do anything about "subpackages" (which aren't really a concept at all in Java).

The direction we've been leaning instead is allowing specifications of how to actually *rewrite* class files (#98), with a tool that will apply such rewrites to `**/*.class` or whatever, and *possibly* (?) with libraries that read class files *as if* they were rewritten (part of #220). I have..... a dense 7-page document about this format/tool that's not public yet and basically low-priority.

**Comment by kevinb9n** [comment]
With `@Implies(Two.class) @interface One {}`, One is allowed to add additional semantics of its own. It doesn't make sense to forbid it from doing so. It also would not make sense if those additional semantics for some reason can't be that it also implies another annotation. It would be unnatural and weird. There's nothing about implication that suggests "you can only have one".

I feel comfortable resolving this until some compelling argument-against happens.

**Comment by netdpb** [comment]
**Current decision**: Because we are not planing to support annotation implication in 1.0 (#35, #307), this issue is not relevant for 1.0.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by wmdietl** [comment]
I find the mismatch between the `working decision` in the issue title and the `current decision` in the summary comment confusing. I'm also confused by the `needs-decision-before-jar-1.0` tag together with `needs-decision-post-1.0`.
My thumbs up is for not including `@Imply` for 1.0 jar. I didn't not think about the original question of this issue.

**Comment by netdpb** [comment]
@wmdietl That is confusing. The proposal is to reopen this, confirming that it is irrelevant for 1.0.
