### ISSUE TITLE
Dependent nullness

### ISSUE THREAD

**Issue by nmatt** [jspecify/jspecify#214]
There are methods where the nullness of the result depends on the nullness of an argument. One example is `Objects.toString(Object, String)`, where the result is null iff the second argument is null. Other examples are "null-transparent" methods like `static URI toUri(String uri) { return uri == null ? null : new URI(uri); }`. It would be helpful to be able to annotate those accordingly.

One way to do that would be to assign an optional name to a `@Nullable` annotation, with the semantics of "same nullness" for all annotations using the same name in the same "scope" (to be defined). For example:

```
public static @Nullable("s") Object toString(Object o, @Nullable("s") String nullDefault) { ... }
```

Alternatively, introduce a dedicated separate annotation.

**Comment by cpovirk** [comment]
Hi, and thanks. We're currently tracking this under an issue named after the [Checker Framework](https://checkerframework.org/manual/) annotation `@PolyNull`, https://github.com/jspecify/jspecify/issues/79. (That thread is _much_ too long, so we will eventually write a separate doc or two to lay out the goals and design questions in a more digestible way.) I'll close this issue, but I'll make a note about the `@Nullable("s")` approach on #79, as I didn't see it discussed there during my quick skim of the thread.
