### ISSUE TITLE
@Implies syntax (array or repeatable?)

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#215]
I'd like to propose that #35 and #213 be focused on requirements questions. That way, we can break off smaller issues for details -- such as this one.

Between those two threads, we have a few options for how to declare the one annotation implies another:

1. `@Implies({Foo.class, Bar.class}) @interface MyAnno {}`
2. `@Implies(Foo.class) @Implies(Bar.class) @interface MyAnno {}`
3. `[@MetaAnnotated] @Foo @Bar @interface MyAnno {}`

(This issue isn't intended to be about _names_, just the choices between the 3 patterns above.)

The main choice is probably between option 1/2 and option 3. (Or we could support both.)

A possible advantage to option 3 is that is works naturally with annotations that have elements. That is, you can define an annotation that implies `@Foo(bar = "baz")`. Or maybe annotation elements are tricky no matter what. (Thankfully, we've mostly been leaning toward avoiding them.) For example, maybe it's _better_ to write `@Implies(Foo.class) @interface MyAnno { ... }` because then it makes at least _some_ sense to support `@MyAnno(bar = "baz")` as meaning the same as `@Foo(bar = "baz")`.

A possible disadvantage to option 3 is that it's easy to imagine automatically applying an annotation like `@NullMarked` or `@NullUnmarked` to every class in a project, only to discover that you've accidentally applied that annotation's semantics to all usages of your project's annotation in other projects! (Or similarly, imagine the "no-op" change of moving in either direction between package- or module-level `@NullMarked` and per-class `@NullMarked`.) This danger could be reduced by requiring a `@MetaAnnotated` annotation -- but not eliminated, since some annotations will legitimately have `@MetaAnnotated` to begin with.

I know that we've had some good success with option 3 for some annotations inside Google, but it scares me as a much more widely used, general-purpose approach that we'd encourage people to apply "by default" to new code and migrate existing code to use.

**Comment by kevin1e100** [comment]
I guess option 3 requires allowing JSpecify annotations to be placed on
annotation classes, while that's not needed for 1/2--there, JSpecify
annotations become attribute values of another annotation instead.

Not sure that difference is an advantage or disadvantage for option 3
though ;).

**Comment by cpovirk** [comment]
True. If nothing else, it's One More Thing to Remember when defining your own annotation to extend JSpecify (like defining `@PolyNull` when we haven't provided one). And the simplest annotations already tend to involve [a surprising amount of boilerplate](https://github.com/jspecify/jspecify/blob/1962f5ff3f072dfccd0f29df3d454f3865ca7782/src/java9/java/org/jspecify/nullness/NullMarked.java#L39-L41).

**Comment by kevin1e100** [comment]
Sorry for being vague btw, the "advantage" I had in mind is that
annotations can explicitly "opt in" to being used as ***@***.***` by
declaring the requisite ***@***.***`location in option 3, or alternatively
choose not to do so. OTOH, we may one day have annotations whose purpose
requires them placed on other annotations, and then it might be confusing
to also put ***@***.***` there.

**Comment by cpovirk** [comment]
GitHub's "email address" scrubbing ate your annotations, but I gather that your point is that Option 3 lets annotation authors choose whether to support `@Target(ANNOTATION_TYPE)` or not and thus choose whether their annotations can be implied (at least by using the Option 3 syntax, since we could theoretically support multiple syntaxes). That's a silver lining for the cloud in my previous post.

**Comment by cpovirk** [comment]
Another thing for us to consider is which syntax works best when JSpecify is not on the classpath: I would guess that at least some projects will use aliases specifically to make it easier to omit JSpecify from the classpath. For example, a code generator that begins outputting nullness annotations might want to output its own aliases so that users can continue to put only the code generator's annotation library on the classpath, rather than having to add JSpecify.

We have previously come across [a couple reasons to avoid using annotations with _enum_ elements](https://github.com/jspecify/jspecify/issues/28#issuecomment-766961413). I don't think we've yet encountered any problems with _class_ elements, nor with annotations that are annotated with other annotations.

**Comment by kevin1e100** [comment]
(fixed my comment, sorry)

**Comment by kevinb9n** [comment]
This seems solid enough to me to treat it as decided for now: make `@Implies` repeatable.
Objections?

**Comment by kevin1e100** [comment]
+1

**Comment by kevinb9n** [comment]
(still for now treating issues here as pure design issues, closing when the design question is answered)

**Comment by kevinb9n** [comment]
(#213 is about whether to support the one-implies-many use case at all; the decision here is just about how we will do that if we do it)

**Comment by kevinb9n** [comment]
This was originally also talking about questions that ended up going into #218.

**Comment by netdpb** [comment]
Note that making it repeatable means we have to have a separate, public, `@Documented` containing annotation with the same retention and targets.

As an alternative to an actually repeatable annotation, option 1 above allows multiple values and doesn't require the container annotation. And arguably it's actually good to have all the implications in one place rather than allowing something like:

```
@Implies(Foo.class)
@Retention(RUNTIME)
@Implies(Bar.class)
@Target({METHOD, CONSTRUCTOR, PACKAGE})
@Implies(Baz.class)
```

Instead you'd have to do:

```
@Implies({Foo.class, Bar.class, Baz.class})
@Retention(RUNTIME)
@Target({METHOD, CONSTRUCTOR, PACKAGE})
```

**Comment by cpovirk** [comment]
Ah, you're talking about the ["containing annotation interface"](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/annotation/Repeatable.html), like we see [in `@EnsuresNonNullIf`](https://github.com/eisop/checker-framework/blob/4baa2365b0fffbf96c8de600b7a4d8681c96c41a/checker-qual/src/main/java/org/checkerframework/checker/nullness/qual/EnsuresNonNullIf.java#L100-L112)? Good point—glad someone is actually writing the annotation source files!

That's enough to sell me on non-repeated. The only downside I haven't seen mentioned is that it would be possible to write `@Implies({})`, but I'm not too worried about that: The `{}` is enough of a hint that something is amiss, and tools could warn if that seems important to do.

(I wonder if anyone has written the doc on "how to decide whether your annotation should be `@Repeated`." I can see cases in which `@Repeated` is clearly necessary, like the `isThresholdExceeded` example in [the `@EnsuresNonNullIf` Javadoc](https://checkerframework.org/api/org/checkerframework/checker/nullness/qual/EnsuresNonNullIf.html) and the _first_ example from [this Java Tutorial page](https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html). Aside from those clear cases, I wonder if it makes sense to prefer array elements. The JDK, for what it's worth, [doesn't offer examples of `@Repeatable` annotations](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/annotation/class-use/Repeatable.html). I admit that I do recall one case in which [we chose `@Repeated`](https://github.com/google/TestParameterInjector/blob/2290212e106570f0986d0a2ae3400f08dbcdfc68/junit4/src/main/java/com/google/testing/junit/testparameterinjector/TestParameters.java#L52). But that was because each individual value could be very long, so having `@TestParameters(...) @TestParameters(...) ...` helped to separate the values.)

**Comment by netdpb** [comment]
I think the case for `@Repeated` over simple array is when there is more than one parameter, so each would have to be an array and there's no way to make it clear that they're pairs—and when the parameter is _already_ an array.

Neither applies here.

**Comment by netdpb** [comment]
Also, I would not reject an idea to provide a JSpecify validator using Error Prone or an annotation processor that specifically looks for things like `@Implies({})`—definitely disallowed constructs that don't require any potentially tool-specific processing. After all, that's the kind of thing you could see Java itself doing, just as it would disallow `@Implies` with no arguments.

**Comment by netdpb** [comment]
There are alternatives for marking pure aliases (which remain a hypothetical requirement), such as a new annotation like `@AliasFor(Something.class)` (which could itself be marked `@Implies(Implies.class)` haha no please no).

I wouldn't want to make the syntax for implies more difficult to support that. It already doesn't support implying an annnotation with parameters, and that seems like a more likely user requirement.

**Comment by netdpb** [comment]
Pure aliases are still hypothetical, and we could always handle them with a new annotation (`@AliasFor(One.class)`—which itself could be annotated with `@Implies(Implies.class)` hahaha no).

Even repeatable `@Implies` doesn't handle implying an annotation with parameters, and we're okay with that even though it's arguably a more likely requirement.

**Comment by cpovirk** [comment]
Yuck, good to know about the reflection API, thanks. (But yes, hopefully people will mostly use libraries, in which case the main people who get bit will be those who write a one-off `assertThat(myGeneratedClass).isAnnotatedWith(One.class)`.)

As for #233, are you envisioning this...?

```java
@Implies(One.class)
@Alias(Two.class)
@interface Three {}
```

If so, wouldn't the existence of `@Implies(One.class)` show that `@Three` is _not_ a pure alias for `@Two`?

Even if so, the general point stands that we _could_ need `@Implies(Foo.class, someOtherElement = ...)` someday. It just becomes hypothetical-er.

**Comment by netdpb** [comment]
Oh good point. If "pure alias" means what it sounds like, then you cannot use it for more than one thing, and you cannot mix it with other `@Implies`.

**Comment by kevinb9n** [comment]
I convinced myself it was at least a possible scenario, but, here's just how "hypothetical" we are really talking about:

```
/** Means only that x. */
@interface One {}

/** Means only that x and y. */
@interface Two {}

/** Means only that x and y. */
@Implies{One.class, Two.class}
@interface Three {}
```

Clearly this does not work as an actual strong argument for anything. It merely highlights that there do exist facts that could pertain to each implication separately.

I'm scraping the bottom of the barrel for reasons to care one way or the other, here.

One way to look at it is "repeatable annotations are new and weird and unnecessary"; another way to look at it is "they're a bona fide feature, and what are they for if not for cases like this?"

Another puny line of reasoning I almost hate to mention. It seems that whichever way we go with this, we *could* change the answer to "both ways!" in the future if it really came to it. It should make sense to allow multiple `@Implies` that each could specify multiple annotation types. That is just... gross and worth avoiding if possible.

Which way is even the "base option" in this case??

**Comment by netdpb** [comment]
I propose we leave aside the pure-alias issue (#233), about which we've said there "_might_ be eventual benefit" and that checkers could use that information in "a few hypothetical ways" that are not enumerated, and suggests that so far nobody has brought up "an actual real-world need for it".

Remaining things to think about:

* A repeatable annotation has a public and documented containing annotation, which affects static and runtime analysis.
* An array parameter makes it possible to have meaningless instances with empty array arguments.
   * Possible mitigation: A checker distributed with JSpecify that checks these kinds of self-contained constraints.
* A repeatable annotation makes it less awkward to have more complex parameters.
   * But we don't currently plan to have more complex parameters.

Do we have a sense of how often people will want one annotation to imply more than one other annotation (#213)?

**Comment by cpovirk** [comment]
Kevin mentioned elsewhere that we've been talking about this more from the implementation perspective than the user perspective. (Of course, if we make things hard enough to implement that implementers mess up, then that has significant impact on the user perspective :))

For the user perspective, I wonder if more real-world examples would be helpful. Here's an example that's at least not 100% made up on the spot:

```java
@Implies(NonNull.class)
@Implies(CanIgnoreResult.class)
@Implies(RefentiallyTransparent.class)
@Target(METHOD)
@Retention(RUNTIME)
@Documented
@interface This {}
```

```java
@Implies({NonNull.class, CanIgnoreResult.class, RefentiallyTransparent.class})
@Target(METHOD)
@Retention(RUNTIME)
@Documented
@interface This {}
```

After writing that, I'm wondering if this debate will _still_ be mostly about which syntax is subjectively "simpler...." :)

For what it's worth: To me, an array feels like "the thing you'd do unless you have a specific reason it's not good enough": `@SuppressWarnings`, `@Target`, other random things I see in Guava (`@Immutable(containerOf = ...)`, `@Footprint(exclude = ...)`, `@Param(...)`, `@VmOptions(...)`, `@CollectionFeature.Require(...)`).

I take your point that arrays could raise questions: "Does ordering matter?" "Do duplicates matter?" My guess is that most users won't think about those with either arrays or repeatable annotations, given that I'm hard pressed to think of an annotation for which array ordering does matter. But I do grant that `@MethodParameters({Object.class, int.class, int.class})` "clicks" to me in a way that `@MethodParameter(Object.class) @MethodParameter(int.class) @MethodParameter(int.class)`, so there is something to what you're saying.

**Comment by cpovirk** [comment]
Question for the group: Are `@Repeatable` annotations unusual enough that the answer Java developer would be caught by surprise at seeing one—or might not think to try writing `@Implies` more than once when that's what was required? I'm not sure I've _ever_ seen a `@Repeatable` annotation other than (a) when I've gone looking for it and (b) when we helped design one, [mentioned above](https://github.com/jspecify/jspecify/issues/215#issuecomment-1205688995).

**Comment by kevinb9n** [comment]
> For what it's worth: To me, an array feels like "the thing you'd do unless you have a specific reason it's not good enough": `@SuppressWarnings`, `@Target`, other random things I see in Guava (`@Immutable(containerOf = ...)`, `@Footprint(exclude = ...)`, `@Param(...)`, `@VmOptions(...)`, `@CollectionFeature.Require(...)`).

Not sure these constitute precedent given they all predate `@Repeatable`. That said, I have the vague sense that we would be explaining/justifying/apologizing-for the use of `@Repeatable` more than we would the array. But, neither very much. It's still a weak argument like the rest.

**Comment by kevinb9n** [comment]
I strongly suspect no one will strongly object to the array.

I've reworded my javadocs and I see that @netdpb has a PR ready to go too.

**Comment by netdpb** [comment]
**Current decision**: Because we are not planing to support annotation implication in 1.0 (#35, #307), this issue is not relevant for 1.0.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.
