### ISSUE TITLE
SpotBugs nullness analysis interaction

### ISSUE THREAD

**Issue by wmdietlGC** [jspecify/jspecify#22]
Information at:
- All `NP_` bug patterns: https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html?highlight=NP_
- https://github.com/spotbugs/spotbugs/tree/master/spotbugs/src/main/java/edu/umd/cs/findbugs/ba/npe

I didn't find a concise summary of the SpotBugs behavior...

**Comment by kevinb9n** [comment]
Kengo, just open specific issues when something comes up.
