### ISSUE TITLE
When does a type variable have unspecified nullness? [working decision: in null-unmarked code, irrespective of its type parameter's bounds]

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#238]
_Originally posted by @cpovirk in https://github.com/jspecify/jspecify/issues/89#issuecomment-1058263565_

In an ideal world, we would hold this question in our mind simultaneously with the other questions about partially annotated code, which I believe are currently:

- provide `@NonNull`? [current: YES]
- provide `@NullnessUnspecified`? [current: NO]
- provide `@NullUnmarked`? [current: YES]
- support `@NullMarked`/`@NullUnmarked` at the method level? [current: YES]

Piece of cake :)

Anyway, I believe the question is over the rule for when a type usage has unspecified nullness:

### Option A

- A type usage with `@Nullable` has specified nullness.
- A type usage in the scope of `@NullMarked` has specified nullness.
- Otherwise, it has unspecified nullness.

### Option B

Usages that are not type variables are handled as in Option A. For type variables:

- If at least one bound of the corresponding type parameter has specified nullness, then the usage has specified nullness.
- Otherwise, it has unspecified nullness.

### Or other hybrids or variants

e.g., 

- like Option B but requiring _all_ bounds to have specified nullness
- A type-variable usage has specified nullness if its type parameter is declared to definitely accept nullable type arguments or to definitely not accept nullable type arguments.
- Nullness is specified if there is either one of (a) an enclosing `@NullMarked` annotation or (b) a corresponding type-parameter declaration meeting \<whichever of the type-parameter rules above we'd pick\>.

---

Going to back strategy for deciding this: One idea that @netdpb(?) had proposed is to draft some sections of the User Guide about partially annotated code, doing so one time for each of the viable combinations we see for our rules and annotations. For example:

> If you want to annotate a class for nullness but skip a method that you're unsure about, then...

If we combine Option A with a method-level `@NullMarked`+`@NullUnmarked`, then the docs would say:

> ...put `@NullMarked` on the class and `@NullUnmarked` on the method you're unsure about. Then, for other types in the class that you want to add `null` to, annotate them with `@Nullable`.

If we combine Option B with a method-level `@NullMarked`+`@NullUnmarked`, then the docs would say:

> ...leave the file unmarked, but put `@NullMarked` on the other methods in the class. Then, for other types in the class that you want to add `null` to, annotate them with `@Nullable`, except for any type-parameter bounds that the unmarked method depends on.

If you then throw in `@NullnessUnspecified`, then:

> ...put `@NullMarked` on the class, `@NullUnmarked` on the method you're unsure about, and `@NullnessUnspecified` on any usages of class-scope type variables in that method. Then, for other types in the class that you want to add `null` to, annotate them with `@Nullable`.

etc., etc., etc. :)

**Comment by kevinb9n** [comment]
(too) much more background is in #89.

**Comment by kevinb9n** [comment]
This seems like the kind of "figure out exactly what unspecified nullness really means" work that is high priority for 1.0, am I right?

**Comment by cpovirk** [comment]
+1. I think that, no matter what features 1.0 contains, it needs to contain a decision on this issue.

**Comment by cpovirk** [comment]
The specific case I always think of when I think of this question is:

```java
@NullMarked
public interface Map<K extends @Nullable Object, V extends @Nullable Object> {
  ...
  @NullUnmarked // yuck, let's figure this out later
  default V merge(
      K key,
      V value,
      BiFunction<? super V, ? super V, ? extends V> remappingFunction);
}
```

The question is whether the various `K` and `V` types in `merge` should be treated as `K*`and `V*` or as "just `K`" and "just `V`."

The advantage to `K*` and `V*` is that erring on the side of unspecified is forgiving: Kotlin won't throw an exception if `merge` returns `null` (which it can), and tools will let `remappingFunction` return `null` (which it's supposed to be allowed to do).

The advantage to "just `K`" and "just `V`" is it gives us a way to specify those types inside `@NullUnmarked` code. That would otherwise be impossible. (But to be fair, if our rules said "just `K`" and "just `V`," then there would be no way to specify `K*` and `V*` for those types! But at least that's solvable by providing `@UnspecifiedNullness` someday.)

There are a couple other considerations that I'll ignore for now, since I think I'm already being confusing enough.

(I should also put together another example or two with different scenarios.)

**Comment by kevinb9n** [comment]
Perfect, thanks.

It's nice that we support a few "sprinkling" use cases with `@Nullable` and `@NonNull`, but I think it's fine if there's no way to sprinkle `@ParametricNullness`. Sprinkling doesn't have to get us all the way; at some point someone just has to migrate the method fully and comprehensively.

It makes sense to treat `key` and `value` as being of unspecified nullness because, when someone does eventually come around and migrate the class, we don't know whether those might be projected or in which direction. More broadly, I would also say that if `Map` were completely unannotated I'd expect the same thing: a usage like `(Map<Foo, @Nullable Bar>) map).get()` should have unspecified nullness, not nullable.

(This might have been different before we agreed to support non-null projections.)

So I would like to resolve this in favor of: it is `@NullMarked` that causes unannotated type variable usages to have parametric nullness instead of unspecified, no matter how the bounds of those variables were annotated.

**Comment by cpovirk** [comment]
> So I would like to resolve this in favor of: it is `@NullMarked` that causes unannotated type variable usages to have parametric nullness instead of unspecified, no matter how the bounds of those variables were annotated.

That strikes me as the way to go, too. I'll mark that as the working decision, but opinions either way are welcome, and we can reopen as needed.

> More broadly, I would also say that if `Map` were completely unannotated I'd expect the same thing: a usage like `((Map<Foo, @Nullable Bar>) map).get()` should have unspecified nullness, not nullable.

Let's take that broader issue to https://github.com/jspecify/jspecify/issues/250.

**Comment by netdpb** [comment]
**Current decision**:

In the folliowing case:

```
@NullMarked
interface Foo<T extends @Nullable Object> {
  @NullUnmarked
  T foo();
}
```

`Foo.foo()` returns T* (unspecified nullness), because when it is later marked it could be left parametric or projected as either nullable or not.

**Argument for changing**: None.

**Timing**: This must be decided before version 1.0 of the spec.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by kevinb9n** [comment]
Note, I believe the decision here also says that even for `interface Foo<T extends`**`@NonNull`**`Object>` that null-unmarked usages of the type variable `T` *still* have unspecified nullness. "Irrespective of the bounds". So my vote is further agreeing with that.

**Comment by netdpb** [comment]
**Decision**:

In the folliowing case:

```
@NullMarked
interface Foo<T extends @Nullable Object, U extends @NonNull Object> {
  @NullUnmarked
  T foo1();

  @NullUnmarked
  U foo2();
}
```

Both `Foo.foo1()` and `Foo.foo2()` return `T*` (unspecified nullness), because when each is later marked it could be left unprojected or projected as either nullable or not.

**Comment by netdpb** [comment]
I believe there is an additional case (not changing the decision, but clarifying):

```java
@NullUnmarked
interface Bar<T> {
  @NullMarked
  T bar();
}
```

Here, the declaration of `bar()` is null-marked, but `T`'s _bound_ has unspecified nullness. In nullness-operator terms, `bar()`'s return type is `T+NO_CHANGE`, but that means it _effectively_ has unspecified nullness because its bound could later be marked nullable or non-nullable, so therefore the return type could later be either parametric or non-nullable.

**Comment by cpovirk** [comment]
I am wary of phrases like "effectively has unspecified nullness": While it's true that it behaves that way in some cases (e.g., lenient tools will allow dereferences, but strict tools will not), it's different in other ways (e.g., even lenient tools would not allow passing `null` to a _parameter_ of type `T+NO_CHANGE` with such a bound).

I'm not opposed to making statements like that as shorthand for the user experience for a return value in this particular situation. I just want to always emphasize that a model needs to describe the type-variable usage's nullness and the type-parameter bound's nullness separately to get even the "basic" questions right—or, if it's going to try to combine them into one value, it's going to need to define probably 5-6 different nullness values :)

(It is possible that the case you mention could make for a more interesting discussion as part of #248. I would need to reread [some comments](https://github.com/jspecify/jspecify/issues/248#issuecomment-1284773824) and think for a while....)

**Comment by netdpb** [comment]
I think we're again mixing the spec's language (base+operator) with the user guide's language (base + nullness, including "parametric"). My comment about "effectively unspecified" was referring only to the user guide's language, as I think the original comment on this issue was. I did say that the augmented return type is `T+NO_CHANGE`.

I can retract my clarifying comment, since it clearly hasn't been.

**Comment by cpovirk** [comment]
Yeah, I think we agree on behavior here. Another way for me to put my point is that I think `T+NO_CHANGE` in your recent example is effectively _non-nullable_ according to the table in [the wiki model](https://github.com/jspecify/jspecify/wiki/nullness-glossary): You can dereference the result, and you can't put `null` in. Now, there are obviously some reasons that I don't like to apply that name to that type :) But if we're going to call it "effectively \<something\>," then I think we're led to "effectively non-nullable." For that reason, I try not to get into the situation of having to apply one of the wiki-model names to this sort of type in the first place :)

**Comment by netdpb** [comment]
That glossary doesn't use nullness-operator language at all. But according to that glossary, `bar()`'s return type has "unspecified-bounded nullness", not "not-nullable" nullness.

The way I read it, in one world, `T`'s bound becomes nullable, and so you won't be able to dereference the result unconditionally and you have to accept null inputs. In another world, `T`'s bound becomes non-nullable, and you will be able to dereference the result and you won't have to accept nulls.

That glossary needs updating, by the way. It's got dangling links, among other things.

My meta-point is that somewhere we should define the relationship between the spec's model and the user guide's model.

**Comment by cpovirk** [comment]
Hmm, the glossary says that "nullness" has only 4 buckets, the ones shown in the table, whose "non-null" row matches the behavior of the type in question. I think that "unspecified-bounded" refers more to the type parameter—or at least that it's an _additional_ description (separate from "nullness") that can be applied to an unannotated type-variable usage.

I agree that we need some story for what the user guide should say, potentially "here are 4 basic cases that are useful to think about, and if you care about more than that, you'll need the spec model."

**Comment by netdpb** [comment]
![image](https://github.com/jspecify/jspecify/assets/4306377/79bf947b-757f-4995-9ee2-abd070dd9868)

I suppose that could be a typo, meant to apply to type parameters. But the link for "type variable" goes nowhere.


-----

Again, I want to emphasize that this conversation doesn't imply any changes are needed to the underlying decision.

**Comment by kevinb9n** [comment]
I'm here for this discussion, and would VERY much like to see someone who isn't me propose edits to the glossary wiki.

**Comment by cpovirk** [comment]
I think that the "type variable" link is meant to go to [that definition in the glossary](https://docs.google.com/document/d/1nbTnJ0-HubLnQPKSjK5CDZyoe6Al64vdlkoJxaYX9XY/preview?resourcekey=0-ADjPZnp8LN3dRX_ptjlagw#bookmark=id.uxek2gfsybvo).

My claim that that there are two separate system in the glossary, neither of which covers all type usages:

- the 4-part "nullness" system, which doesn't address the mix of specified and unspecified nullness discussed here
- the 4-part "type-variable" system, which doesn't address non-type-variable types

My general proposal would be to avoid claiming that either set of 4 is exhaustive and instead to present them as "4 basic cases." It is possible that we could alternatively add another item or two to the "nullness" system to cover everything (i.e., add "unspecified-bounded" and maybe other entries to the "nullness" system), but I'm not sure that would be more useful that just pointing out that other edge cases exist.

**Comment by netdpb** [comment]
> I think that the "type variable" link is meant to go to [that definition in the glossary](https://docs.google.com/document/d/1nbTnJ0-HubLnQPKSjK5CDZyoe6Al64vdlkoJxaYX9XY/preview?resourcekey=0-ADjPZnp8LN3dRX_ptjlagw#bookmark=id.uxek2gfsybvo).

I've just updated that wiki page to point to the actual Java Glossary instead of to nothing.

**Comment by netdpb** [comment]
I keep saying that "parametric nullness" has no representation in the spec; `NO_CHANGE` has no representation in the user documentation; and we can and should resolve that by documenting the relationship between those two systems.
