### ISSUE TITLE
How does implication work when both aliases declare an element of the same name?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#241]
```java
@interface Original {
  boolean isGood();
}

@Implies(Original.class)
@interface Copy {
  boolean isGood();
}
```

I've gotten the impression that we'd probably like for `@Copy(isGood = true)` to behave like `@Original(isGood = true)`.

Does this behavior carry over even for the `value` element (i.e., the one that can be used as `@Copy(true)`, without stating the element name)?

(The spec will need to say something about the case in which `isGood` has a type other than `boolean` in one of the annotations.)

We'll probably also need to say something about defaults -- both normal Java annotation defaults and any "defaults" provided by the "transitive annotation pattern." For example, what does `@Copy` (with no `isGood = ...`) mean for the following...?

```java
@interface Original {
  boolean isGood() default true;
}

@Original(isGood = false)
@interface Copy {
  boolean isGood() default true;
}
```

**Comment by kevinb9n** [comment]
Let's start with TSTTCPW. No duck-typing, not even for `value`. A usage like `@Implies(Original.class)` above is "unrecognized". To be acceptable, Orignal must have no elements, or -- sliiightly more advanced version -- every element of Original must have a default value provided.

**Comment by cpovirk** [comment]
GitHub will not let me leave a reaction emoji to your proposal, so:

:+1:

**Comment by kevinb9n** [comment]
I think the "slightly more advanced version" will be required. Adding a defaulted attribute to an annotation type really shouldn't break anything.

The rest of the possible features seem like just value-adds that can be filed separately.

**Comment by kevinb9n** [comment]
This looks good as a working decision.
