### ISSUE TITLE
Define levels of compliance, the first covering just "root" declarations

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#244]
By "root" declarations, I mean only the places where non-type-use annotations can go. For other locations the tool can either recognize our annotations properly or just ignore them.

Note: it's not a backpedal, just a milestone on the way. For several tools it will take quite a while to get to full, so they should have something else to shoot for. It does deliver at least half the value at a much smaller fraction of the complexity.

Thoughts?

**Comment by cpovirk** [comment]
I think I'm coming to terms with the idea that "compliance" doesn't have to mean something anywhere near as formal and serious as the term initially suggested to me. I would still want to be careful about preemptively doing significant work on this (e.g., to go categorize all our existing samples). But I think it makes a lot of sense for us to call "root" types out as a useful intermediate step and to take action to support tool authors who are working toward it.

**Comment by kevinb9n** [comment]
This does call for forming various suites of our compliance tests. It seems worth it to me and just good organization.

**Comment by kevinb9n** [comment]
This has been captured as a requirement for the test framework (named suites) and I don't think we need to keep this issue open.
