### ISSUE TITLE
Substituting a specified-nullness type argument and (a) an unspecified-bound type variable or (b) an unspecified-nullness usage of a type variable

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#248]
"Discussion" issue: we'll need to fork off independently resolvable questions as necessary.

Here's a basic unannotated generic class:

```
@NullUnmarked
static class UnmarkedClass<T> {
  T get() { ... }
  void set(T t) { ... }
}
```

First some general background -- principles I think we apply in how we think about this case:

* There is some correct way that `UnmarkedClass` could be annotated, and we want to plan for that future.
* To the extent feasible, we'd like callers to write the same code _now_ that they will have to write in that future. (It's better if correctly annotating the class doesn't break them!) This may involve some amount of guessing at *how* exactly `UnmarkedClass` will get annotated.
* Our guiding star has been the "many-worlds" model: consider each possible way `UnmarkedClass` might get annotated like it's a parallel universe; report a finding only if that finding exists in all universes. (If it's entirely valid in *some* universe, there is a good chance that's the universe we're in, so we don't have enough basis to complain.)
* A problem with this generic class is that due to type variable projection there are 13 of these universes. I suspect it's fair to say that we probably can't future-proof against all 13 of them at once very easily. So we have to have some tolerance for the idea that sometimes -- maybe, who knows, 20% of the time? -- it won't work great and you'll be compelled to either use ugly workarounds or just go provide the stub file already.
* We won't resort to the "just go provide the stub file already" argument very often, or it would undo the benefit of having the ternary design in the first place.

Now, here's a conformance test, written using an imagined form of @netdpb's [semi-magical proposed framework](https://docs.google.com/document/d/1U7DHHFz49nrByyUEhLSVUYrxblfo2dLtfO6XETcYBGs/edit?resourcekey=0-ByeD2fAlv3JqErgUissoFQ#heading=h.3eq51y2skfxb), with some pieces missing:

```
@NullUnmarked
static class UnmarkedClass<T> { // just repeating this from up above
  T get() { ... }
  void set(T t) { ... }
}

@NullMarked
void testUnmarkedClassOfNonNullFoo(UnmarkedClass<Foo> ofNonNullFoo) {
  assertThat(ofNonNullFoo).hasType("UnmarkedClass!<Foo!>");
  assertThat(ofNonNullFoo.get()).hasType("__?1?__");
  assertThat(ofNonNullFoo).set(accepts("__?2?__"));
}
```

Observations:

* We have a type argument with specified nullness, whose bound has unspecified nullness.
* We still want `UC<Foo>` in this usage code to mean `UC<@NonNull Foo>` as it generally does, and as it surely will when `UC` is annotated.
* Since this is always a legal parameterization of `UC` no matter how it's later annotated, it offers no "prediction" or "vote of confidence" by the user of which way that annotation is going to go.

Questions:

* What type should be at `__?1?__`?
* What type should be at `__?2?__`?

Now here's the corresponding test for a nullable type argument:

```
@NullMarked
void testUnmarkedClassOfNullableFoo(UnmarkedClass<@Nullable Foo> ofNullableFoo) {
  assertThat(ofNullableFoo).hasType("UnmarkedClass!<Foo?>");
  assertThat(ofNullableFoo.get()).hasType("__?3?__");
  assertThat(ofNullableFoo).set(accepts("__?4?__"));
}
```

Observations:

* This time, the user is strongly suggesting that `UC` is probably going to be annotated with a `@Nullable` bound; they are opting for their code to get broken otherwise.

Questions:

* What type should be at `__?3?__`?
* What type should be at `__?4?__`?

Some of these four questions probably correspond to existing issues.

One set of answers is that they are all `Foo*`, a.k.a. `Foo` with unspecified nullness.

Another is that the user is "asking" for more restriction / protection from themselves, in a sense, so 2 should be `Foo!` (non-null), and 3 should be `Foo?` (nullable). But that they should only be able to adjust in this restrictive direction, not make 1 and 4 more permissive.

There are of course other possibilities.

**Comment by netdpb** [comment]
I think the user, and any given tool, should be free to interpret `__?1?__`, `__?2?__`, `__?3?__`, and `__?4?__` [^1] in ways that make sense for them even if JSpecify says they're all `Foo*`. Isn't that what "unspecified nullness" is meant to allow? I would hesitate to have JSpecify attempt to guess what users are asking for at callsites. I see JSpecify as more focused on allowing API authors to indicate what they intend.

[^1]: Wow, these are hard to type!

**Comment by netdpb** [comment]
What do you mean by "well determined"?

**Comment by kevinb9n** [comment]
I _think_ this amounts to:

* You can write distinct types `UC!<Foo!>` and `UC!<Foo?>`
* Those types are identical as far as JSpecify is concerned
* But we let you write those different types just so that there is an extra bit of information along for the ride, for your tool to decide on its own whether it wants to use in some way. Of course, if it wants to use it, it will have to keep track of it in some other way besides as part of the JSpecify-recognized type.

Did you consider the merits of the second alternative I mentioned?: that the answers to 1/2/3/4 are `Foo*/Foo!/Foo?/Foo*`, or more understandably:

```
@NullMarked
void test(UnmarkedClass<Foo> ofNonNullFoo, UnmarkedClass<@Nullable Foo> ofNullableFoo) {
  assertThat(ofNonNullFoo.get()).hasType("Foo*"); // 1
  assertThat(ofNonNullFoo).set(accepts("Foo!")); // 2
  assertThat(ofNullableFoo.get()).hasType("Foo?"); // 3
  assertThat(ofNullableFoo).set(accepts("Foo*")); // 4
}
```

The idea here is: it probably makes sense to treat these distinct types as if they mean something distinct. It's problematic to interpret them as making the types more permissive (as 1=Foo!, 2=Foo? would do). But I think it makes sense to interpret them as restrictive. For example, if I write `@Nullable` there, it means I think the type parameter bound probably is going to be annotated as `@Nullable`, and so I would _want_ the result of calling `get()` to be nullable and stop me from doing something non-null-requiring with it.

**Comment by kevinb9n** [comment]
Okay, I propose resolving in favor of `Foo*` in all 4 cases, as David is also arguing.

First, from pure principle, because <T> is null-unmarked, we are to consider the parallel universes where it gets annotated in either direction, _and_ further the parallel universes where each of its usages get projected in either direction. Because the process of null-marking the class will occasionally involve such projection. That makes a clear argument for the proposed resolution.

It's also just far from clear that this option would cause any real trouble. Any thoughts out there?

**Comment by cpovirk** [comment]
If tools were actually to treat the types as unspecified, I would be highly confident that that would cause real trouble: Code that uses `Future<String?>`, `Maybe<String?>`, etc. would unaware that the results extracted from those kinds of objects could be null.

Yes, the real solution is to get those types annotated. But when we're asking "Will this cause problems for users of unannotated code?" the answer is "most certainly yes."

**Comment by kevinb9n** [comment]
I was unaware the kotlin is currently answering this issue's question (1/2/3/4) with "unspec/unspec/nullable/nullable".

That treatment would be consistent with the following imagined principles:

1. It would be very bad to need 2 substitution formulas, one for in-types and one for out-types. That dictates that 1 and 2 should have the same answer, as should 3 and 4.
2. Though, as mentioned, `UnmarkedClass` could be future-annotated in 13 different ways (13 "universes"), we can downgrade the 3 cases that include *non-null projection* because non-null projection Is And Should Be Rare. That makes the answer to 3+4 "nullable" but leaves 1+2 "unspec".
3. Considering that non-null projection *could* still happen, that uncertainty for `UnmarkedClass<@Nullable Foo>` manifests in these ways:
(a) it's restrictive for out-types (i.e., using that out-type in some bigger expression might fail when it logically shouldn't). Probably that's because said failure (at compile-time) is easily remedied with `!!`.
(b) yet it's permissive for in-types (i.e., lets you pass nullable, though a real runtime `null` *might* cause an NPE). And this is forced, because if restrictive there would be no remedy -- no way to pass `null` in anyway (because to Kotlin these findings are unsuppressable errors).

**Comment by kevinb9n** [comment]
#250 has more discussion of the choice between */*/?/? and */*/*/*.

**Comment by kevinb9n** [comment]
Good lord, are these issues themselves just dups of [#76](76)?

We've been at this too long.

**Comment by cpovirk** [comment]
I believe kevinb9n is going to be looking at writing up a summary of this. On the summarizing front, I wanted to note that I think the issue title is wrong :)

I think the important bit is not "unspecified-bounded type variable" but rather "type-variable usage in non-`@NullMarked` code." So I think that our discussion also includes a case like this (which uses an "identity parameterization!")...

```java
@NullUnmarked
class MyList<E extends @Nullable Object> {
  E[] elements;

  public int hashCode() {
    int result = 0;
    for (E e : elements) {
      result += 31*result + e.hashCode(); // error or not?
    }
    return result;
  }
}
```

...but excludes a case like this...

```java
@NullUnmarked
class Supplier<E> {
  @NullMarked
  E get();
}

Supplier<@Nullable String> s = ...;
s.get().hashCode(); // definitely an error
```

**Comment by cpovirk** [comment]
Nooooo wait it gets worse nooooo

It _would_ make sense for the bound of the type parameter to enter into it _in addition to_ the null-markedness of the type-variable usage: In my second example, if the "intended" bound for the `E` in `Supplier` is `<E extends @NonNull Object>`, then the type of `s.get()` is going to be `@NonNull String`, despite the `@Nullable String` type argument. (Digression: Come to think of it, that might be different from how Kotlin behaves? I could check if it matters to anyone.) Thus, we'd expect for `s.get()` to _likewise_ have unspecified nullness.

So I think we're talking about any case that involves at least one of:
- an unspecified-bounded type variable
- a type-variable usage in non-`@NullMarked` code

**Comment by cpovirk** [comment]
...and I think that "`*/*/?/?` vs. `*/*/*/*`" is what we're faced with for only the second of those bullets\[*\]. For the pure first case (~where only the usage is in `@NullMarked` code), I think we're faced with "`!/!/?/?` vs. `!/!/*/*`."

The good news is that I think there's still only one "decision" to make: We have to decide whether [the principles above](https://github.com/jspecify/jspecify/issues/248#issuecomment-1201441386) should put the `@NonNull` case on equal footing with the `@Nullable` case or not. Then we get either...

- `!/!/?/?` for the first bullet and `*/*/?/?` for the second or...
- `!/!/*/*` for the first bullet and `*/*/*/*` for the second.

I hope I got that right....

[*] including the case in which _both_ bullets apply

**Comment by cpovirk** [comment]
kevinb9n requested a while back that I weigh in on any 0.3-targeted issues for which one decision would be a lot easier to implement in the reference checker than another. That way, we could consider making the working decision that lets us get 0.3 into the hands of actual users faster, at which point we could reconsider under less time pressure and with more user feedback.

This is one of those issues: Our current implementation of substitution is pretty hacky, so I'm not sure how easy it would be to change. Thus, it's simplest _at the moment_ to keep the reference checker on its current behavior, which is... well, it's getting kind of hard to describe the options at this point :( But I think the following example is enough to distinguish it from the others, and in fact _maybe_ the `ofNullable` cases alone would be enough?

```java
@NullUnmarked
interface FullyUnmarked<T> {
  T get();
}

ofNonNull.get()  // Object*
ofNullable.get() // Object?

////

@NullUnmarked
interface UnmarkedTypeParameterMarkedMethod<T> {
  @NullMarked
  T get();
}

ofNonNull.get()  // Object!
ofNullable.get() // Object?

////

@NullMarked
interface MarkedTypeParameterUnmarkedMethod<T extends @Nullable Object> {
  @NullUnmarked
  T get();
}

ofNonNull.get()  // Object*
ofNullable.get() // Object?
```

**Comment by kevinb9n** [comment]
Thank you! At the current juncture that has to be enough to call this working-decided.

As of now, when there's a decision that we know need to be shored up before 1.0, I'm going to keep it open and retargeted for 1.0.

**Comment by kevinb9n** [comment]
We should try to understand the relationship between this, #76, #250, and #292 ... combined with my statement that "we will need to shore this up before 1.0", I'm removing "[working decision]" from the title.

**Comment by cpovirk** [comment]
I had promised @netdpb recently that I'll return to this. (There have been some relevant developments since we last discussed it.) I still intend to do that.

I think that we can still distinguish between "jar 1.0" and "spec 1.0," with this necessary only for "spec 1.0." But even if you agree on that, I still think that we should have a better _understanding_ of where we stand with this issue for "jar 1.0": It will affect what kind of statement we can make about what sorts of non-javac-compile-breaking changes we might still make to our annotations' semantics in the future.

**Comment by cpovirk** [comment]
@netdpb and I ended up talking about this on Friday, so I'll give a "quick" "summary" here of why I've softened on this:

- Kotlin historically implemented `*/*/?/?`. Granted, they could continue to do that even if JSpecify were to say `*/*/*/*`: A tool is entitled to add its own rules on top of ours. But the Kotlin behavior provided some evidence that `*/*/?/?` could be useful and that it could be implemented (though I don't think we had much doubt about the latter). Additionally, it suggested that the Kotlin people had chosen that behavior in a situation similar to ours.
   - But now Kotlin is probably going to change to `*/*/*/*` (though [not until at least 2.1](https://youtrack.jetbrains.com/issue/KT-59138/Change-Java-type-parameter-based-types-default-representation-in-Kotlin#focus=Comments-27-9466402.0-0), and I don't know how settled it is). (This change seems to have been prompted by the addition of `T & Any` to Kotlin a while back. But I think the relationship between the two Kotlin changes is more complex than it might sound. Notably, the type `T & Any` had already been possible to produce when reading _Java_ code, which is of course the code from which platform types arise.) It would be relatively more sad for Kotlin to implement a behavior that un-specifies some nullness that JSpecify says is specified, essentially _ignoring_ our rules.
- We will be getting back to our new conformance tests in the future. When we do, it will present a natural opportunity to update our tests' expected results for _any_ change in behavior but obviously specifically for this one.
- As we look to make our reference checker somewhat less hacky and fragile, I suspect that we'll find our job easier if we implement `*/*/*/*`, which I think is more similar to the upstream behavior.

**Comment by cpovirk** [comment]
And sorry, I also forgot:

- One of my historical concerns about `*/*/*/*` had been that [users would write (e.g.) "`Future<String?>`" and then be surprised that Kotlin would let them dereference the result of `future.get()`](https://github.com/jspecify/jspecify/issues/248#issuecomment-1201368531). And the same problem could exist with Java checkers\[*\]. But Google and NullAway have both been doing work recently to make it easier for tools see annotations on JDK APIs and other unannotated APIs. (This builds on earlier work by numerous groups.) While we are still very far from "solving" that problem, we at least have more evidence that it _could_ be solved, including in more efficient and general ways that we'd feared. (And the Kotlin developers, as they discuss their plans for 2.1, may make their own accommodations for JDK types, as they already do in some cases.)

\[*\]. Yes, again, all tool authors can choose to go their own way. But when our spec lays out a particular set of rules, tools are more likely to implement that set than to implement some other set.

**Comment by cpovirk** [comment]
(One of my long-shot hopes had been that we'd have time before 1.0 to expand what the specification covers and perhaps do more from-scratch implementation work. (For example, we haven't said anything much of anything about type inference, nor have we looked into all the concepts/rules that we'd need for dataflow.) If we had, then it might have provided us more information about which approaches are easiest to implement, and that could have provided additional arguments one way or the other on this issue.)

**Comment by cpovirk** [comment]
One other reason that I've softened on this:

- Compared to [5 years ago](https://github.com/jspecify/jspecify/issues/4#issuecomment-532312511), we've seen more real-world use cases for `@NonNull`—and thus more reason for unspecified-nullness type-variable usages to "account" for that. To be precise, `git grep '^[^*/]*@NonNull'` now turns up 25 lines in 6 files in the JDK (under `src/java.base/share/classes/java*`) and 98 lines in 15 files in Guava (under `guava`).

I'll edit this into my earlier post.

**Comment by netdpb** [comment]
I remain convinced that the simplest specification is best.

* Unprojected type variable usage in null-unmarked scope: unspecified. `@NullUnmarked T foo();` returns `T*`.
* Projected type variable usage in null-unmarked scope: as projected. `@NullUnmarked @Nullable T bar();` returns `T?`.

The case I hadn't considered before is an unprojected type variable use in null-unmarked scope, where the type parameter's bound is unspecified. I think that has a simple answer as well: parametric.

* Unprojected type variable usage in null-marked scope, where the type parameter's upper bound is unspecified: no-change. `@NullUnmarked interface Qux<T> { @NullMarked T qux(); }`: `qux()` returns `T`.

("No-change" is one of the [nullness operators](https://jspecify.dev/docs/spec#nullness-operator) in the spec. It's equivalent to parametric if the type parameter bound is nullable, or to non-null if it's non-null.)

The rationale for that is that we don't know whether `<T>` will eventually have a nullable or non-null bound, so those are the two worlds. (We don't have to consider a world in which `qux()`'s return type will be projected, since it's null-marked.) In both worlds, no-change will be correct.

All the arguments for anything stronger than this proposal seem to come from a (valid) desire for tools to report the least surprising errors to their users for unmarked code. But tools are free to report whatever makes the most sense to their users, especially in these unspecified contexts. The specification can and should declare that types have unspecified nullness in order to let tools do that.

**Comment by cpovirk** [comment]
(I agree with all that but think that this issue is getting at something subtler (on which I think we _also_ now agree, conveniently). We can talk elsewhere, as you've suggested.)

**Comment by kevinb9n** [comment]
I also agree with all that. 

Noting that the third case you added is mentioned here and also in #238 and I agree with it in both places.

**Comment by kevinb9n** [comment]
I've just noticed that in the current state of github.com/jspecify/jdk, and the jspecify-annotated Guava branch, `@NonNull` is almost _never_ used except to coerce a type argument to meet the non-null bound (mainly of Class and Optional). There are also a scant few examples used with `? super`, like in Map.merge().

This, to me, makes the argument for '*/*/?/?' in https://github.com/jspecify/jspecify/issues/248#issuecomment-1201441386 seem really, really reasonable.

**Comment by cpovirk** [comment]
Noooo, I had finally given in! :)

In the spirit of [my earlier mega-post on why I'd changed my mind and gotten on board with `*/*/*/*`](https://github.com/jspecify/jspecify/issues/248#issuecomment-2008031089), here are a couple things that have changed since _then_ that do argue in favor of `*/*/?/?`:

- We might find ourselves with a Java language feature that can't express parametric nullness for type parameters (just "nullable," "non-null," and "unspecified"). We'd be back to having it be sad that `Future<String?>.get()` produces a `String*` instead of a `String?`, except there would be no way to solve it by "just" annotating `Future` yet.
   - Caveat: If users continue using a JSpecify-based checker, they could still get parametric-nullness behavior; it's just that the Java _language_ is less likely to offer that in any initial version of nullness-augmented types.
- We might find ourselves with a Java language feature that produces only warnings. This at least means that weirdness like that involving `Class` and `Optional` is less likely to outright _break_ builds.
   - Caveat: We can expect some scrupulous users to promote the warnings to errors.

**Comment by netdpb** [comment]
I would be very surprised if the eventual Java language feature didn't allow type variable usage's nullness to vary with the type argument. And I'd really rather not make our spec less expressive just in case of that outcome.

**Comment by cpovirk** [comment]
I think that we all expect for it to eventually do so. My new point here was meant to be only that it seems likely that there will be a transition period during which it would not _yet_ do so, even after it has gained some support straight-up nullable and non-null types.

I've edited my post to actually say that.

I still don't think that needs to swing us back to `*/*/?/?`. Of course, if the possible future JDK feature were to be designed to use `*/*/?/?`, then that would make me wish we'd gone that way.... But at this point, I hope that we can get the JDK and JSpecify behavior to match by getting them both to `*/*/*/*` :)

**Comment by cpovirk** [comment]
The four people who expressed interest in further discussion ended up converging on what we've been calling "`*/*/*/*`" here (and called just "`String*`" in [the doc](https://docs.google.com/document/d/1NVA6Jj1_JKCsxi5oyM7YL40u_FH5F3NZvnCVEQA2W5s/edit?resourcekey=0-PDrdbiROaqF3C-1nkKW1fg)):

```java
@NullUnmarked
class Unmarked<T> {
  T get();
}

Unmarked<@Nullable String> unmarked = ...;
return unmarked.get(); // returns `String*` (chosen over an alternative of returning `String?`)
```

\[edit: And years later, we hit a fun example of where `*/*/*/*` would have been a bit friendlier than the current Kotlin behavior in internal issue 526744711.\]
