### ISSUE TITLE
`List<?>` in a null-*unmarked* context: Specified to include lists with null elements, or no specification?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#249]
In #83, we decided that `List<?>`, in a null-*marked* context, behaves like `List<? extends @Nullable Object>`.

What does it mean *outside* a null-marked context? The two obvious options are:
- `List<? extends @Nullable Object>`
- `List<? extends @UnspecifedNullness Object>`

# Considerations

## Conceptualizing `<?>` as "unbounded"

One reason that we felt good about our decision in #83 was that we could say the following: Yes, `@NullMarked` generally makes types "non-null by default." However, that has no bearing on `<?>` because _it has no bound_.

By that logic, we'd want it to still have no bound in a null-*unmarked* context. That is, we'd want it to still behave like `List<? extends @Nullable Object>`. If not, we'd have to address this with another entry in our list of exceptions to "non-null by default"—though perhaps we need to speak to it in _some_ way no matter which option we pick.

## Conceptualizing unannotated code as expressing no nullness information

Under that model, `List<? extends @UnspecifedNullness Object>` may make more sense. But as discussed in the previous section, we have a justification for how `List<? extends @Nullable Object>` can make sense, too.

## Making unannotated code more likely to pass lenient nullness checking

If an unannotated method declares a parameter of `List<?>` and then dereferences elements of that list, it would likely fail lenient nullness checking if we considered it to be `List<? extends @Nullable Object>` and pass if we considered it to be `List<? extends @UnspecifedNullness Object>`.

This argues for `List<? extends @UnspecifedNullness Object>` under the theory that missing nullness information shouldn't cause nullness errors in lenient checking.

Alternatively, it argues for `List<? extends @Nullable Object>` under the theory that that is almost (but [not](https://github.com/google/guava/blob/4cf437c75062d98fcb1172dc3b0a3d309650aa37/guava/src/com/google/common/cache/AbstractCache.java#L112) [quite](https://github.com/google/guava/blob/4cf437c75062d98fcb1172dc3b0a3d309650aa37/guava/src/com/google/common/util/concurrent/Striped.java#L142)) always what the author wants. Thus, we might prefer to have code like the two linked examples _not_ pass nullness checking for the greater good of catching problems in _other_ code. In general, we don't place a lot of weight on what's most common, but it's worth noting that the ratio here is [20:1 in famously null-hostile Guava](https://docs.google.com/document/d/1hr8Ld9cRMFksvA_Uzh61o4bdiVMXl084AR5QAkokEn0/edit#heading=h.yy7g3f7mofvm) (so probably higher in normal code). And we should always remember that unannotated code often fails nullness checking for reasons unrelated to this particular issue—though perhaps only "because of implementation code," not "because of APIs" like we'd be seeing here?

## Blocking implementations of an interface from defining the right signature

Suppose that a type `Super` defines the method `getAll(List<?> l)` and a user tries to define a subtype `Sub`. Tools are likely to encourage or even force the nullness of `Sub.getAll` to match the supertype.

This argues for `List<? extends @UnspecifedNullness Object>`: That way, lenient tools are more likely to allow `Sub` to declare the type as `getAll(List<? extends @NonNull Object>)` if appropriate.

(In these previous two sections, we're talking only about (a) the unannotated code itself and (b) annotated (or Kotlin) subclasses of that code: When it comes to _callers_ of the unannotated code, which is [what we care most about](https://docs.google.com/document/d/1d5NgP4Pjk_ahkISpRa3nFb1FzPz9yS9luByiBj6qCsk/edit#bookmark=id.x9oqfkq3ga1t), the two options are basically equivalent.)

## Consistency with current Kotlin behavior

I just confirmed that Kotlin implements the `List<? extends @UnspecifedNullness Object>` behavior.

**Comment by kevinb9n** [comment]
Well, this came out so clearly on one side that a person who didn't know you might think it was passive-aggressive. :-)

By all practical rationales the bound should be unspec. You've uncovered a weakness of the "? means no bound" _explanation_, is all, I think.

But I think it's fine if some mental models work only for null-marked code and fall apart when unspec enters the picture. Because I think unspec will have its own guiding star. (I don't know exactly what it is, but it's _something_ like many-worlds.)

If `List<?>` appears in null-unmarked code, then one day when someone null-marks it they're either going to leave that alone or change it to `List<? extends Object>`, and we don't know which. So for now it is the quantum superposition of those two states. Yes?

**Comment by netdpb** [comment]
**Current decision**: In null-unmarked code, the wildcard in `Foo<?>` has essentially a null-unspecified upper bound.

**Argument for changing**: If we want to consider plain wildcards as having _no bound_, then even in null-unmarked code they should have no bound, which means they should be interpreted as if they could also capture nullable types. But this is not a strong case; there are benefits to leaving the effective nullness unspecified.

**Timing**: This must be decided before version 1.0 of the jar.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: In null-unmarked code, the wildcard in `Foo<?>` has essentially a null-unspecified upper bound.
