### ISSUE TITLE
Revisit behavior of substituting a @Nullable type argument into an null-unmarked class

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#250]
In short:

```java
@NullUnmarked
interface Lib<T> {
  T get();
}

class Caller {
  void go(Lib<@Nullable String> l) {
    l.get().length(); // <---
  }
}
```

So far, we've said that `l.get()` has the type `String?` ([1](https://docs.google.com/document/d/15NND5nBxMkZ-Us6wz3Pfbt4ODIaWaJ6JDs4w6h9kUaY/edit#heading=h.xo15qzmw82i3), [2](https://jspecify.dev/spec#substitution)). As a result, tools are likely to issue an error for a possible null dereference on the call to `length()`.

This is in contrast to what happens with a `Lib<@NonNull String>` or `Lib<[unspec] String>`: In both of those cases, `l.get()` has the type `String*`. Tools are likely to allow users to dereference that.

There has been increasing discussion lately that `l.get()` should have the type `String*` for the `Lib<@Nullable String>` case, too.

The reason for considering the change is this:

First, consider a world without `@NonNull`. No matter how any of the types in `Lib` are ultimately annotated, the result of substituting `@Nullable String` into the return type of `get()` is going to produce a `String?`. Thus, we want the type to be `String?`, even in the absence of nullness information. Note also that this is Kotlin's long-standing behavior.

But: We no longer live in that world—neither in JSpecify Java (since we'll be offering `@NonNull`) nor in Kotlin (which added definitely non-null types: `T & Any`). Now it's possible to annotate `get()` as `@NonNull T get()`. And _then_ the resulting type is `String!!` rather than `String?`, even for a type argument of `@Nullable String`. Since the result of the substitution now depends on exactly how `Lib` is ultimately annotated, that suggests that we should leave the result type unspecified—that is, as `String*`.

My personal feeling is that `String?` is still the way to go: It's going to be correct quite possibly 99% of the time, since `@NonNull T` is expected to be rare. Plus, as noted above, it matches the Kotlin behavior. (Perhaps Kotlin would be willing to change its behavior, though, especially after adding definitely non-null types.)

Yes, the fallout is that people will occasionally see errors where they aren't helpful. But given how often this happens already (with calls to methods like `Map.get` that humans often know will never return `null`), I don't think these rare occurrences will make users' experience noticeably worse. And by contrast, users are very likely to benefit from having tools know that `Foo<@Nullable Bar>` will probably return `null` from its methods, even when the tools know nothing of `Foo`. 

But I admit this is not a tidy, logical argument. I further admit that, if our rules that leave the resulting type's nullness as unspecified, that gives tools the freedom to treat it as nullable if they prefer. In contrast, if we say that it's nullable, they may feel reservations about treating it as unspecified. Then again, we give tools freedom to do a lot of things no matter what, so maybe nothing we decide here is going to change what they choose to do :)

**Comment by cpovirk** [comment]
I neglected to mention that our implementation work on the reference checker looks like it _might_ have been easier if we'd chosen the `String*` behavior. However, I'd need to look into this more to say anything with confidence.

**Comment by netdpb** [comment]
I think it's impossible for a machine to tell whether the result of calling `get()` is nullable or not. You, a human, are using the semantics of the names "supplier" and "get" to infer that the result is likely nullable.

What about

```
@NullUnmarked
interface Sklazzitch<T> {
  T bleccch();
}
```

or even
```
@NullUnmarked
interface Filters<T> {
  T getOrThrowIfNull();
}
```

In these examples, I think it's much better to treat the return value when `T` is `String?` as `String*`.

**Comment by cpovirk** [comment]
Sorry, I didn't mean to pick a name that biased people. I've edited my post to use a generic class name `Lib`.

I still maintain that, among all the `Sklazzitch<@Nullable String>.bleccch()` and `Filters<@Nullable String>.getOrThrowIfNull()` calls in the world, on the order of 99% of them are going to return a nullable result. I say that based on the annotations we have for most of the JDK, the annotations we have for Guava, and the annotations we have for the other Google code we've covered.

The only big exception I can recall is the `Flag.getNonNull` method you're familiar with. (I would add that that's a method that we _might_ choose not to include if we were writing the class from scratch in a null-checked world. But of course JSpecify should still have a story for such methods.)

Maybe you can also include [methods like `FluentIterable.getFirst`](https://github.com/jspecify/jspecify/issues/86#issuecomment-1030450562) in that.

But when we're talking about `getNonNull` and `getFirst`, we're talking about _methods that throw a `RuntimeException` if the underlying value is null_. So I'm not even sure it's a bad thing for nullness checkers to warn about about usages of them with `@Nullable` type arguments!

**Comment by netdpb** [comment]
I'm concerned about our spec recommending a narrowing of the nullness of an expression type from unspecified based on heuristics. That seems like acceptable behavior for a tool to have in the presence of unspecified-nullness types, but not something the specification should mandate.

**Comment by kevinb9n** [comment]
Is this issue different from #248 (aside from focusing only on its cases 3+4)?

**Comment by cpovirk** [comment]
Ah, so *that's* why I thought there had been more GitHub discussion of this :)

I, uh, mean, of course I knew that, and this was just intended to be one of the "independently resolvable questions." Yeah, that :)

(Thanks.)

**Comment by kevinb9n** [comment]
I guess I'm calling this one the dup, then.
