### ISSUE TITLE
Discuss jspecify.dev makeover

### ISSUE THREAD

**Issue by artempyanykh** [jspecify/jspecify#253]
We touched on this a couple months ago. Now that we're planning to go somewhat more public and publish more content, I thought it'd be helpful to talk about a makeover for the site again.

I spent a few hours this morning in Figma playing with fonts and icons and then a couple more to set things up in [docusaurus](https://docusaurus.io/). Below is the screenshot of the landing page which is a combination of 
1. docusaurus' template and
2. my amateurish attempt at graphics design (I'm not a designer by any stretch; consider this as just my attempt to make the site standout a little bit; not as a definitive take on branding 🙂).

I guess, overall **I have a positive impression from docusaurus**: the template feels more modern than what we have now and the toolchain for working with the site is quite good.

I didn't try to port any content from the current site. **I can take a stab at it unless somebody feels strongly against** going in this direction. Let me know what you think.

Light:

<img width="1112" alt="Screenshot 2022-08-03 at 15 18 10" src="https://user-images.githubusercontent.com/2338443/182636846-1225d1ee-6026-48ff-b688-1abfb0a9dde5.png">

Dark:

<img width="1014" alt="Screenshot 2022-08-03 at 16 09 02" src="https://user-images.githubusercontent.com/2338443/182643313-7cea8552-87da-4c25-acd5-6b6c8e21dbb5.png">

**Comment by netdpb** [comment]
I don't know anything about docusaurus, but explore away! As long as it
lets us write docs in markdown, it sounds good to me.

Thanks!

**Comment by kevinb9n** [comment]
I appreciate your taking this on. And I like the logo. :-)

Are we stepping on each other's toes if I'm changing the landing page .md much?

**Comment by artempyanykh** [comment]
Thanks @kevinb9n! 🙂 I don't think we're stepping on each other's toes. I'll port the 2 other pages (user guide, the spec) first and then share intermediate results/ping you about the landing page.

**Comment by cpovirk** [comment]
I, too, like the logo, as well as the similar hints at the concept of "annotations" in the... workmark, I guess is the term? :) We're going to need some T-shirts when 1.0 arrives!

@KengoTODA has done a good bit of the word on the existing setup and may make a good reviewer. But I don't want to sign anyone else up for doing work :)

**Comment by artempyanykh** [comment]
I've just submitted #257 which updates the website. Let's discuss next steps on the PR.
