### ISSUE TITLE
Is a tool ever compelled to calculate a type as unspec, or is always free to assign a specified nullness as it sees fit?

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#254]
Our tests will check what augmented-types various type usages have, various expressions produce, and various expression-sinks (whatever things enclose an expression) want to consume.

Should we ever test that a particular type comes out as `Foo*`? Or is a tool always within its rights to decide a nullness for anything that is JSpecify-unspecified?

We have long stated a central goal as "make sure API owners can successfully/correctly annotate independently of tool choice". If it's fair to assume that process requires correctly annotating any types *used* in the API, then ... maybe we have no strong interest in whatever happens to anything left unspecified?

**Comment by netdpb** [comment]
I say yes.

Tools are free to decide to further specify that type for their own purposes, but we should check their understanding that JSpecify does not.

**Comment by cpovirk** [comment]
I have a question about the question :) I think we're talking about something like this:

```java
class Foo {
  // jspecify:type:bar=List*<T?>
  List<@Nullable T> bar();
}
```

I _suspect_ that there's no controversy that _that's what the test should say_: It should say that the type is `List*<T?>` from JSpecify's perspective.

The possible controversy, I think, is over what it means to "pass" that test: Does a tool have to internally spit out the type `List*<T?>`? Or is it enough for it to spit out `List!<T?>` or `List?<T?>`, both of which are compatible with JSpecify's lack of specification for the list itself?

Does that sound right?

**Comment by netdpb** [comment]
Thank you for expressing the question in the form of a test case!

My 2¢ is that the tool should agree that the type is `List*<T?>`. It is then free to tell its users whatever it wants about whether calls to that method are in error, or whatever.

**Comment by kevinb9n** [comment]
That'll work for now.

**Comment by netdpb** [comment]
**Current decision**: Conformance tests will require conformant tools to express that certain type usages are in fact nullness-unspecified. They do not have to report that to their user; they can go on to treat that type component however leniently they want.

**Argument for changing**: No strong case.

**Timing**: This must be decided before version 1.0 of the spec.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: Conformance tests will require conformant tools to express that certain type usages are in fact nullness-unspecified. They do not have to report that to their user; they can go on to treat that type component however leniently they want.
