### ISSUE TITLE
How to address `@Foo(bar = XYZ) @ImpliesFoo`

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#259]
We've discussed some similar but not identical cases:

- In [#216](https://github.com/jspecify/jspecify/issues/216), we established that `@Foo @SomethingThatImpliesNotFoo` is Bad and that the result is that both `@Foo` and the implicit `@NotFoo` are unrecognized.
- And while I don't have a specific issue to cite for this offhand, I'm confident that `@Foo @ImpliesFoo` is Fine, just redundant. (slightly related: [#233](https://github.com/jspecify/jspecify/issues/233) might help tools decide whether to suggest replacing it with `@Foo` or with `@ImpliesFoo`.)

So now, what about the following...?

```java
@interface Foo {
  boolean bar() default false;
}

@Implies(Foo.class)
@interface SomethingThatImpliesFooWithBarEqualsFalse {}

@Foo(bar = true)
@SomethingThatImpliesFooWithBarEqualsFalse
class User {}
```

`User` doesn't imply two identical `@Foo` annotations, but neither does it imply a clear conflict of `@Foo @NotFoo`. Arguably, the right answer to this question would depend on the semantics of `bar`. For example:

```java
@interface Nullable {
  boolean polyNull() default false;
}
```

If some type is annotated with both some annotation that implies `@Nullable` and some annotation that implies `@Nullable(polyNull = true)`, that probably just means that the first annotation was written before `polyNull` became available.

But in another example:

```java
@interface Tainted {
  boolean tainted() default true;
}
```

Then a type that is annotated to imply both `@Tainted` and `@Tainted(false)` is an outright contradiction. (Of course, part of the story here is that `@Tainted(false)` is probably a worse API than `@Untainted` :))

I could imagine yet another possibility, which is that an annotation might declare an array element with a `default` value (similar to https://github.com/jspecify/jspecify/issues/215#issuecomment-1208525109 except for the `default` value). Then a type could be annotated with both that annotation (with an explicit array of values) and an annotation that implies it (with its default array of values). Would we then merge the two arrays, presumably removing duplicates... and somehow choosing which annotation's values come first in order?

Despite the possibility that different annotations would want different things, it seems likely that we should specify a single answer so that tools don't have to program in different handling for each annotation—and we don't need to define a meta-annotation to configure it.

The easy way out is always "If an annotation is implied more than once with any difference in any of its values among them, then all annotations are unrecognized." (I think the only question that would leave is whether a change in array order is a "difference." I'd say probably?) But that's kind of sad in the `@Nullable @Nullable(polyNull = true)` case, since a clearly nullable type could become non-null. I'm not sure if we can get away with avoiding defining `@PolyNull` that particular way or with telling people not to imply `@Nullable` more than once if one of them might someday be `@PolyNull`... but hopefully?

(This would all become more likely to be a practical problem if we provided a way for one annotation to imply an annotation that has required elements (or even to imply an annotation and provide any non-default set of values): #240 #241.)

**Comment by kevinb9n** [comment]
The goal of supporting `@Implies(One.class) @interface Two {}` is that eventually, _most_ code of all kinds that wants to query for the presence of `@One` would use APIs that follow the links automatically; i.e., would just query for "is `@One` present" and get the answer `true` for cases like `@One m()` _and_ `@Two m()`.

Such an API would have to be able to actually provide the instance of `One` that was found, so it must have a deterministic way of handling attribute conflicts.

What's a good description of the simplest thing we can possibly do?

**Comment by cpovirk** [comment]
My proposal for that was:

> The easy way out is always "If an annotation is implied more than once with any difference in any of its values among them, then all annotations are unrecognized."

I guess we could alternatively say that any conflicting values are resolved to whatever the default is? (I assume that information is available to all tools that would need it, but I haven't checked.) That's not necessarily ideal, either: If someone implies both `@Nullable` and `@Nullable(polyNull = true)`, presumably we'd prefer the _non_-default value. But for any type more complex than a `boolean`, there could be multiple possible non-default values, so we wouldn't have a way to pick among those.... Anyway, having _some_ rule may at least be better than ignoring `@Nullable` entirely?

(Oh, and in everything we've been saying here, if `@Foo` is `@Repeated`, then we just behave as if both `@Foo(bar = true)` and `@Foo(bar = false)` are present.)

**Comment by kevinb9n** [comment]
This gets back to the age-old ambiguity with default values: sometimes accepting the default means "I really don't care what this is", and sometimes it means "I care what it is and I happen to want the same value as the default value", and you can never tell which it is. If people only coded under the assumption that *default values might change* then their code would be more clear about its cares.

As it is, yeah, I think we just declare all to be unrecognized...

**Comment by kevinb9n** [comment]
It occurs to me that even if the explicit value happens to match the default value, it just means that explicit value is unnecessary and is waiting to break if the default is ever changed. Changing an annotation attribute default thus becomes a nullness-incompatible change. So it might be worth handling the same way.

**Comment by kevinb9n** [comment]
So to handle `@Foo(bar = XYZ) @ImpliesFoo` *whether or not* `XYZ` is `bar`'s default:

For now I think we should treat it the way we do other contradictory pairs of annotations. Part of this is that I would really like `@ImpliesFoo` to _mean what it means_, not _sometimes_ mean what it means but sometimes mean only part of that. I'm not certain that's a realistic outcome, but....

As a longer-term question before 1.0: when analyzing dependent code only (not the code itself), something gives me pause. It feels hard to blame a library for seeing the `@Foo` and returning the `Foo` instance for it without recursively checking all the `@Implies`. But, that implies a "direct annotation wins" world in practice, that'd make people question why we even complain about it at all.

**Comment by cpovirk** [comment]
I can't find a reason to care about whether we treat `@Foo(bar = XYZ) @ImpliesFoo` as a conflict or not, so treating it as a conflict SGTM.

As for the model of throwing out everything else that `@ImpliesFoo` implies, too: I think that model would block `@Implies` on further work. I'll explain....

The model as I'm understanding it would be this:

There is a set of annotation usages that are present in the code (either source code or bytecode; the difference doesn't matter here). So you might have `@Foo @Bar(true) @Baz(1)`.

From that, we can compute another set of annotation usages that are in the reflexive, transitive closure of the "code annotations'" `@Implies` graph. Maybe that's `@Foo @Bar(true) @Baz(1) @Baz @X @NotX @Y`.

For every pair of annotation usages in the computed set, we look for conflicts. Conflicts would include `@Baz(1) @Baz` (whether `1` is the default or not) and (presumably) `@X @NotX`.

Now we retrieve every "code annotation" that implied any of those 4 annotation usages. And we update the computed set by removing everything that is part of those "code annotations'" reflexive, transitive closure.

Does that sound right?

The tricky thing about that is that a tool needs to know that `@X` and `@NotX` are conflicting. In other words, I don't think we can implement this scheme unless we do https://github.com/jspecify/jspecify/issues/101 first.

In contrast, the nice thing about the ugly "sometimes mean only part of that" model I'd been floating recently is that it _doesn't_ need that: For any given tool, either:

- The tool understands `@X` and `@NotX`. In that case, it knows they're conflicting, so it can remove them, or...
- The tool doesn't understand them. In that case, it doesn't know to remove them, but that's fine because:
   - The tool doesn't care about them, and...
   - We don't ask the tool to know to remove any of the _other_ annotations that were implied by the same "code annotations." (That's the part that's different from the model you're proposing.)

**Comment by kevinb9n** [comment]
Okaaay, this makes the point extremely well that I was indulging in wishful thinking far removed from reality. I shall never speak of this "mean what it means" business again.

**Comment by kevinb9n** [comment]
I coughed up [wiki/incorrect-annotations](../wiki/incorrect-annotations) but it still needs a lot of editing.

I think there is a proper way to address this:

* There is no good reason to write `@Foo(bar = XYZ) @ImpliesFoo` and (to start off imprecisely) we can agree that it is definitively "wrong" (even when the default is XYZ).
* JSpecify's primary interest is in defining "what annotation usages mean". In this usage, we define that it means nothing. (That's not the same as "it's undefined what it means".)
* An analyzer finding either has the goal of validating `@Foo` annotations themselves, or the goal of using the information to uncover real problems (discussed in wiki).
    * If the first, it *should* report a problem here (even if it's just that `ImpliesFoo.class` isn't present for validation ([#294](294))).
    * If the second, it is *entitled* to trust the direct `@Foo` without looking more deeply into it. For that matter, if for some strange reason it checks into `ImpliesFoo` first and it finds `@Foo(bar = ABC)` through that route, it's entitled to trust that too! It's entitled to assume that the annotations have been used correctly. If it happens to discover the conflict, there is little point in our dictating how to resolve the conflict; we may as well just say tool behavior is undefined.

**Comment by cpovirk** [comment]
Allowing tools to trust the direct `@Foo` sounds like it will lead to [`@MyFavoriteDefaults @ButNotThisOne`](https://github.com/jspecify/jspecify/issues/216), since that will likely "work" for clients. The hope would be that the library itself would be run through a checker that flags these problems. But if we trust the checker to implement the right logic for analyzing the library, then can we also trust it to implement the right logic for analyzing the clients?

On the conceptual level, I'm surprised that you would say that annotations "mean nothing" but that tools are entitled to assume that they mean something. It seems equivalent to saying that it _is_ "undefined what it means."

**Comment by cpovirk** [comment]
For example, that sounds to me like saying:

"The annotation in `class Foo<@Nullable T>` means nothing, but tools are entitled to assume that nullness annotations are used correctly, so we're fine if they want to interpret it like `<T extends @Nullable Object>`."

As always, we're not in the business of forcing any tool authors to do anything. But I'd expect us to hold the line on discouraging them from interpreting our annotations as meaning something that they don't.

**Comment by kevinb9n** [comment]
> Allowing tools to trust the direct `@Foo` sounds like it will lead to [`@MyFavoriteDefaults @ButNotThisOne`](https://github.com/jspecify/jspecify/issues/216), since that will likely "work" for clients. The hope would be that the library itself would be run through a checker that flags these problems.

Scenario:

1. Library has `@Foo(bar = XYZ) @ImpliesFoo some_api_element` or `@Nullable @ImpliesNonNull some_api_type`
2. Library owner isn't running analysis, or the analyzer doesn't catch the problem, or they ignore the report
3. A client's analyzer doesn't catch the problem either, so behaves as if `@Foo(bar = XYZ)` *has* effectively overridden the value intended by `@ImpliesFoo` (which can only be the default value), or that `@Nullable` *has* effectively overridden the `@NonNull` from `@ImpliesNonNull`
4. That might well be the behavior the library owner wants, so ... why *should* they fix the problem?

Possible remedies I can think of:

* Just don't worry about it. We aren't saying client analyzers *can't* discover the problem and make a stink, so maybe eventually some client will complain that theirs did, and the JSpecify specs may be consulted to figure out what to do. By having an unambiguous answer for them there, we've *basically* done our job.
* Define instead that the more local annotation does have precedence.
* Attempt to hold client-side analyzers responsible for always uncovering problems like this.


> But if we trust the checker to implement the right logic for analyzing the library, then can we also trust it to implement the right logic for analyzing the clients?

I don't know what this means; those are in all likelihood different checkers. Even if the same product, they may be different code paths pursuing different goals. Did the EqualsTester analogy land at all?


> On the conceptual level, I'm surprised that you would say that annotations "mean nothing" but that tools are entitled to assume that they mean something. It seems equivalent to saying that it _is_ "undefined what it means."

These discussions get too philosophical too fast. I can only tell you how this is structured for me. If you don't like this framing, I would *like* to think we can just work it out and adopt a common framing, but I'm *way* past hoping for that anymore.

Here is my perspective:

One conversation we can have is about "what is the meaning expressed by these annotations", in the deepest, truest sense. And I think it's our job to be unambiguous about this. And whenever we can assign true valid meaning to them, then tools should not treat them as meaning anything different. And whenever we can't, we would *rather* tools did not ascribe meaning to them anyway as suits their whims.

This conversation is at a different level from that one. This asks, "if a tool seeks to know Fact X, and it has gathered enough information to know 'either Fact X is true or the annotations would have to be invalid in some way I have yet to recognize', is it responsible for digging further to find invalidities, or is it fair to proceed as though Fact X is true?"

An answer that "it's fair to do that" doesn't change what anything means or doesn't mean. It is just a concession to reality and pragmatism.

Another analogy:

Suppose you ask a person, "Is Bar a subclass of Foo?" and they ask to see `Bar.java`, and it says `class Bar extends Foo`. They would answer yes.

Suppose you ask them the same question, and they ask to see `Foo.java`, and it says `final class Foo`. They would answer no.

Neither one realizes that those two files are actually uncompilable together. But each is justified in their answer. I think it is unreasonable to hold either one accountable to answering any differently, when the real issue is obviously to *fix the actual problem* with the files.

**Comment by kevinb9n** [comment]
> For example, that sounds to me like saying:
> 
> "The annotation in `class Foo<@Nullable T>` means nothing, but tools are entitled to assume that nullness annotations are used correctly, so we're fine if they want to interpret it like `<T extends @Nullable Object>`."

You do see how different that case is, right?

**Comment by cpovirk** [comment]
To me, there are two remedies: Either we define that the local annotation wins, or we hold clients responsible for uncovering the problem. If we do something other than that, I don't see us as providing "an unambiguous answer." (I prefer the second option, but I think you're right that the difference is deeper than that.)

It's always true that tools can do whatever they want, so what I'm trying to understand is why this situation is _different_ from any various situations. We don't typically couch our rules in "`@NonNull` on a type-parameter bound means that the parameter forbids nullable types, but if a checker sees a `@Nullable` type argument, it's entitled to conclude that the parameter actually allows nullable types." Could a checker do that? Sure. Could it even have a good reason for that? Sure.

I can get behind the idea of warning users that, if they do things that JSpecify considers to be "wrong," then they're likely to end up in uncharted territory, under which different tools will do different things. That, too, feels like a general point, but I wouldn't mind making it specifically here. But I would still see those tools as _buggy_, not as exercising their choice for a question we left as implementation-defined behavior. I don't think you see it as implementation-defined, either, and maybe your concept of "entitlement" is getting at something similar to my concept of "warning users?"

**Comment by cpovirk** [comment]
Loose ends: 

We can probably drop the "separate tools" discussion. I was trying to emphasize the point that conflicts will arise in practice, which I was taking to already be a point of agreement.

As for `EqualsTester`, the difference I see here is that it's _possible_ for a tool to exhaustively check for conflicting annotations (and in a way that doesn't make the worst-case performance any slower). That's not possible for users of `equals`.

I do see this case as similar to `class Foo<@Nullable T>`: In both cases, we're asking authors of "Primary analysis" tools to write additional code that exists only to handle cases that would have failed "Annotation validation." The two cases are separate cases in the sense that each requires its _own_ additional code. But similar to above, I'm not sure why we would address the two differently.

**Comment by kevinb9n** [comment]
The main topic of your comment is now being discussed in #307 (thanks for filing that). It's tagged to a later milestone than this one, so this one is still relevant.

A second topic in your comment is:

> An additional alternative for consideration: Annotation A cannot imply annotation B if annotation B has parameters

So I've filed that as #308.

Let's let *this* issue (259) return to being about this issue (259). 

It presumes that the implication link between the two annotations is valid, so a "yes" on any part of #308 would seem to render this one obsolete.
