### ISSUE TITLE
Educational design article about "null pollution"

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#283]
This describes a set of problems that aren't feasible for JSpecify to "solve". We can however help guide users and tool owners on how to avoid problems. Most of the below should become documentation at some point.

## Null pollution

When an expression JSpecify defines to have a non-nullable type evaluates to null anyway, **null pollution** has occurred somewhere in the application. This is largely analogous to the “heap pollution” risk introduced by generics in Java 5. (Neither is specifically related to the heap *per se*.)

### Causes

Null pollution is a "fact of life" that can happen for various reasons:

1. Some code in the application was never null-analyzed.
2. A checker was not JSpecify-compliant (e.g. had a bug).
3. A checker didn't support "sound" analysis (which JSpecify doesn’t mandate).
4. A JSpecify finding was ignored.
5. Reflection!
6. The developer suppressed a warning, believing it harmless or impossible in practice (EDIT: as a *special case*.). For example, they write `null` to a non-nullable field they know is never again read. (The most interesting case for us.)

### Effects

A null pollution *might eventually* cause an `NullPointerException` in a location where no JSpecify finding exists:

1. a dereference
2. an explicit runtime check like `Objects.requireNonNull`
3. a runtime check inserted by a transpiler or bytecode rewriter (e.g. IDEA has this feature)
4. crossing the border with Kotlin (etc.)

But sometimes no blow-up will happen.

### A complication

A developer might suppress a finding (Cause 6) and justify it by inspecting the surrounding source code and seeing that they are safe from Effects 1 and 2. But they might forget to think about Effects 3 and 4 (or those could come along later). The result would be an "overzealous" NPE that tries to protect against a real-world problem that was never going to happen.

Put another way, these two things are at odds with each other:

* The practice of tools to base runtime checks on JSpecify-provided information.
* The practice of developers to suppress warnings when their code is "logically" safe.

This conflict has in the past hampered our decision-making clarity on issues like #225, which was the trigger for writing all this up.

### Proposed stance

* Tool owners who insert runtime checks should be aware that sometimes JSpecify findings are meant to be suppressed. The tool should, if possible, devise a way that their own checks can be suppressed as well.
* Developers who suppress warnings should be aware if their code might be used with tools that insert runtime checks. They might need to follow the tool's advice for how to suppress.

Occasionally a perfect storm will cause a frustrating situation for a user, but this seems like a manageable risk.

**Comment by cpovirk** [comment]
That sounds good to me. One additional thing that came up in some past discussions (like #225) is that suppression is likely to work well for "internal" APIs but not for "widely accessible" ones. The contrast is something like this:

- If a bytecode rewriter is inserting `requireNonNull`-like checks every time you write to one of your non-nullable `private` fields, then that tool is likely to have a way to disable those checks, either universally or for particular fields. Thus, you can easily get away with writing `void close() { someNonNullableField = null; }`.
- If kotlinc is inserting `requireNonNull`-like checks every time you pass a value to a Java method's non-nullable parameter, then Kotlin is _not_ likely to provide a way to disable those checks. Thus, you're not likely to get away with writing `public void set(Field f, Object value)` and telling your Kotlin users who want to pass a null `value` to "suppress the warning."

I think that's worth mentioning somewhere. It's mostly an addition to what you've said: The only part that is perhaps slightly at odds with your writeup is that you might be read as implying that everyone can behave as if _all_ nullness findings are suppressible. That's not the case now, and if we were to decide that we want it to be, we may find that to be a tough sell to the Kotlin team :)

**Comment by kevinb9n** [comment]
To this point I agree, and I'd suggest that is handled by including this in our advice for API owners: "Don't assume that your users can always suppress nullness findings" (with necessary explication). Anything else?

**Comment by kevinb9n** [comment]
I'm going to reopen this as a "write a design article about null pollution" issue.

**Comment by kevinb9n** [comment]
Though the new wiki page has a TODO pointing back to a comment here, I think this can be considered closed.
