### ISSUE TITLE
Discourage (or stronger) `@Null*arked` from non-static members of generic classes

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#292]
The current working decision ([#43](43) [#127](127)) is to allow both `@NullMarked` and `@NullUnmarked` at the method/constructor/nested-class level.

The most troublesome negative consequence of that decision was [stated here](https://github.com/jspecify/jspecify/issues/127#issuecomment-884566188): an unprojected usage of a type variable might be null-marked or not *independently* of whether that type variable's *bounds* are null-marked or not, and this gets really hard for normal people to reason about.

Option 1:

* We keep figuring it out until we can explain it really well (then we explain it really well).
* We make sure the spec makes it unambiguous (it might already).
* We make sure to cover various permutations in our conformance tests.

Option 2:

* We say: look, don't put `@Null*arked` on a non-static member (field/method/inner-class) of a generic class; results may be undefined if you do. (Note we can't *prevent* them from doing it.)
* We don't include these cases in our conformance tests, or optionally we test that an analyzer can report an don't-do-that

My observations in favor of 2:

* having to avoid that case seems like no great loss to users
* it eliminates the troublesome scenario above
* I feel like if we have to have documentation explaining how to think about that weird scenario, it ends up making our whole product look more complicated.
* I don't think 2 would close the door on doing 1 sometime later, perhaps even post-1.0.

**Comment by cpovirk** [comment]
There are a bunch of ways to mix specified and unspecified nullness, and the scenario you describe is likely to be a relatively unusual one. So I can see wanting to further marginalize it. At the same time, that scenario has to be handled by the underlying model anyway (and it is, and we have lots of sample inputs for cases like this), so we'd have to go out of our way to _not_ respect the nullness information that users have provided us. Given that, I see a lot of reason to avoid discussing the scenario in any detail in our main docs, but I don't see reason to declare it to be undefined.

The typical ways of mixing specified and unspecified nullness are when a `@NullMarked` class uses a `@NullUnmarked` class or vice versa. But within a single class, there's the scenario you mention, plus the scenario of annotating only a type-parameter bound in `@NullUnmarked` code. For whatever we want to do for your scenario, we'd likely want to to do for that last case, as well. At that point, every type-variable usage would have specified nullness if and only if its type parameter's bound had specified nullness.

...wellllll... kind of... :( We can produce essentially the same scenario when a `@NullMarked` class uses a `@NullUnmarked` class (or vice versa):

```java
@NullMarked
class Marked<T> {
  T get();

  Unmarked<T> unmarked;
}

class Unmarked<T> {
  T get();

  Marked<T> marked;
}
```

Inside `Unnmarked`, `marked.get()` returns "just `T`," but we don't know if `T` permits nullable type arguments or not. Similarly, inside `Marked`, `unmarked.get()` returns "maybe just `T` or maybe some projection of `T`," but we still know that `T` doesn't permit nullable type arguments.

Again, I agree very much with not pushing this kind of scenario into users' faces. But in cases in which we have enough nullness information to tell users about mismatches, I think we should tell them: If someone writes `class ImmutableList<E extends @NonNull Object>`, I think that person is asking us to produce errors for `ImmutableList<@Nullable String>`, even if that person hasn't annotated the rest of `ImmutableList` yet and even if that person couldn't stand at the whiteboard and derive all the information about expressions involving different usages of `ImmutableList`.

To oversimplify (but I hope only slightly): I think we have to say that, if you don't want to see nullness errors, then don't provide nullness information. I think it's fine to warn users that mixes of specified and unspecified nullness can be complex. But incremental adoption is perhaps the biggest "new" feature we're providing, and we have evidence from Kotlin that it's useful, even when people encounter scenarios like `someMarked.unmarked.get()`.

**Comment by kevinb9n** [comment]
> The typical ways of mixing specified and unspecified nullness are when a `@NullMarked` class uses a `@NullUnmarked` class or vice versa. But within a single class, there's the scenario you mention, plus the scenario of annotating only a type-parameter bound in `@NullUnmarked` code. For whatever we want to do for your scenario, we'd likely want to to do for that last case, as well.

I've been chalking that part up to: "in null-unmarked code, a type variable usage (that isn't already unspec-bounded) that isn't being projected is automatically an 'unspec-projection'". And [#248](248) is about whether that happens in one or both directions. Eh?

**Comment by kevinb9n** [comment]
There's nothing we really need to do here

**Comment by kevinb9n** [comment]
(I did the "discouraging" in #349 anyway.)
