### ISSUE TITLE
Warn users about using `provided`/`optional`/`implementation` for annotation deps, especially with `@Implies`

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#294]
I wrote something about those scopes for Guava users in https://github.com/google/guava/wiki/UseGuavaInYourBuild#what-about-guavas-own-dependencies, but here we'd be writing primarily to other library authors who are making their own decisions about what scope to use.

We'll hopefully be defining annotations such that those scopes can't cause "`Cannot find annotation method 'value()'`" problems, but I don't know that we'll be able to prevent all _runtime_ problems. And `@Implies` is going to be a whole additional problem (somewhat similar to `@Inherited`) about which I'll file an issue shortly.

Some other links:
- https://issues.apache.org/jira/browse/MNG-2205?focusedCommentId=16267311&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16267311
- https://github.com/google/auto/pull/765#discussion_r332220988
- https://github.com/google/auto/pull/765#discussion_r335545477

**Comment by cpovirk** [comment]
(In our docs, we can mention that JSpecify is a small library (and, given our rate of progress, is going to stay that way ;)).)

**Comment by kevinb9n** [comment]
I think you were summarizing this issue in [#295](295) like this:

> When developers declare a dependency on a library of annotations (like JSpecify), they sometimes choose to declare the dependency in a way that tells tools: "When someone depends on my library, don't include that annotation library on that user's classpath, either at build time or at runtime." I think this is a bad idea in general (and so I want to discourage it).

So unless we reverse course on "bad idea", we should continue this evangelism, and strongly advise tool owners that they should issue loud warnings when they spot an annotation they know nothing about. And maybe even add a javadoc blurb to `@Implies` in particular about it.

**Comment by cpovirk** [comment]
See also #389.

**Comment by cpovirk** [comment]
Continuing to dump links without thinking deeply: As long as nullness checkers contain [code like this that introspects on annotation declarations](https://github.com/eisop/checker-framework/pull/658/files#diff-31c76fc7e4107f7c9b5b669df12d97019969593c9980ce852dba8ddc0fd81cc4R98), we will have another reason to worry about building without those annotations on the classpath.

**Comment by netdpb** [comment]
This is written in the docs-1.0 branch, which we'll merge into main soon.
