### ISSUE TITLE
DefaultNotNull and the split-package case

### ISSUE THREAD

**Issue by amaembo** [jspecify/jspecify#30]
Recently we stumbled across the following problem. User had two versions of Spring framework library in the class-path, namely spring-core:4.3.23.RELEASE and spring-core:5.0.9.RELEASE. Spring 5 has package-level `NotNull` annotation in `org.springframework.core.annotation.package-info` (`org.springframework.lang.NonNullApi` to be precise), while Spring 4 has no such annotation. Several methods have overwritten nullability, e.g. `org.springframework.core.annotation.AnnotationUtils.findAnnotation` is marked in Spring 5 as `Nullable`, but not marked at all in Spring 4. So normally for Spring 4 IDEA should use "unknown" nullability (or try to infer it from method bytecode as we sometimes do) while for Spring 5 it should use "nullable" nullability. However when both present in the classpath and Spring 4 comes first, IDEA finds the `findAnnotation` method from Spring 4, sees that it has no annotation, then checks the package annotation and sees the `package-info` from Spring 5 (there's no `package-info` in Spring 4) which says that all methods in this package are not-null by default. Thus IDEA assumes that `findAnnotation` is not-null, which results in false-positive warnings.

I agree that it's a questionable project structure, but as we can see, it happens. So the question is  whether package-level annotations may affect classes from different class-path roots (e.g. different jar files). This is not a problem with JPMS, as split-packages are disabled there, but people still rarely fully migrate to JPMS. We should have a clear statement whether package-level annotation affects every class in given package, regardless of the class-path root (thus the observed behavior is intended and the only way user can get rid of the false-positive warnings is to fix the project setup), or package-level annotations affect only that class-root where they are defined (thus the observed IDE behavior needs to be fixed). In Spring JavaDoc there's no clear statement whether `org.springframework.lang.NonNullApi` could affect different class-path roots, and we are inclined to fix this particular case to make user happy. But for our project we may settle with different decision.

Related to #8.

**Comment by kevinb9n** [comment]
We can only address this by giving users warnings about the pitfalls.
