### ISSUE TITLE
Are nullness annotations "applicable" to `var` in a lambda signature

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#303]
See #261 discussion

EDIT: Example: 

```java
void foo(Consumer<? extends @Nullable String> consumer) {}

void bar() {
  // case 1
  foo((var s1) -> out.println(s1));

  // case 2
  foo((@Nullable var s2) -> out.println(s2));
}
```

A "yes" answer means:
* `s1` is non-null or unspecified, based on presence of `@NullMarked`
* `s2` is nullable

A "no" answer means:
* `s1`'s type is inferred by an analyzer ([this comment](261#issuecomment-1269087842) suggests it "should" probably be inferred as non-null, at least if we are in null-marked code (?))
* `s2` is handled like other cases of present inapplicable annotations (defined to have no meaning; expect tools to probably report; ignored if seen in a dependency)

**Comment by cpovirk** [comment]
Thread in which I try to get type-use annotations on `var` made into invalid Java: https://mail.openjdk.org/pipermail/compiler-dev/2022-October/020593.html

That said, even if that goes through, we'll have work to do:

- Since some versions of javac permit the annotations, we should write in the JSpecify spec that they're unrecognized/inapplicable/whatever we end up calling such things. Ideally, tools will then complain when they see them.
- We have a decision to make about _declaration_ annotations, which _are_ definitely allowed.
- For that matter, we have a decision to make about declaration annotations _on local variables_, since Java permits that with `var`, too.

**Comment by kevinb9n** [comment]
Groovy. Given that viewpoint, then whether it actually happens or not I would still propose we declare these locations nullness-inapplicable.

What is the issue with declaration annotations? We don't have any that could go there anyway, and if it's a decl ann that `@Implies` something, we already define that such an annotation is meaningless wherever the implied annotation would be inapplicable.

**Comment by kevinb9n** [comment]
As for *what happens* if we go that way, Chris said:

> If the "not" case, I would assume that the type would be inferred, rather than nullable. Otherwise, a lambda like `e -> e.getKey()` is going to fail nullness checking until it's rewritten to `Entry e -> e.getKey()` (OK, fine `Entry::getKey` in that case :)).

Yes, inferred is what I thought.

**Comment by cpovirk** [comment]
> we already define that such an annotation is meaningless wherever the implied annotation would be inapplicable

Ah, true. Arguably the spec should still be explicit about this: It's not too far-fetched to think that a declaration annotation on a parameter/variable/whatever should be treated like a type-use annotation on its top-level type, _regardless_ of whether that top-level type appears in source code. But probably the more important part is to cover this case in our conformance tests :)

**Comment by netdpb** [comment]
Could someone update the first comment with an example?

**Comment by msridhar** [comment]
From my comment at https://github.com/jspecify/jspecify/issues/261#issuecomment-1275472833:

> I am also fine with not allowing nullness annotations on `var` lambda parameters for consistency with locals; I think if a developer wants to annotate a lambda parameter for nullness, they can be asked to give a full type and not use `var`.

**Comment by kevinb9n** [comment]
> Could someone update the first comment with an example?

Done; can you check if I screwed it up?

**Comment by kevinb9n** [comment]
@artempyanykh says:

> To me, lambda params are closer to method parameters than to locals. Therefore, I don't see a problem with `var` denoting a root type while allowing `@Nullable` qualification and thus affecting the type argument of the lambda's target type. This also reminds me of `auto` and `auto&` in C++ – not saying it's a pinnacle of design but it's a precedent.
> 
> OTOH, we don't support annotated `var` lambdas. I also don't feel too strongly about this. So, if the group decides to forbid the pattern `(@Nullable var x) -> ...` and require spelling out the full type, I'll support this decision.

I agree that similarity-to-locals would not be a good reason for this. My concern is more that if `@Nullable var` is allowed, that suggests `var` means *non-*null (in null-marked code; unspec otherwise). But that conflicts with the idea that `var` is a way to opt out of having to say anything about the type.

**Comment by artempyanykh** [comment]
@kevinb9n 

> My concern is more that if @Nullable var is allowed, that suggests var means *non-*null

This is a very good argument! I'm convinced now.

**Comment by kevinb9n** [comment]
Cool!  For now, I've added a note to [wiki/type-usages](../wiki/type-usages), but have a pending TODO to reconcile that page with the spec and javadoc.

@cpovirk If you bump your compiler-dev thread again you might throw in a bit about this... Many type-use annotations have no corresponding *negation* annotation, simply interpreting the absence of the annotation to mean that negation. But on var, absence will always appear to mean "I don't care, I'm expecting the type to be figured out for me", so this will always be ambiguous.

(yes, even `@Nullable` has no negation, which would have to be something like `@NonNullOrUnspecifiedOrParametric`)

**Comment by netdpb** [comment]
**Current decision**: "Lambda parameters that are `var` or untyped have their nullness inferred. See #261. Java may explicitly forbid type-use annotations in this context.

**Argument for changing**: None.

**Timing**: This must be decided before version 1.0 of the jar.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by kevinb9n** [comment]
Nice, it looks like javac is plugging this hole:
https://github.com/openjdk/jdk/pull/29687

\[cpovirk edit: https://github.com/jspecify/jspecify/issues/261#issuecomment-1289025455 has more links.\]
