### ISSUE TITLE
Renumber 0.3 to something more indicative of how much has gone into it

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#304]
I think the number 0.3 is sending the wrong PR message at this point.

Even just 0.5 would be an improvement. Whoa, we're halfway there! But I would find a higher number appropriate. A *lot* has gone into this and I tend to think we should communicate a more accurate idea. Say 0.8?

*Yes I completely realize there's no science to this...* We're not actually trying to do a linear interpolation of "how much of the way there" we are. But the number *will communicate something* to people who hear about it.

**Comment by netdpb** [comment]
I don't think anyone will actually care about the meaning of the numbers that are less than 1.

**Comment by kevinb9n** [comment]
What I'm positing is that they may not *care* but they will take away a subconscious impression from it anyway.

Do the guidelines of semantic versioning point any particular way on this?

**Comment by JakeWharton** [comment]
0.5 is only halfway to 0.10 and not necessarily to 1.0!

I do think _very_ low 0.x numbers can be perceived as immature (unless you're doing Rust where they're exceedingly common). But as to whether 0.5 vs. 0.8 vs. 0.42 is any better than the other I have no idea.

**Comment by cpovirk** [comment]
AFAICT semver.org talks only about "incrementing," which suggests not advancing beyond 0.3 until there's been a 0.3. But I'm not sure it really sets rules for _versions below 1.0_ beyond saying that they should match their grammar. Notably:

> **How should I deal with revisions in the 0.y.z initial development phase?**
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

**Comment by kevinb9n** [comment]
Cool, less work.
