### ISSUE TITLE
`@Null*arked` on record components

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#306]
See summary in https://github.com/jspecify/jspecify/issues/43#issuecomment-881061588, with discussion starting in https://github.com/jspecify/jspecify/issues/43#issuecomment-700277489.

It might be that all we can do is to encourage tools to report an error if compiling code that uses `@NullMarked`/`@NullUnmarked` on a record component. And probably people won't even think to try that in the first place, so we're probably fine in practice no matter what.

**Comment by kevinb9n** [comment]
I'll mention in a NullMarked/NullUnmarked javadoc update that they have no meaning on a record component.

**Comment by kevinb9n** [comment]
Fixed by #349
