### ISSUE TITLE
An annotation with any attributes (even with defaults) "cannot" be used with `@Implies`

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#308]
(The word "cannot" is in scare quotes because much of the discussion below is about unpacking what that really means in our context.)

From [a #259 comment](https://github.com/jspecify/jspecify/issues/259#issuecomment-1293888308) by @Mooninaut:

> An additional alternative for consideration: Annotation A cannot imply annotation B if annotation B has parameters

Here's one interpretation I've extrapolated from that line for discussion.

Given this example (whose three sections might be in the same file or in entirely different projects):

```java
public @interface One {
  String anyParameter() default "any default"; // or other type
}

@Implies(One.class)/*X*/
public @interface Two {
  // may have params; example has none for brevity
}

@Two/*Y*/ some_program_element;
```

Then this issue's purpose is to decide what subset of the following should be true:

1. An analyzer that validates correct usage of JSpecify annotations, when it analyzes `Two`, must recognize a finding at `/*X*/` to the effect that `One.class` is not a marker annotation type as required.

2. An analyzer or library that depends on whether `some_program_element` is conceptually-not-literally-annotated with `@One` must recognize the answer as "no".

3. An analyzer that validates correct usage of JSpecify annotations, when it analyzes `some_program_element`, must recognize a finding at `/*Y*/` to the effect that a malformed annotation `@Two` is in use. (i.e., one level of recursive validation)

("must" is just short for "is non-conformant unless"; also "recognize a finding" does not mean the tool is in any way to report that finding to its *users* in any particular way or at all.)

You might have a 4 or 5 to add, perhaps.

Of course, what I call different analyzers here might all be the same one. I prefer to consider them independently, as currently discussed a bit at [wiki/two-kinds-of-analysis](../wiki/two-kinds-of-analysis).

**Comment by kevinb9n** [comment]
Tagged 0.3 for now because some outcomes could resolve other issues blocking 0.3.

**Comment by kevinb9n** [comment]
### Clearest argument I know for "NO/NO/NO"

If the `One` annotation type has no attributes, then is edited it to add an attribute *with a default value*, that should by rights be a safe change.

### Clearest argument I know for "YES/YES/*"

Simply to get out of having to resolve issue #259. (How to resolve question 3 is more of a detail we could discuss later.) But it's not necessarily clear that doing this would be easier. For now I still cling to optimism.

**Comment by Mooninaut** [comment]
Upon further consideration, I remembered that annotations in Java can be marked `@Repeatable`. It would be valid for such an annotation to be used directly, without `@Implies` (with or without arguments) multiple times. I don't think it should be an error for a non-marker annotation to be `@Implies`-ed if it is marked `@Repeatable`. 

Otherwise, it should be an error (Y/Y/Y).

One could argue that it's OK to use a non-marker non-repeatable annotation with a default value as long as no single program element is annotated with both the default and a non-default value. I think that would require an undue level of sophistication in tools, but it's certainly _possible_.
