### ISSUE TITLE
Nullness: Annotating wildcards and their bounds

### ISSUE THREAD

**Issue by abreslav** [jspecify/jspecify#31]
> Extracting this from https://github.com/google/codeanalysis-annotations/issues/19 for better granularity.

### What we seem to agree on
* Wildcard bounds can be annotated, as in `Foo<? extends @Nullabe Bar>`
* There's a parallel with type parameter bounds, and it would be logical to apply the same rules

### The current rule for type parameter bounds

In the context of `@DefaultNullable`/`@DefaultNotNull` if a type parameter has no explicitly annotated bound, its bound is considered to be annotated according to the specified default.

### Questions
* Is each of the following forms allowed and if yes, what does it mean: `Foo<@NotNull ?>`, `Foo<@NotNull ? extends @Nullable Bar>`, `Foo<@NotNull ? super @Nullable Bar>`
* Does the default specified by `@DefaultNullable`/`@DefaultNotNull` apply to the wildcard itself? (If we give that any meaning while answering the previous question)
* Does the default apply to explicit bounds if they are not annotated? E.g. does `Foo<? extends Bar>` become effectively `Foo<? extends @NotNull Bar>` when in the scope of `@DefaultNotNull`?

### Unbounded wildcard (`?`)

It seems that we might need to allow annotating an unbounded wildcard `Foo<@NotNull ?>` because its bound is not always denotable, e.g. for the case of F-bounded recursive types, e.g.:

```
interface C<T extends C<T>> {
    T get();
}
```

It looks like `C<?>` and `C<? extends Object>` may not mean the same thing here, but in fact [JLS §4.5.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.5) says this:
> The wildcard `? extends Object` is equivalent to the unbounded wildcard `?`.

And the following code compiles correctly:
```
    void test(C<?> unbounded, C<? extends Object> bounded) {
        unbounded.get().get();
        bounded.get().get();
    }
```

The bounds from the declaration site are implicitly applied to the wildcard even if it declares only `Object` as its explicit bound, but then it's hard to tell how an annotation on the `Object` should interact with those implicitly applied bounds. So, for now, we have it as an open question.

### Bounded wildcards

A wildcard type in Java can specify either an upper bound (`? extends Foo`) or a lower bound (`? super Foo`). The bounds are normal type usages, so they can be annotated explicitly as `@NotNull` or `@Nullable`. 

By analogy with type parameter bounds, it would make sense to apply defaults to unannotated wildcard bounds. E.g. `Foo<? extends Bar>` becomes effectively `Foo<? extends @NotNull Bar>` when in the scope of `@DefaultNotNull`.

#### "Write-only list of not-null Foo"

The intuition for `List<? super Foo>` is roughly "a write-only list of Foo". One may want to say something like "write-only list of not-null Foo", or "a list where you can add only not-null Foo's". 

Observation: `List<? super @NotNull Foo>` does not capture this intent because it can be assigned `List<@Nullable Foo>` (`@Nullable Foo` is a supertype of `@NotNull Foo`).

To express this intent, one could use the fact that each wildcard implicitly has two bounds, so that `? super Foo` means actually "lower bound Foo, upper bound Object` (and `? extends Foo` is "lower bounds Bottom, upper bound Foo", where Bottom is the subtype of all types, i.e. the empty type, like Kotlin's `Nothing`). 

So, the "write-only list where you can only add not-null Foo's" would be a list of "lower bound `@NotNull Foo` upper bound `@NotNull Object`). We could adopt a convention that this can be expressed as `List<@NotNull ? super @NotNull Foo>` where the annotation of the `?` applies to the bound that is not explicit.

Some more examples of this convention:

Supertype  | `List<@NotNull Foo>` | `List<@Nullable Foo>`
--|--|--
`List<@NotNull ? super @NotNull Foo>` | subtype | not a subtype
`List<@Nullable ? super @NotNull Foo>` | subtype | subtype
`List<@Nullable ? super @Nullable Foo>` | not a subtype | subtype
`List<@NotNull ? super @Nullable Foo>` * | not a subtype | subtype
--|--|--
`List<@NotNull ? extends @NotNull Foo>` | subtype | not a subtype
`List<@Nullable ? extends @NotNull Foo>` * | not a subtype | subtype
`List<@Nullable ? extends @Nullable Foo>` | not a subtype | subtype
`List<@NotNull ? extends @Nullable Foo>` | subtype | subtype

\* Inconsistent bounds

> Notes on the related discussions are available [here](https://docs.google.com/document/d/1-J1FSqjx1DqglIQPSlC_tX0O7Kj2mDoy_kIG7c1-fLw/edit#).

**Comment by kevinb9n** [comment]
(Last comment is about #83.)

I think Denis's comment https://github.com/jspecify/jspecify/issues/31#issuecomment-521983935 is an accurate depiction of how we are thinking about this now.
