### ISSUE TITLE
Allow `@Null*arked` to target a field [working decision: no]

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#310]
So far: no (#50).

#50 also said "no" to method parameters and local variables. I don't want to encourage us to revisit _those_ parts.

I _do_ want to revisit fields, though not urgently.

We've compiled at least 3 reasons against `@NullMarked`/`@NullUnmarked` on fields:

(1) [We didn't use to even support `METHOD` and `CONSTRUCTOR`, and clearly the case for `FIELD` was worse than for those.](https://github.com/jspecify/jspecify/issues/50#issuecomment-526305512)

But now we've reversed that and allowed `METHOD` and `CONSTRUCTOR`. So we can consider `FIELD`, too, while still recognizing that its case is weaker than those.

(2) [From bytecode, we can't tell what was done inside a field initializer.](https://github.com/jspecify/jspecify/issues/50#issuecomment-1016598323)

But that's OK if we consider `@NullMarked` on a field to affect only the type of that field, not anything done in the initializer (e.g., inside an anonymous class).

This does mean that tools that read _source_ code will have to be careful not to over-apply the effects of `@NullMarked` on a field.

Beyond that, annotating a field is just _weird_:
- It's weird because fields don't count as "enclosing elements" the way that `@NullMarked`'s other targets do.
- It's weird that the annotation means _something_ there but not what users might naively expect. (Hopefully most users just don't care about this at all, since they won't annotate fields and/or won't annotate fields with initializers and/or won't think or care about how the annotation affects those initializers.)

(3) [We didn't have particularly compelling use cases](https://github.com/jspecify/jspecify/issues/50#issuecomment-520468335).

I wouldn't call what I'm about to say "compelling," but I can give a less uncompelling variant of my earlier argument.

One of the things we've been doing is annotating classes in the JDK. That includes putting `@NullMarked` on JDK classes. But what happens when we provide annotations for the Java 11 version of a class and someone tries to use them with Java 17? Our annotations might say that JDK class `Foo` is `@NullMarked`, but they won't have any information about a field `Foo.addedInJava17` (https://github.com/jspecify/jspecify/issues/94).

The conservative thing for tools to do is to treat `Foo.addedInJava17` as `@NullUnmarked`. And if the tool reads the JDK annotations directly, it can do that.

However, we've been talking about providing a tool to rewrite JDK jars to _actually include_ the annotations. That means that `Foo` would end up with an actual `@NullMarked` annotation in its class file. And then we need a way for the tool to tell nullness checkers "but `addedInJava17` is `@NullUnmarked`"... like, say, by automatically putting a `@NullUnmarked` annotation on it :)

Really, I might discourage users from writing these annotations on a field themselves. But having the ability to insert them (mainly `@NullUnmarked`) with a tool might be valuable.

Or this might be too niche to care about: Our tool could already label _methods_ as `@NullUnmarked`. How often would there be an API that is (a) newer than our JDK annotations that is (b) a public field  that (c) needs `@Nullable` or another annotation? It's probably rare. Hopefully we'll actually try this and get some real data someday.

**Comment by kevinb9n** [comment]
> It's weird because fields don't count as "enclosing elements" the way that @NullMarked's other targets do.

Fun times:

```java
private String foo = switch("You've") {
    default -> {
        class GottaBe { 
            ...
        }
        yield "KiddinMe";
    }
};
```

That is NOT a compelling use case for the feature. :-)

I do think in most ways allowing it on FIELD should be harmless.

But I do have one subtle concern. Right now the `@Null*arked` and the `@Nullable`/`@NN` annotations don't tread on each other's turf much at all... with the exception that they *could* mix it up in and around method modifiers (google-java-format, for one, fixes that).

Their domains being neatly partitioned might be helpful to novice users keeping the "big and clear" difference between them straight. I think if they see `@Null*arked` on a field or just that it *can* go there it might muddy the waters a bit. A field, unlike a method, really feels like the kind of "single unit" that would only have a type-use annotation (even though we know it has type components, and the code above notwithstanding).

Again, subtle.

> And then we need a way for the tool to tell nullness checkers "but addedInJava17 is @NullUnmarked"... like, say, by automatically putting a @NullUnmarked annotation on it :)

Sufficiently edgecasey and generally user-invisible that perhaps a tool-specific `@ImpliesNullUnmarked` would serve?

**Comment by cpovirk** [comment]
_If_ it turns out that we care about this for types in the JDK or other types that we want to annotate, then we may want it to work across tools. But now that you mention it, maybe we'd only really _need_ it to work Kotlin, since that's the main tool that inserts runtime checks? If so, we may be able to satisfy it with a [`@TypeQualifierNickname`](https://kotlinlang.org/docs/java-interop.html#type-qualifier-nicknames) approach. (In doing so, we'd be defining and using [a type-use `@UnspecifiedNullness` annotation](https://github.com/jspecify/jspecify/issues/137) :\ But we can hold our noses, since, again, it would be a tool-specific annotation, one that we could avoid exposing to end users. [It wouldn't be the first time](https://github.com/google/guava/blob/6d7e326b2cbfba5f19fc67859c0b3d4c45fab63f/guava/src/com/google/common/base/ParametricNullness.java) :))

As for the concern: I'm not sure how much differently users will see fields and methods. But I definitely grant that, between the two of them, the field looks _more_ like a "single unit," And methods will always be the more compelling use case.

Primarily, I'm holding out hope that my proposed problem scenario is rare enough that we'll find it easiest to just manually annotate any public fields that need `@Nullable`.

**Comment by cpovirk** [comment]
I also see a _slight_ connection to another idea that I think has come up, the idea of annotating only the _user-visible_ parts of a class. For that purpose, it could be nice to be able to annotate a class (or enclosing package/module) as `@NullMarked` and then put `@NullUnmarked` on all its `private` and package-private members—including fields. (This reminds me of Spring's [`@NonNullApi`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/lang/NonNullApi.html)/[`@NonNullFields`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/lang/NonNullFields.html) distinction.)

This just came up because AutoValue annotates its user-facing APIs but not its fields. That said, we're likely going to just get AutoValue to address that :) Plus, for obvious reasons, most tools don't care about the private members of a class in the first place, so incorrect annotations there usually don't matter (though they do in the unusual case we got a report about).

I still don't see this as an important reason to have `FIELD` as a target. If anything, it is a slight motivation for opening an actual issue about "only the user-visible API is `@NullMarked`," except that that feels pretty iffy to me, too. If anyone really wants to do that, it's mostly possible to put `@NullUnmarked` on the class (if necessary to override an enclosing `@NullMarked` annotation) and then put `@NullMarked` on each user-visible method. The complicated case would be a generic class, but even that is still workable as long as each type-parameter bound can be declared as `extends @Nullable Something` or `extends @NonNull Something` (as opposed to `<T ..., U extends T>`).

**Comment by kevinb9n** [comment]
To be clear about my little gotcha

```java
@NullMarked
private String foo = switch("You've") {
    default -> {
        class GottaBe { 
            ...
        }
        yield "KiddinMe";
    }
};
```

I am saying that I think if we allowed it, it *has* to make the `GottaBe` class null-marked as well.

**Comment by cpovirk** [comment]
Yeah. While I am happy to have spent November with this bouncing around in my brain, I think it's clear that some new information would have to surface for us to consider it worthwhile.

I agree that the gotcha is bad (though hopefully very unlikely to come up). I might be willing to accept it _if_ we saw an actual, significant need for this (like in my JDK example above), but that need itself seems very unlikely to come up.

As a further point against this, I'd note that I wrote [my comment about annotating user-visible APIs](https://github.com/jspecify/jspecify/issues/310#issuecomment-1332307592) as if `@NullMarked` would affect only API signatures. But in fact we've said that it affects implementation code, too (though [doing anything with _annotations_ in implementation code _in bytecode_ is unlikely to go well, anyway](https://github.com/jspecify/jspecify/issues/301)). So anyone who does what I said in that comment would likely already be "lying" a bit, and it's hard to get excited about adding a footgun feature to help them lie slightly less in one case.

**Comment by cpovirk** [comment]
I am still happy with the answer of "no" here. But I'll note for the record that I just ran into a bug that was manifesting only when a particular field was recognized as non-nullable, and it would have been convenient to be able to use `@NullUnmarked` on that field.

That said, we have the workaround of applying `@NullMarked` to all other members of the class instead. And also, the bug is in a tool that doesn't support `@NullUnmarked` yet, anyway... :)

**Comment by netdpb** [comment]
**Current decision**: `@NullMarked` and `@NullUnmarked` cannot target fields because they do not enclose other nonlocal declarations. No compelling use case has emerged that requires such annotation targets. In any case, we could always add such target validity in the future, compatibly, if such a case is described.

**Argument for changing**: Fields do _kind of_ enclose their initializers, and so `@NullMarked` and `@NullUnmarked` could be used to mark local classes or type arguments within them. However, that is an infrequent case, and could be considered implementation-only and outside the required scope of JSpecify.

**Timing**: This must be decided before version 1.0 of the jar.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
Decision: `@NullMarked` and `@NullUnmarked` do not target fields.
