### ISSUE TITLE
Lingering @Implies spec questions

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#311]
This is highly related to #259 and #281 and others. I'm attempting a general formulation here that could help resolve those. But there is probably useful discussion hiding in those that is really about this.... pardon our mess...

This is somewhere between approximately what @cpovirk has been proposing and exactly what he's been proposing.

(As usual an annotation type `ImpliesXAndY` is assumed to itself be annotated with `@Implies({X.class, Y.class})`.)

The current `@Implies` javadoc defines essentially that `@ImpliesFoo` should be handled identically to `@ImpliesFoo @Foo`. But we need a more robust formulation than that.

### Option 1: prescriptive, reducible

* Once for each annotation in the direct annotation list, check for any implied classes, and if found add them to the annotation list, where they will also be processed in the same way (recursively). Continue until reaching the end of the list.
* Address provable conflicts:
   * If any two or more annotations in the list, of the same non-Repeatable type, have *any* attribute value specified on at least one of them, even if all values are identical, (see [#259](259) for specifics) and remove them from the list.
   * If we ever do [#279](279), many other conflicts could be addressed here
* Deduplicate what remains (including identical Repeatable annotations; differing attribute values would hold them apart)
* Now the information known about the annotated element is exactly as if the resulting annotation list had appeared directly.

("Reducible" in the header means that anything you can do this way is always also expressible directly without `@Implies`... ignoring details like visibility. It makes our feature just "syntactic sugar" and there's less potential mystery about behavior.)

### Option 2: flexible, exposes complexity

The annotation data associated with the element is considered to be the whole graph of all annotations present (with Implies links as edges). Each specific annotation type can define how it should be collapsed from this graph.

**Comment by kevinb9n** [comment]
I'm more or less "ethically opposed" to Option 2. It enables communicating usable information to tools that wouldn't have been expressible without `@Implies`. And it makes it hard to just have any mental model of what implies really does/means. Better to nail that down and make it simple, and if some annotation needs to be implyable in some other way it can do something special.

I'm comfortable making that call, especially since it would seem easier to generalize it to Option 2 in the future than to go the other way (but it's possible neither change would be okay).

**Any refinements to Option 1?**

**Comment by Mooninaut** [comment]
Is this a spec question or a library question? The title says spec but the body appears to be about a library implementation.

The spec should say what it means (or doesn't) if an annotation appears multiple times.

If this is about the utility library, I would think there would be a high-level API (Option 1) that exposes a clean (deduped, possibly canonically ordered if there's a canonical ordering) list of annotations, and a low-level API (Option 2) for the library's own use that exposes everything. Tools should use Option 1.

**Comment by kevinb9n** [comment]
> Is this a spec question or a library question? The title says spec but the body appears to be about a library implementation.

Spec only. My goal was to "reduce" the meaning of a usage down to "identical to *this set* of annotations", so I described how to determine that set algorithmically. It could perhaps be worded differently.

> There seems to be something missing, perhaps "issue a warning" immediately before "and remove them from the list".

The parenthetical is standing in for that. I'll clean it up later.


> Refinement: If annotations have a way to mark themselves as being mutually exclusive/contradictory, that processing could be done here.

Coincidentally I was editing that into the initial description of Option 1 around the same time you must have been saying that!
