### ISSUE TITLE
FAQ item on why we don't inherit `@Nullable` from a supermethod's return type

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#312]
https://github.com/jspecify/jspecify/issues/14 says some things, and the "self-contained files" item of [our requirements doc](https://docs.google.com/document/d/1d5NgP4Pjk_ahkISpRa3nFb1FzPz9yS9luByiBj6qCsk/edit) says some things. We could collect those things.

A Googler just asked about this, including asking how often an override _actually_ overrides a `@Nullable`-returning method with a `@NonNull`-return method. I confess that I don't have any examples ready at hand, aside from ones that aren't "really public API"—for example, how `ThreadFactory.newThread` has a `@Nullable` return type but most _implementations_ of that method don't. I suspect we could find at least a somewhat better example, while still acknowledging that the reasons here are mostly about the understandability of our model, not about the frequency of such methods.

**Comment by kevinb9n** [comment]
good idea, here you go:
https://docs.google.com/document/d/1H3TdqjRZQiGEP7ZePLpTnbYxj9s5hJAn9sp6eOiuj_c/edit#heading=h.rsvxffwgolm3

I didn't scrape the history for other arguments; these seemed enough to me. But edit at will!
