### ISSUE TITLE
What happens when a `@Repeatable` annotation is declared to imply a non-`@Repeatable` annotation?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#316]
(Somehow the _opposite_ case seems even more clearly like something that we would allow. But we could have an issue for that if we wanted.)

First, is that allowed, or do we reject the `@Implies` edge outright (perhaps treating it like one of the categories from https://github.com/jspecify/jspecify/issues/314#issuecomment-1302557230)? I guess it seems fine to allow?

If we allow it, and if the repeatable annotation is repeated somewhere, is that still fine? I guess I'd say that it is: Just as it's fine to have `@Foo @Bar` when both of those annotations imply `@Baz`, I'd expect it to be fine to have `@ImpliesBaz @ImpliesBaz`. `@Baz` would be deduplicated as part of the process discussed in #311.

Are there any real concerns here? I'm hoping not, but I hadn't thought about this at all before, so let's see if anything immediately comes to someone's mind.

**Comment by kevinb9n** [comment]
Nothing worries me about this if we're deduping.
