### ISSUE TITLE
What do we need to say about container annotations for `@Repeatable` annotations?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#317]
This question is perhaps easiest to understand from the perspective of "How would [our wrapper libraries](https://github.com/jspecify/jspecify/issues/220) expose them?" But there is probably more to it than that.

I want to say that Java (both in its runtime reflection APIs and in [its compile-time APIs](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/AnnotatedConstruct.html)\[*\]) exposes the `@Repeatable` annotation itself (for an isolated appearance) or the container (for multiple appearances). That's kind of weird, and I think it might have been forced by legacy considerations? If so, our wrapper libraries could perhaps simplify this, and that simplification could even serve as a small carrot to get projects to adopt those libraries. (But if our behavior were to differ from javac's, would that actually _complicate_ adoption for some projects?)

But the more interesting questions are probably around `@Implies`. I think any implementation of `@Implies` is going to be responsible for merging together individual `@Repeatable` annotations and any that are implied by a container:

```java
@Repeatable(Args.List.class)
@interface Args {
  String[] value default {};

  ...
}

@Implies(Args.class)
@interface NoArgs {}

@TestWithParameterizedArgs
@NoArgs // Tools will most naturally see this as implying an isolated appearance of `@Args`.
// The following two will be folded into an @Args.List before most tools see them:
@Args("0")
@Args("0", "1")
public void testSort() { ... }
```

From the perspective of what we have to officially define, it would be nice if this mostly came down to explaining that that merging takes place—that it's as if three `@Args` annotations are present. We could do that without getting into whether any are represented using `@Args.List` or not. Or maybe we _should_ get into that? I don't know what to think.

I also don't know what to think about the possibility that a container annotation might itself be annotated, including with any JSpecify meta-annotations that might be available, including JSpecify meta-annotations that might seemingly conflict with the meta-annotations on the "main" annotation. 

JLS [9.6.3](https://docs.oracle.com/javase/specs/jls/se19/html/jls-9.html#jls-9.6.3) and [9.7.5](https://docs.oracle.com/javase/specs/jls/se19/html/jls-9.html#jls-9.7.5) look like a glimpse into our future....

(After that, maybe there are also tips that we'll want to give tool authors. But hopefully many tool authors can rely on our libraries instead, and the question to us for those is how we design the API.)

\[*\] OK, there are also the `Tree`-based APIs inside javac. I don't think those get into container annotations. But that's because they're about, well, the syntax tree. I'm not sure if it would makes sense for us to provide a wrapper library at that level or not.

**Comment by kevinb9n** [comment]
Quick background: how repeated annotations work in the reflection API. Multiple are desugared to the container annotation; single is not.

```java
import java.lang.annotation.*;

class Issue317 {
  @Retention(RetentionPolicy.RUNTIME)
  @Repeatable(RaContainer.class)
  @interface Ra { int value(); }

  @Retention(RetentionPolicy.RUNTIME)
  @interface RaContainer { Ra[] value(); }

  @Ra(1)
  class One {}

  @Ra(2) @Ra(3)
  class Two {}

  @RaContainer({@Ra(2), @Ra(3)})
  class Three {}

  public static void main(String[] args) {
    assert  One.class.isAnnotationPresent(Ra.class);
    assert !One.class.isAnnotationPresent(RaContainer.class);

    assert !Two.class.isAnnotationPresent(Ra.class);
    assert  Two.class.isAnnotationPresent(RaContainer.class);

    assert !Three.class.isAnnotationPresent(Ra.class);
    assert  Three.class.isAnnotationPresent(RaContainer.class);
  }
}
```

**Comment by kevinb9n** [comment]
First I'd say that I'm not especially concerned about Actual Use Cases that really need one behavior or the other, here. This seems really ... fringe.

The ideal would be to treat `RaContainer` as much like an implementation-detail as possible. We could say that in all four cases `RaContainer`'s annotations are ignored and `Ra`'s annotations apply to the annotated element (they will, incidentally, be de-duped, per [#311](311)) . And just forget about the fact that that doesn't *technically* make sense for `Four`.

Probably, a nice checker would complain at any JSpecify annotations being placed on `RaContainer`. (Though, to even *know* it's a container requires checking `Ra` to make sure it points back to `RaContainer` in the expected way. Yuck!)
