### ISSUE TITLE
Do we guarantee anything about the ordering of annotations, mainly `@Repeatable` ones, across `@Implies`?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#318]
```java
@Repeatable(...)
@interface Foo {
  String[] value default {};
}

@Implies(Foo.class)
@interface Bar {}

@Bar @Foo("x") @Foo({"y", "z"}) String s;
```

Do we guarantee the order in which `@Foo`, `@Foo("x")`, and `@Foo({"y", "z"})` are considered to be present? And, if someone asks for "all the annotations," do we guarantee where `@Bar` fits into that?

I'm not sure if Java guarantees anything about the relative ordering of `@Bar` relative to the two directly present `@Foo` annotations. Even if it does, I'm not sure if it guarantees anything about the relative order annotations that are inherited, which is the closest match to `@Implies` that is part of Java (even if [we wouldn't necessarily follow any precedents that it sets](https://github.com/jspecify/jspecify/issues/315#issuecomment-1302649554)). I admit that I have not even looked.

Obvious candidates for things to guarantee or not guarantee includes:

- no guarantees on order at all
- guarantees that the relative order of directly present annotations does not change (so, e.g., `@Bar` is somewhere before the directly present `@Foo(...)` usages in the example above)
- guarantees that all directly present annotations appear consecutively
- guarantees of specific DFS/BFS behavior

**Comment by kevinb9n** [comment]
I think it's well-accepted that annotation ordering should not be relied on for any purpose; I think some style guides even ask that they be in lexical order, and/or some formatters might sort them.

So I think this should be an easy one.
