### ISSUE TITLE
How to release artifacts that smooth the package move

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#332]
> I'm assuming that we will not need to make a release that contains both old and new locations, because at the very worst, someone in transition could always just use both 0.2 and 0.3 jars at once. (!) Is that even right?

_Originally posted by @kevinb9n in https://github.com/jspecify/jspecify/issues/260#issuecomment-1314584664_
      
Then, in [email](https://groups.google.com/g/jspecify-dev/c/BcG5aAn22wQ):

> We should be able to publish 0.3.0-rc2 with these changes soon. I think we will have both old and new annotations together in that, in case that helps your transition. Then, -rc3 will have only the new ones.

**Comment by cpovirk** [comment]
I wouldn't necessarily assume that a project can easily depend on `org.jspecify:jspecify:0.2.0` and `org.jspecify:jspecify:0.3.0` at the same time. Maven, for example, will fight you on this, though apparently you can prevail through [awesomely terrible workarounds](https://stackoverflow.com/a/53280462/28465). I don't know what the story would be with other tools, like Gradle.

That suggests your newer approach of having both annotations together.

Alternatively, it suggests that we switch the Maven artifact ID, too, back to `org.jspecify:annotations`. That would also let people depend on both, conceivably even temporarily mixing 0.2.0 with some _future_ release like 1.0.0 (though I would hope that doesn't become necessary). And it would fit with the idea that we're "making room" for non-annotation artifacts in the future. (Previously: https://github.com/jspecify/jspecify/issues/181#issuecomment-1023703142.)

While we're at it, we could also switch the Java module back to `org.jspecify.annotations`. That would be for similar reasons (avoiding conflict, "making room").

This fits with the advice in https://jlbp.dev/JLBP-6. Not that we should feel bound by that for a lightly used, pre-1.0 artifact. Plus, any big adopters (including Google) may well have to do more during their transition than just take a jar or two no matter what.

I'd kind of lean that way: We've already muddied the Maven waters by publishing pre-1.0 artifacts under both `org.jspecify:jspecify` and `org.jspecify:annotations`, so we're not making things much worse in that regard. The biggest specific problem I can imagine is that someone might not be automatically notified of the available upgrade. But that seems like a minor concern.

**Comment by msridhar** [comment]
I think there will be many contexts in which depending on multiple versions of the same artifact will be very painful.  But I think I am missing some higher-level context here.  Why are we so concerned with not breaking version 0.2 users?  Is it due to significant internal adoption at some companies?

**Comment by msridhar** [comment]
Actually, one thing I forgot about is Kotlin / IntelliJ.  I guess that's a significant concern?  Even if you can rename imports in your own codebase for the new package structure, if the Kotlin compiler only recognizes the old packages, and its behavior depends on that, then you may be forced to continue using the old packages (or mixing?) until you can take on the relevant Kotlin update.

**Comment by kevinb9n** [comment]
I guess I mentally switched to the "we'll release one with both with a fast follow that drops the old ones" when I couldn't think of any down sides to doing it. That one release will be ugly, with @Deprecated and everything, but I dunno, what could it harm?

**Comment by msridhar** [comment]
> I guess I mentally switched to the "we'll release one with both with a fast follow that drops the old ones" when I couldn't think of any down sides to doing it. That one release will be ugly, with @deprecated and everything, but I dunno, what could it harm?

Completely reasonable, and I don't see any harm.  Just wanted to understand the context.

**Comment by lazaroclapp** [comment]
> I guess I mentally switched to the "we'll release one with both with a fast follow that drops the old ones" when I couldn't think of any down sides to doing it. That one release will be ugly, with @deprecated and everything, but I dunno, what could it harm?

Actually: Would IDE auto-import ever pick or list the "wrong" version of the annotation if both are included? That would be my only concern. Again, fixable for us with a search and replace once the deprecation goes through, but could still be confusing for some devs and _might_ cause issues for tools that understand only one path or the other.

**Comment by kevinb9n** [comment]
Oh, I think we can trust the IDE to either not show the deprecated one, show it crossed-out, or at least show the resulting code crossed-out.

**Comment by wmdietl** [comment]
> Another possibility is that a tool would like to have both packages of annotations on its classpath/processorpath during checking or at least when it runs tests. Besides you and some of the people I mentioned above, maybe @wmdietl can let us know if he anticipates trouble?

https://github.com/eisop/checker-framework/pull/364 adds support for the new package.
I don't see any build/test issues with the change.

**Comment by cpovirk** [comment]
Our previous release was "0.3.0-alpha-1." That suggests that our next release would be one of:

- 0.3.0-alpha-2
- 0.3.0-beta-1
- 0.3.0-rc1

In the discussion above, we'd been referring to "0.3.0-rc2." That would seem weird when there has been no rc1.

I doubt the name really matters much to anyone, so I guess I'll go with "0.3.0-rc1" in case some organization has a rule against depending on alpha/beta but no such rule against depending on release candidates, maybe? But if someone has a real reason to prefer one name, let me know. Otherwise, I'll go with "0.3.0-rc1" around this time on Monday.

**Comment by kevinb9n** [comment]
Oh, I was just mentally typo-ing it this whole time. alpha2 is what I would have said, and I think it would be best. This is only really for the benefit of anyone who's *already* using the alpha1, so company rules shouldn't affect this.

**Comment by cpovirk** [comment]
> This is only really for the benefit of anyone who's _already_ using the alpha1

I don't think that's true: Anyone who is using 0.2.0 could also benefit, since that release contains `@Nullable` and `@NullMarked` in the `org.jspecify.nullness` package. The API [changes in 0.3.0-alpha1](https://github.com/jspecify/jspecify/releases/tag/v0.3.0-alpha-1) were mainly the addition of `@NonNull`, `@NullUnmarked`, and `@Implies`.

**Comment by kevinb9n** [comment]
True, but... still?

**Comment by cpovirk** [comment]
I'm happy to amend my threat to "I'll go with '0.3.0-alpha-2' around this time on Monday" :)

**Comment by cpovirk** [comment]
https://github.com/jspecify/jspecify/releases/tag/v0.3.0-alpha-2
