### ISSUE TITLE
Declaring that one annotation aliases or specializes another (`@Implies`)

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#35]
A meta-annotation, used like:

```
@Implies(Nullable.class)
public @interface MyNullable { ... }
```

... which declares the annotated annotation to have all of the semantics of the linked annotation (plus optionally more).

This could make for easier migration, it could be used by things like `@PolyNull` so that the user doesn't have to redundantly write `@Nullable @PolyNull`, it could be used by a library that parallels ours to remove runtime retention, and perhaps other uses as well.

**Comment by artempyanykh** [comment]
In Nullsafe we use [@Nullsafe](https://github.com/facebook/infer/blob/master/infer/annotations/src/main/java/com/facebook/infer/annotation/Nullsafe.java) class-level annotation to
1. mark that the class is DefaultNonNull
2. allow users to configure certain aspects of checker's behaviour.

Annotation aliasing would be very helpful for us at least for the following reasons:
1. Help with interop between `@Nullsafe` Java classes and Kotlin code.
2. Make OSS FB libraries (that again use `@Nullsafe` classes) more friendly for the community.

Given that annotations currently present in the design are parameterless there's not much difference between
1. `@Implies`-annotation
```
@Implies({DefaultNonNull.class})
public @interface Nullsafe ...
```

2. Aliasing via application
```
@DefaultNonNull // alias
public @interface Nullsafe ...
```

No.1 is clearer, but No.2 (w/ a comment) is not too bad either, and added flexibility in allowing to specify arguments to aliased annotation seems to be a nice bonus.

---

> Notably it wouldn't be a complete solution, since there will be users who want to alias an annotation they don't own and the owner won't do it.

@kevinb9n this is somewhat restrictive, but I don't feel this is necessarily a *bad thing*. At the very least this prevents people from producing inconsistent aliases. In this (rather far-fetched) example I wouldn't like to be the person who depends on `MySuperAnnot` and both libA and libB if

libA:
```
@Nullable
public @interface MySuperAnnot ...
```

libB:
```
@NonNull
public @interface MySuperAnnot ...
```

---

@donnerpeter do I understand correctly that your concern with option No.2 (aliasing via application) is that it would require to scan all `@interface` declarations to build aliasing index compared to just uses of `@Implies` (but the resulting index size would be the same)?

**Comment by donnerpeter** [comment]
@artempyanykh It'd require to either scan all `@interface` declarations in all JVM languages, or all usages of `@NotNull`, or the intersection of these two sets (and do it after any change in the project, any typing).

I'm not sure which index you mean and what would be the same.

**Comment by artempyanykh** [comment]
@donnerpeter sorry, I have 0 experience in implementing IDEs, but want to understand better the situation, so please bear with me.

To support aliases in Infer, we would just lazily build a mapping from encountered annotations to their base jspecify analogues as we walk the CFG. Since this is a batch job, the overhead of this lookup would be low and there wouldn't be much difference between `@Implies(DefaultNonNull.class)`, `@DefaultNonNull public @interface MyAnnot`, or the combination.

Now in IDE this should happen incrementally, but I don't quite understand why the cost cannot be efficiently amortised.

For instance:

> ...and do it after any change in the project, any typing

Why would it need to be *any* typing? I'd assume it depends on the "context", so if someone is not editing annotation classes or changing annotations on elements there's no need to rebuild the index of aliases. Or am I missing something?

---

On related note, perhaps one aspect of `@TypeQualifierNickname` that I find questionable is its recursive nature. Theoretically, it allows for very flexible setups, but **I have found 0 usages of it both in our Android and server code**. This may very well be idiosyncratic to our codebase, so input from people with more sophisticated setups would be appreciated.

But anyhow, would it be easier to limit the scope of such annotation to be just a marker to simplify life of IDE implementers (if it's really needed) without the requirement to propagate annotations from an alias to annotations this alias is applied to?

So that when someone wants to alias some base annotation from jspecify they would need to write:
```java
import jspecify.nullability.DefaultNonNull
import jspecify.meta.Alias

@Alias
@DefaultNotNull
@Nullsafe { ... }
```

**Comment by donnerpeter** [comment]
> Why would it need to be any typing? I'd assume it depends on the "context", so if someone is not editing annotation classes or changing annotations on elements there's no need to rebuild the index of aliases. Or am I missing something?

You're right, in an ideal world that'd be so. Unfortunately it's too expensive to determine what an edit (or an update from version control, or a library jar change) could affect across the project, so, at least in IntelliJ, we drop most caches on any change, and try to be fast in recomputing them.

Non-recursive aliasing would indeed simplify the life of (our) IDE. But explicit marking seems much more important IMHO.

**Comment by kevinb9n** [comment]
I'm still not in a position to comment on the performance implications, but can only speak to my continued positive impressions of the benefits of the feature.

First, the topic of this comment is: what would it mean, exactly?

Assuming this simple usage:

```
@Implies(Foo.class)
public @interface Bar {}
```

And this generalized usage of our example annotation:

```
// elsewhere
@Bar /* some annotatable element here*/
```

`Implies` says that IF `@Foo` is also legal to appear in that context (by its target type):

```
// elsewhere
@Bar @Foo /* some annotatable element here*/
```

then these two snippets just above convey identical information; no meaning should be ascribed to the difference between them.

(Of course, checkers that want to issue a warning to the latter that `@Foo` can be safely removed would be welcome to, so that is a difference in behavior, but still not a difference in meaning.)

We would say that `@Bar` is a "specialization" or "refinement" of `@Foo`, and in fact `@Refines` and `@Specializes` are potential names for the annotation.

`Bar` may or may not add semantics of its own. If it does not, we may use the term "alias" to describe it, and its javadoc should presumably say nothing but "Alias for {@link Foo}". (We might wish in theory that the `@Implies` link could be made in both directions, but in real life we'd have to be content with just one.) In this alias scenario, each client codebase may have its own policy for which annotation's usage is preferred; it is probably not something that `@Bar` itself can define and thus not something `@Implies` would have anything to do with.

(The alias use case makes the name `@Implies` a little more attractive than `@Refines` or `@Specializes`, since the latter might subjectively be seen as suggesting more than the trivial refinement.)

All the above doesn't provide any solution for implying another annotation with particular attribute values; e.g. you can't define a `@Bar` that implies `@Foo("value here")`. However (a) many of these cases would want some "pass-through" of values anyway, which it's hard to see any way to accomplish, and (b) for the hardcoded no-pass-through case, `@Foo` could choose to enable that differently, by adding `@Target(ANNOTATION_TYPE)` and documenting it to have that meaning when applied to annotations.

(Aside: we've said we might offer small helper libraries for checker implementations or runtime/reflection code to use, if the need arises. A "does this element have this annotation on it" method that automatically traverses `@Implies` would be a simple example of this.)

**Comment by kevinb9n** [comment]
Now starting to get at why I feel this is important,

A thought experiment: if some codebase converts over to use our annotations completely, let's say that's what a 100% victory looks like for us. But what if it does not use our annotations at all, but it does use annotations that contain hard links via `@Implies` to ours?  Would we call that a 50% victory, or 80%, or 10%, or what?

imho, I think of it as like 90% victory. Because it can still be very concretely observed in the code that our semantics are the ones in play. 

If they use annotations that maybe mention ours in javadoc, that's kinda okay, except that that's going to serve no purpose until they go around configuring all their tools to say "please recognize our annotation as their annotation" (which would happen magically if we had `@Implies`). Of course, in the real world people will do that without even bothering to mention this in their annotations' javadoc, and from their pov, why should they?

**Comment by kevinb9n** [comment]
A few design points:

* `@Implies` still seems like a fine name to me
* It should take a `Class<? extends Annotation>` ... it will only be useful for marker annotations
* Possibly a `boolean isAlias() default false` might be useful, to signify that this class promises it adds no additional semantics and thus the two annotations are equivalent
* The specified annotation type should have all the target types the current annotation type has
* The Implies javadoc should warn that it's important for "all" code that checks for the presence of an annotation to do it using a method like <link> that takes Implies into account.

**Comment by cpovirk** [comment]
The ability to remove runtime retention is looking [even more important than I'd thought](https://github.com/jspecify/jspecify/issues/28#issuecomment-766955882), thanks to old versions of Android.

**Comment by cpovirk** [comment]
Earlier today, I noted [one way that we could end up with a nullness annotation and an alias for its _inverse_ in the same location](https://github.com/jspecify/jspecify/issues/34#issuecomment-767036960) (though presumably we'll work to avoid that).

This relates to an earlier possibility that has come up a few times -- namely, that we'd end up with a nullness annotation and another annotation that implies that _same_ annotation in the same location. Specifically, we've discussed that this could happen with `@PolyNull @Nullable` ([1](https://github.com/jspecify/jspecify/issues/35#issue-458279977), [2](https://github.com/jspecify/jspecify/issues/20#issue-397662562), [3](https://github.com/jspecify/jspecify/issues/2#issuecomment-433252330)). In theory, aliasing/implies should make that unnecessary: By declaring that `@PolyNull` implies `@Nullable`, we eliminate the need for `@Nullable`. On the other hand, I would anticipate that:

- Sometimes an annotation like `@PolyNull` will not have been updated that way (yet?), so people may want to use both. If so, it would be a little sad to have to remove `@Nullable` in lockstep with updating the definition of `@PolyNull`.
- Some tools will recognize any annotation named "Nullable" but not implement our aliasing/implies logic. Then again, I guess a solution here is to use `@PolyNull` for JSpecify tools and some _non-JSpecify_ annotation named "Nullable" on the same usage? But mixing in a non-JSpecify "Nullable" annotation is confusing and error-prone in its own way.

Anyway, this is all to say that aliases open up the possibility of writing `@Foo @NotFoo` or `@Foo @Foo` in indirect ways. We'll want to think that through.

**Comment by cpovirk** [comment]
Another thing to consider, especially if we embrace aliasing/implies as a broad solution to many problems:

A JSpecify checker can always recognize code with `@org.jspecify.annotations.Nullable` on it, even if that class isn't on the classpath.

(OK, it's possible that the implementation of a particular checker will in fact require that class to be present. But in principle, the checker _could_ work without the class definition. And if it _really_ wants the class definition to be present, then the checker (or at least its build-system integrations) can add that class to the classpath automatically.)

And that can be important, because people like to hide their annotation dependencies entirely from their users. This is (I have argued) [a bad idea](https://github.com/google/guava/issues/2824), but people do it because [Maven has no true compile-time-only scope](https://issues.apache.org/jira/browse/MNG-2205?focusedCommentId=16327595&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16327595).

But if code uses `@com.foo.MyNullable`, then the JSpecify checker _needs_ to see the definition of `@com.foo.MyNullable` in order to know that it implies `@org.jspecify.annotations.Nullable`.

One bit of good news is that, if we provide aliases _as part of JSpecify itself_ (e.g., for a `CLASS`-retention version of `@InTheClub`), then it's likely that (a) they will appear in most JSpecify users' classpaths or at least (b) JSpecify-based tools can hardcode knowledge of those annotations for the case in which they're not in the classpath.

**Comment by cpovirk** [comment]
As far as I can tell, javac _itself_ at least doesn't mind usages of an annotation whose declaration has `@Implies(SomeClassNotOnTheClasspath.class)`. That's the case even though [it _does_ mind usages of an annotation whose declaration has `@Target(SOME_ENUM_VALUE_NOT_ON_THE_CLASSPATH)`](https://github.com/jspecify/jspecify/issues/50#issuecomment-520468335). (Caveat about that latter problem: I don't know if it's specific to `@Target` (since javac cares specifically about that) or more general. It would be easy enough to test.)

```
$ tail -n +1 *.java
==> Implies.java <==
@interface Implies {
  Class<? extends java.lang.annotation.Annotation> value();
}

==> JSpecifyNullable.java <==
@interface JSpecifyNullable {}

==> OtherNullable.java <==
@Implies(JSpecifyNullable.class)
@interface OtherNullable {}

==> User.java <==
@OtherNullable
class User {}

$ javac -sourcepath none Implies.java JSpecifyNullable.java OtherNullable.java && mkdir othernullableonly && cp OtherNullable.class othernullableonly && javac -sourcepath none -cp othernullableonly User.java
<no errors or warnings>
```

**Comment by cpovirk** [comment]
RE: (1):

An impression that I got (which may or may not be accurate) is that part of the reason we're here is that at least one tool vendor (Kotlin) is trying to avoid adding nullness annotations to its list and also avoid exposing arbitrary configuration abilities to users. Maybe we can run that by someone from Kotlin to see if it's accurate?

Aside from Kotlin, my impression is indeed that most tools will let you specify which annotations to recognize, or they'll recognize anything with the simple name "Nullable."

**Comment by kevinb9n** [comment]
> I wonder if we can decide among a few options for moving forward here for 1.0.
> 
> 1. Maybe **1.0 doesn't need any `@Implies` annotation at all.** Each checker tool has a way to configure aliases already. For libraries that want to be used by clients who use any tool, it behooves them to change their annotations to the JSpecify ones. For users who are committed to a specific tool, they can configure it however it expects to recognize the aliases it wants to.

(To express this decision we would move all Implies-related issues to the post-1.0 milestone.)

> 2. **1.0 needs to support a common use case for aliasing the JSpecify nullness annotations,** but we can decide not to support more complex annotations (such as those with parameters) or more complex relationships besides simple implication (such as refinement or implies-except) for now because we believe we have a reasonable path toward supporting those more complex use cases in a later release without breaking existing users.
> 3. **1.0 has to support more general use cases,** such as those described above, because we do not believe we can support only the common use case first without precluding support for the more complex ones later.

And 2-vs-3 breaks down like this by feature:

* Parameters: absolutely, assume we will say/do nothing about this case. Separately, #218 argues for a simple solution.
* Refinement: I don't think refinement is a special case, it's just generally how this works. Did I misunderstand anything?
* Alias: the ability to mark an annotation as being a *pure* alias (non-refinement?) is an optional feature, with some value, that is NOT part of this and is fine to file separately, because `isAlias=false` would be the default anyway.
* Implies-except: this is about precedence rules when a conflict is found, and we have to have _some_ decision on it (#216)
* Imply-multiple: assume no, because #213 tracks that.

**Comment by sdeleuze** [comment]
As discussed with @kevinb9n recently, and as described in [this old but still relevant comment](https://github.com/jspecify/jspecify/issues/35#issuecomment-530733459), `@Implies` support is mandatory for Spring Framework 6 adopting jSpecify.

**Comment by kevinb9n** [comment]
Appreciate you reasserting this. It may seem like it should be unnecessary to repeat, but it really does help. Will address in meeting and update here.

**Comment by kevinb9n** [comment]
We have made a working decision to include this for 0.3. This will help us discover any serious problems with it before 1.0.

**Comment by netdpb** [comment]
The current, working decision, as of release 0.3, is that JSpecify 1.0 will not include a general specification of one annotation implying another.

Although this use case is important to large library providers such as Spring Framework (see #307 for further discussion), its requirements are also quite complex. We won't delay 1.0 for this use case, but we should figure out what to do after 1.0.

**I propose the current decision be finalized for 1.0.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by sdeleuze** [comment]
I won't thumb-down this one, as I think it is great that 1.0 with current scope is released asap and I am not sure we need a mechanism as general/complex as `@Implies`, but I want to express (again) that the lack of meta-annotation/alias capability is a blocker for Spring Framework usage of JSpecify, so my ask would be to plan that feature for 1.1 and treat it as high priority after 1.0 release.

Could be as simple as supporting annotating Spring null-safety annotation with JSpecify ones (I understand there are performances implications for checkers, but IMO this is doable, we are talking about build-time tooling, not runtime analysis).

**Comment by kevinb9n** [comment]
New proposal: https://docs.google.com/document/d/19Z7Ep2zBRpeKu17JNXOGhcZziGiAsz-CGkNTq7hHXoI/edit
