### ISSUE TITLE
Decide whether and how to specify interpretation of other nullness annotations besides our own

### ISSUE THREAD

**Issue by wmdietlGC** [jspecify/jspecify#37]
I'm working through how our `@LegacyNullness` annotation would work (naming discussion see #32). In particular in the context of generics, #19, I wasn't quite sure when `legacy parametricity` should apply. But this seems like a general topic we need to discuss.

For clarity, I'll use `@305XXX` and `@CAAXXX` with `XXX` being either `NotNull` or `@Nullable`, where the `305` version stands for any of the many existing nullness annotations.

Let's say we come across some bytecode, corresponding to:

```java
class C {
  Object fNone() ...
  @305NotNull f305NN() ...
  @CAANotNull fCAANN() ...
  @305Nullable f305Nbl() ...
  @CAANullable fCAANbl() ...
}
```

And no particular default applies to the class.

We currently have no mechanism to decide how this bytecode was generated.
So what is the nullness-augmented signature for this class?

```java
class C {
  @LegacyNullable Object fNone() ...
  @??? f305NN() ...
  @CAANotNull fCAANN() ...
  @CAANullable f305Nbl() ...
  @CAANullable fCAANbl() ...
}
```

For `fNone` we don't have any annotations, so we use `@LegacyNullable`.

For `fCAANN()` we have a CAA not-null annotation and we trust it. Similarly for `fCAANbl`.

For `f305Nbl` we have a legacy nullness annotation and it would seem safe to map that to `@CAANullable` instead of `@LegacyNullness`.

However, what should be the signature for `f305NN`? The bytecode uses a legacy not-null annotation, but we have no reason to trust the annotation.
Some options:
1. treat it like `@LegacyNullable`, completely ignoring legacy not-null annotations
2. treat it like `@CAANotNull`, blindly trusting existing not-null annotations
3. add a separate `@LegacyNotNull` to distinguish the cases.

Option 1. seems inconvenient, forcing all users to switch what nullness annotations they use.

Option 2. on the other hand might be dangerous, because the legacy not-null annotation might not have been checked.

Option 3. would require yet another annotation and deciding how it would be handled differently.

Are there other options?

**Comment by kevinb9n** [comment]
I believe it has been our plan for a while that our specifications say nothing about anyone else's annotations, only our own. #35 discusses how other annotations could be marked as aliases/refined versions of ours.
