### ISSUE TITLE
Confirming understanding of null marked generics

### ISSUE THREAD

**Issue by bowbahdoe** [jspecify/jspecify#390]
Just trying to make sure I understand whats going on.

So in a `@NullMarked` context, every generic parameter means "non-null T".

```java
interface JsonDecoder<T> {
     T decode(Json json);
}
```

So this interface means that `JsonDecoder` only works on `T`s that are non-null. To make it compatibile with null I need to put a bound on `T`.

```java
interface JsonDecoder<T extends @Nullable Object> {
     T decode(Json json);
}
```

Which means that it could be a type which includes null or it might not. 

If I were to say `@Nullable` on the `T` itself that would mean the generic parameter always has to allow null?

```java
interface JsonDecoder<@Nullable T> {
     T decode(Json json);
}
```

So this method is how i would denote "maybe null type"

```java
    static <T extends @Nullable Object> T null_(Json json, T value) throws JsonDecodeException {
        if (!(json instanceof JsonNull)) {
            throw JsonDecodeException.of(
                    "expected null",
                    json
            );
        } else {
            return value;
        }
    }
```

And this is how I would denote "has to be a nullable type"?

```java
    static <@Nullable T> T null_(Json json) throws JsonDecodeException {
        if (!(json instanceof JsonNull)) {
            throw JsonDecodeException.of(
                    "expected null",
                    json
            );
        } else {
            return null;
        }
    }
```

Or for that last one is it

```java
    static <T> @Nullable T null_(Json json) throws JsonDecodeException {
        if (!(json instanceof JsonNull)) {
            throw JsonDecodeException.of(
                    "expected null",
                    json
            );
        } else {
            return null;
        }
    }
```

**Comment by kevinb9n** [comment]
(To add: if we do ever want to support this "definitely-nullable type parameter" we would very likely do it with some different annotation besides `@Nullable` anyway.)

**Comment by cpovirk** [comment]
And since that post popped this thread to the top of my inbox, I realize that I can now mention https://errorprone.info/bugpattern/NullableTypeParameter, one of a few new nullness-related checks in https://github.com/google/error-prone/releases/tag/v2.24.0. It's only a warning, and not everyone uses Error Prone, so the problem isn't "solved." But we did do that thing that I said we should do back in August, yay :)
