### ISSUE TITLE
Accommodate users of well-known effectively-co(ntra)variant types who don't use wildcards?

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#40]
Code accepting a `Supplier<Foo>` and `Predicate<Bar>` should basically always accept `Supplier<? extends Foo>` and `Predicate<? super Bar>` instead. This is well-plumbed territory (see EJ3e Item 31), and as far as we are concerned, it's non-controversial:  you can avoid the wildcard if you want, but you're going to have a bad time *with or without us* and we won't feel sorry for you. (We'll continue to dream of declaration-site variance in a future version of Java.)

Fortunately our nullness annotations seem to intersect pretty sanely with these wildcards - they basically do what you would want them to do. But what of the users who don't want to use them?

We may want to think about what checkers should do in these cases, so we can consider what boundaries we may want to place on what a compliant checker can do.

1. Do nothing to accommodate this case

2. Or be lenient about assigning in either direction between `Abc<@NotNull Xyz>` and `Abc<@Nullable Xyz>`, though this may be a sizable hole in the safety net

3. Or actually maintain special knowledge of common types that are known to be effective co(ntra)variant, and use that knowledge accordingly for our purposes.

I personally favor 1.

**Comment by cpovirk** [comment]
I don't think we've noted yet the the Checker Framework `@Covariant` is surprisingly lightly used so far: It's currently only `Class`, `Constructor`, and `Optional` -- the ["nothing to do with nullness"](https://github.com/jspecify/jspecify/issues/78) classes.

But some more on CF usage:

- There used to also be [one mistaken usage](https://github.com/typetools/checker-framework/pull/3278).
- There's [a "phantom usage" in `Iterator`](https://github.com/typetools/jdk/blob/959a7a11335c4e425f13caef2df831306e9274b1/src/java.base/share/classes/java/util/Iterator.java#L64) that I'm going to look into.
- There are other places (like those mentioned in this thread) where `@Covariant` would make sense (see also https://github.com/typetools/checker-framework/issues/1444). And in fact someone just raised the possibility of annotating `Supplier` inside Google, so I'm going to raise that on the CF project.

**Comment by cpovirk** [comment]
> - There's [a "phantom usage" in `Iterator`](https://github.com/typetools/jdk/blob/959a7a11335c4e425f13caef2df831306e9274b1/src/java.base/share/classes/java/util/Iterator.java#L64) that I'm going to look into.

Apologies: I was looking at my local copy, in which I removed the annotation as a test. As you can see from the link I provided, `Iterator` has `@Covariant`.

**Comment by cpovirk** [comment]
(more `@Covariant` annotations possibly coming to the Checker Framework in https://github.com/typetools/jdk/pulls?q=is%3Apr number 51 (not linking directly to avoid drawing people here accidentally))

**Comment by kevinb9n** [comment]
Just a reminder that issue #72 is about the benefits of capturing variance with annotations and what benefits it would intrinsically bring, and this issue is phrased as being specifically about whether we would use that information to let users "cheat" (so to speak) on their wildcard usage.

**Comment by cpovirk** [comment]
Sorry, I got confused trying to differentiate the two. Possibly I convinced myself that #72 couldn't be about this because "types are covariant, not type parameters" and #72 talks about type parameters? And I guess that's part of the reason you use `@In` and `@Out` rather than `@Covariant` and `@Contravariant` :)

**Comment by kevinb9n** [comment]
("Types are covariant, not type parameters" is just an accident of grammar? We say "Function<F, T> is covariant on T",  but this demonstrates that it's just a property of T itself. AFAICT that property, "used-covariantly", could be spelled "covariant" without causing any actual confusion.)

I think we can rule out the idea that JSpecify would somehow reference some list of "well-known" cov/contrav types. Our nature is instead that we will either have something like #72 or we won't.

It's weird (today) that in null-marked scope we have to turn `void foo(Predicate<Object>)` into `void foo(Predicate<? super Object>)` when foo needs it to accept null. But it does "teach a correct lesson", a couple really, so it may be desirable.

**Comment by kevinb9n** [comment]
> inferring covariance/contravariance worries me a little, given the existence of seemingly covariant `Iterable`.

Concepts: I think it works to say that `Iterable` as a type *is* covariant, plain and simple. Final types and runtime types can have "strong covariance". The fact that `Collection` is not covariant opens the door to the problem you're alluding to, and downcasts *are* the problem. Collection itself and the downcasts all deserve warnings.

**Comment by kevinb9n** [comment]
> I think we can rule out the idea that JSpecify would somehow reference some list of "well-known" cov/contrav types. Our nature is instead that we will either have something like #72 or we won't.

This makes the current issue closable. A fix for #72 will have to explore the implications for nullness already.

**Comment by netdpb** [comment]
The current, working decision, as of 2022-03-21, is that in general, JSpecify should not require tools to assume special things about specific types, even JDK types. We plan to provide annotation overlays for the JDK eventually.

The best argument made to change this decision is that most users of `Predicate<Foo>` really mean `Predicate<? super Foo>`. This is more acute in cases like `Predicate<Object>`, where in null-unmarked code there's no proper supertype, but in null-marked code there is (`@Nullable Object`). To make it easier for users, JSpecify should require tools to assume the wildcard in those cases.

However, none of the discussion above has made a strong case for making special cases for "well-known" types.

**I propose the current decision be finalized for 1.0.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: JSpecify does not require tools to assume special things about specific types, even JDK types.
