### ISSUE TITLE
`Optional`: `T orElseGet(Supplier<T>)` or `@Nullable T orElseGet(Supplier<@Nullable T>)`?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#425]
(brain dump, sorry)

Currently, we [have `T orElseGet(Supplier<T>)`](https://github.com/jspecify/jdk/blob/f206ad5fc3b5b0d5ba7b5ed6d4c87d3012acec84/src/java.base/share/classes/java/util/Optional.java#L376).

That's much more convenient for almost all callers because the return type is non-nullable.

But it "prevents" (to varying degrees) callers from legitimately returning `null`. A search of Google's codebase for `orElseGet.*\bnull\b` turns up more results than I feel like sifting through right now, but it does turn up `.orElseGet(() -> someOtherOptional().orElse(null)))`. In fairness, that could be changed to `.or(() -> someOtherOptional()).orElse(null))`. But as it currently stands, I'd expect it to become a (suppressible) nullness error when we roll out more nullness checking.

\[edit: I came back and looked through some results for `^[^*\042]*orElseGet[^\042]*\bnull\b
^[^*\042]*orElseGet[^\042]*\bnull\b`. A lot of them use `orElse(null)` similar to above, and a surprising number are simply `orElseGet(() -> null)`. While those aren't super-compelling, I don't think it would be any more super-compelling to give those people warnings/errors, even suppressible ones.\]

One bit of good news is that Kotlin users can use [`getOrElse`](https://github.com/JetBrains/kotlin/blob/0938b46726b9c6938df309098316ce741815bb55/libraries/stdlib/jdk8/src/kotlin/jvm/optionals/Optionals.kt#L29), which not only automatically returns the correct nullness but also lets you return a more general type than the initial `Optional` (e.g., `optionalNumber.getOrElse { defaultDouble() }`, though of course you'd likely just use `orElse`/[`getOrDefault`](https://github.com/JetBrains/kotlin/blob/0938b46726b9c6938df309098316ce741815bb55/libraries/stdlib/jdk8/src/kotlin/jvm/optionals/Optionals.kt#L22) in that case). So we don't need to worry _as_ much that "Kotlin users will be stuck with a bad return type" or "Kotlin users can't return `null`." (Admittedly, some users won't find `getOrElse`, so they'll be "stuck" with whatever behavior we pick for `orElseGet`.)

Our position for the very similar (and much more commonly used) `orElse` was that it clearly needed to be `@Nullable T`. It turned out that we could easily modify our prototype checker to understand that a nullable parameter implied a nullable return type. That is probably harder to do when the `@Nullable T` appears inside "`Supplier<@Nullable T>`," but I have to imagine that it's doable if we care enough.

Naturally, this is a textbook use case for [`@PolyNull`](https://github.com/jspecify/jspecify/issues/79).

I think we'd clearly use `@Nullable` if we could convince ourselves that users wouldn't start seeing lots more errors from their checkers. Even if it _did_ lead to lots more errors, we would probably _still_ use `@Nullable` if we saw enough users who legitimately wanted to return `null`.

I do still want to stand up for the idea that it can _maybe_ be OK to pick an "overly" restrictive type. For example, [`Collectors.toMap`](https://github.com/jspecify/jdk/blob/f206ad5fc3b5b0d5ba7b5ed6d4c87d3012acec84/src/java.base/share/classes/java/util/stream/Collectors.java#L1565-L1567) takes a `BinaryOperator` that is allowed to return `null` (to tell the `Collector` to remove the corresponding key). However, the only way to annotate it to allow that has the effect of also allowing the _inputs_ to the `BinaryOperator` to be `null`. This complicates almost every implementation that people use in practice (e.g., `Integer::sum`). Now, `@Nullable` might _still_ be the right choice there, too. (Or there might be [another solution](https://github.com/google/guava/issues/6824#issuecomment-1799740219)!) I am just simultaneously pushing the idea that annotations are a design choice _and_ the idea that the right choice is almost always the type that's general enough to admit all users :)

**Comment by kevinb9n** [comment]
So: `@PolyNull` is the "right" answer, and that absent that, `@Nullable`/`@Nullable` is the most correct, and our main concern is just the annoyance that is characteristic of any "shoulda-been-polynull" case?

I would be inclined to live with that annoyance and let it contribute to the overall argument for `@PolyNull`.
