### ISSUE TITLE
Choose non-null annotation name

### ISSUE THREAD

**Issue by donnerpeter** [jspecify/jspecify#44]
I'm used to `@NotNull`, but the other two variants might be slightly more grammatical, I'm not sure though.

**Comment by kevinb9n** [comment]
Just a minor note that if #230 goes yes, there is some _slight_ potential to find a substantially different name that better suggests "this isn't the useful thing you imagine it is", and that could reopen this.

I'd moderately insist we never go back to non-vs-not though :-)

**Comment by netdpb** [comment]
The current, working decision, as of rel;ease 0.3, is that the annotation is named `@NonNull`.

This issue must be finalized before the release of version 1.0 of the annotation JAR.

We have indicated an extremely strong bias against introducing new compilation-breaking changes after 0.3. Nobody has made a strong case for changing that name.

**I propose this decision be finalized for 1.0.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and _briefly_ explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: The annotation is named `@NonNull`.
