### ISSUE TITLE
Strangeness with generics and callbacks.

### ISSUE THREAD

**Issue by bowbahdoe** [jspecify/jspecify#440]
I will confess i am not running the reference checker, so IDK if this is just intellij's implementation or i'm misunderstanding the nullness rules.

code in question is here https://github.com/bowbahdoe/json

<img width="1134" alt="image" src="https://github.com/jspecify/jspecify/assets/5004262/4ed87467-6784-4fd4-a10c-b6b15df091d6">

Where the method at issue appears to be here

```java
    static <T extends @Nullable Object> T field(
            Json json,
            String fieldName,
            JsonDecoder<? extends T> valueDecoder
    ) throws JsonDecodeException {
```

My read was that this is a method which accepts any type, including nullable types, but if the decoder didn't admit null as a possible return value that the result shouldn't either.

More relevant code

```java
public interface JsonDecoder<T extends @Nullable Object> {
    T decode(Json json) throws JsonDecodeException;
```

```java
    static int int_(Json json) throws JsonDecodeException {
```

Is this a consequence of some unification rules? Like

`T extends @Nullable Object`, `? extends T` where `T` == `Integer` still sees `@Nullable Integer` as a valid super-type?

**Comment by agentgt** [comment]
For most frameworks you need to use the type witness notation because it can't properly deduce from the left hand.

I did not test your case on IntelliJ but Eclipse null analysis will do the same thing.

To fix it you would do something like:

```
JsonDecoder.<Integer>field(....);
```

**Comment by agentgt** [comment]
Yes but intellij null analysis isn’t really type based last time I checked. 

Eclipse and Checker are. Try those guys.

Check out this action I use that tests with both: https://github.com/jstachio/jstachio/actions/workflows/analyze.yml

**Comment by cpovirk** [comment]
Your understanding of the meaning of the code looks correct to me, as well. I, too, would expect the Checker Framework and our reference checker to get this correct (though no guarantees :)), likely including without the explicit type argument. I haven't used Eclipse enough to predict how it would behave, but I would not be surprised to see it work, either.

While IntelliJ (IIRC) can understand generics in some case (e.g., `Future<@Nullable String>.get()`, maybe?), this looks like a case I remember from testing IntelliJ on Guava: It's been a few years, but I think I was seeing `T extends @Nullable Object` lead IntelilJ to treat all usages of `T` as if they might be nullable, without regard to substitution.

The IntelliJ folks fixed some of the problems we reported with Guava. But given that Guava is a much heavier user of generics than the average project, they didn't try to deal with everything that came up frequently for us. (Not to mention that full handling of generics is quite a pain to implement.)

I'd encourage you to [file an IntelliJ bug](https://youtrack.jetbrains.com/newIssue?project=IDEA). Even if it doesn't get a quick fix, it should help to start establishing how often "real users" encounter some of the remaining issues in IntelliJ's support.

**Comment by bowbahdoe** [comment]
👍 https://youtrack.jetbrains.com/issue/IDEA-341808/T-extends-Nullable-Object-should-not-always-be-treated-as-nullable.

**Comment by agentgt** [comment]
I agree with @cpovirk . Ironically given how well IntelliJ does so many other things I have found it to be lacking on null analysis when it comes to generics and when I went code diving trying to figure out how it worked it appears to be far different than the others.

When I have run into this issue usually with Streams is that Checker is the only one that seems to get it consistently right but I'm haven't been using the reference checker lately.

Eclipse needs the type witness notation for some reason that I think Stephan explained to me in  a chat room once. I will check with them after the holidays to find out why or what is the limitations.

Across my projects I plan on adding null analysis using each tool in my CI pipeline. I am currently missing IntelliJ (I just found out last year you can run its check stuff headless), and JSpecify reference checker. My hope is to somehow codify it into a Github action (one for maven and one for gradle... might not even just be put this Maven profile in your script etc) for library authors to quickly play with the various frameworks and to find inconsistencies.

**Comment by kevinb9n** [comment]
Is this issue closeable now?
