### ISSUE TITLE
Generalized contract language expressed in a single `@Contract("...")` annotation, like IntelliJ supports

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#454]
Our future roadmap talks about annotations covering a variety of contractual expressions like must-close-resource, may-ignore-result, param-must-be-constant, etc.

It's worth asking whether a single annotation could accept an expression in a generalized contract language that enables all these behaviors to be expressed. Of course, IntelliJ has something of this nature, and of course, this language would grow to encompass a _lot_ more expressions, like int ranges and the whole deal. It would be more expressive/powerful by leaps and bounds.

**Comment by kevinb9n** [comment]
A few observations:

* our particular design projects may just translate into design projects for the contract language itself, and we saved little effort

* my feeling so far is that each of these different problem domains may call for subtly different approaches that wouldn't lend themselves well to a single annotation, such as differences in how inheritance, overriding, containment, etc. function. I don't know this, but my point is we _won't_ know it until we've designed a few.

The tenor of the discussions we've had so far have seemed to be "we're happy for some other project to tackle this". Of course it would be important that the two interoperate to the extent they overlap.

**Comment by kevinb9n** [comment]
I would even suggest this is farfetched enough that we should mark this closed?

**Comment by Mooninaut** [comment]
I think there's some value in defining a DSL for the semantics of JSpecify (and potentially other) annotations, which would probably live outside of Java source code entirely. `@Contract` is its own thing, that JSpecify could potentially draw inspiration from, but it's a different approach.

**Comment by kevinb9n** [comment]
Noted.

Given our current firm impression of our own scope I'm closing this as being firmly outside it.
