### ISSUE TITLE
Documentation for code authors

### ISSUE THREAD

**Issue by netdpb** [jspecify/jspecify#457]
Include advice for whether you should start adding these annotations to your code.

Specific documentation for:
- Authors whose code has no preexisting nullness annotations
- Authors whose code has other nullness annotations whose semantics are not enforced by any tool
- Authors whose code has other nullness annotations whose semantics are enforced by specific tools, including some subset of:
   - FindBugs/SpotBugs
   - NullAway
   - Checker Framework
   - IntelliJ

May include updating https://github.com/jspecify/jspecify/wiki/adoption, or replacing that with one or more documents.

**Comment by cpovirk** [comment]
One thing to address here is the idea of "sprinkling" annotations into code that is not `@NullMarked`. This can apply for code that already has non-JSpecify annotations sprinkled in it, or sprinkling can be a first step for a project that currently has no annotations.

Background: We got some feedback that the current User Guide suggests that `@Nullable` is valid only within `@NullMarked` code. This may have been based on the phrasing:

> JSpecify includes a `@NullMarked` annotation. In code covered by that annotation, `String x` means "`x` is a reference to a string object", and `@Nullable String x` means "`x` is either null or a reference to a string object"

**Comment by netdpb** [comment]
This is written in the docs-1.0 branch, which we'll merge into main soon.
