### ISSUE TITLE
Reassigning a non-null parameter with a nullable expression? [working decision: expect a finding]

### ISSUE THREAD

**Issue by donnerpeter** [jspecify/jspecify#48]
Imagine a method:

    void printHierarchy(@NotNull Element e) {
      while (e != null) {
        System.out.println(e);
        e = e.getParent();
      }
    }

Note that notnull parameter is reassigned, eventually to null. Should this be allowed? Whatever we choose, it probably should apply to local variables as well. I see 3 alternatives:
1. Disallow this, since it's assigning null into a non-null variable.
2. Allow this and say that `@NotNull` only applies to the argument passed into the parameter. In the case of local variable, to its initializer.
3. Leave it to be checker-dependent, e.g. since it's not exactly about signatures.

Kotlin disallows such code. IntelliJ also did, but after many complaints we started to support this, because apparently it's a relatively frequent pattern, and it's too convenient to write loops this way.

**Comment by kevinb9n** [comment]
I'm reopening this -- in light of our newer more optimistic approach toward imp code (see #252 and #261 for instance), we should try to come to agreement, and then wield the "undefined" hammer when there are legitimate conflicts between different tools' interests.

I think I agree with @stephan-herrmann. I don't see how we can teach users that a parameter type is non-null while the variable that is the very same thing as that parameter is nullable. Either that type is nullness-applicable or it isn't!

```
void foo(@NonNull String s) {
  s = doesNotExcludeNull(); // I expect a finding here
}

@NullMarked void bar(String s) {
  s = doesNotExcludeNull(); // expect finding here
  try {
    ...
  } catch (QuxException e) {
    e = doesNotExcludeNull(); // expect finding here
  }
}
```

This does have a slight hazard. A parameter might be made nullable though it doesn't actually want to accept null, only because the impl is reassigning that variable to null and say the user doesn't want to change the implementation yet. I can live with this.

**Comment by kevinb9n** [comment]
Working decision: yes, finding expected.

In @stephan-herrmann 's example code:

```java
void foo(@NonNull Element el) {
    // many lines omitted
    el = dubious();
    // many more lines omitted
    el.print(); // warning here, WHAT?
}
```

There's going to be a finding in one place or another anyway, and I agree that `dubious()` is the better place for it.

While inside a method/constr body a parameter acts a lot like a local variable, these are still one and the same thing. So its treatment by nullness analysis is governed by its "parameterness" and parameter types are nullness-applicable. Our special local-variable-root-types exception is for real local variables.

**Comment by netdpb** [comment]
**Current decision**: A non-null parameter should not be reassignable to a nullable type. In general, JSpecify doesn't require tools to report particular findings. But we will require that tools be able to tell when this happens in conformance tests.

**Argument for changing**: None

**Timing**: This must be decided before version 1.0 of the spec.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by kevinb9n** [comment]
I've just added an argument for changing. I haven't thought super deeply about it yet.

**Comment by netdpb** [comment]
**Current decision**: A non-null parameter should not be reassignable to a nullable type. In general, JSpecify doesn't require tools to report particular findings. But we will require that tools be able to tell when this happens in conformance tests.
