### ISSUE TITLE
Document the package name in the User Guide and perhaps landing page

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#524]
...perhaps alongside [the Maven coordinates](https://github.com/jspecify/jspecify/issues/503).

**Comment by netdpb** [comment]
What do you mean by "landing page"? https://jspecify.dev/ or [start-here](https://jspecify.dev/docs/start-here)?

**Comment by cpovirk** [comment]
Hmm, good question. Probably start-here?

**Comment by cpovirk** [comment]
I don't _think_ the User Guide changes covered this one, right?

**Comment by netdpb** [comment]
I had a note in the commit that it _might have_ closed this, and GitHub leapt to that conclusion.

**Comment by cpovirk** [comment]
Oops, now I'm reading the PR comment :)

> Now that the annotations are all linked to Javadoc, this might be sufficient to close #524 as well, at least with respect to the User Guide.

I'd still be inclined to keep this open as a reminder for me to cover it when I take care of the build-system issues, but if I fail, I don't think we need to block 1.0 over it.
