### ISSUE TITLE
Which buildtool and CI we prefer?

### ISSUE THREAD

**Issue by KengoTODA** [jspecify/jspecify#54]
Current `master` branch has no `pom.xml`, `build.gradle` nor `build.xml` then I want to make some of them to ease coming works. My suggestion is [Gradle with Spotless and Errorprone](https://github.com/google/codeanalysis-annotations/commit/97e7b7c9a06c6e72ae5f98007f2c932bc1fff5cb), let's have a talk to make our daily hack great.

I also want to introduce CI such as Travis CI and Circle CI, but I think that we have some limitation while this repository is private... is it better to wait until we publish it?

**Comment by cpovirk** [comment]
I am checking whether we are waiting on any more approvals before starting work under Apache 2.0. I am hopeful that we'd be able to take a PR for a build setup soon.

As far as which _tool_ to use for builds, I would look at this similarly to which tool to use for documentation (#99): Unless someone has strong objections, I am happy to use whichever tool someone is willing to set up :) So Gradle SGTM.

**Comment by JakeWharton** [comment]
GitHub actions for CI would be my recommendation. We can also use GitHub packages for hosting snapshots of the artifacts. GitHub pages can host the static files as produced by the documentation tool and an action can trivially push to those pages automatically.

**Comment by KengoTODA** [comment]
Thanks for your reaction! GitHub Actions is [already working for documentation](https://github.com/jspecify/jspecify/blob/master/.github/workflows/docs.yml), and it's also easy to use to deploy SNAPSHOT or stable release to GitHub Packages and/or Maven Central.

About the Gradle, I have [some related works in this branch](https://github.com/jspecify/jspecify/tree/add-annotation-impl), however, the final package name isn't fixed so I cannot propose a PR to build. I'll keep waiting for #1.

**Comment by cpovirk** [comment]
Excellent :)

I can't speak for everyone, but I would encourage you to submit a PR for us to merge even before the package names are finalized. I would encourage a package name like `org.jspecify.experimentaldonotuse` to continue to make clear that the name of the package (like the names of the annotations themselves, especially [`@NullnessAnnotated`](https://github.com/jspecify/jspecify/issues/87#issuecomment-574879103)) has not been finalized.

Our current tentative plan is to make an "internal release" with just enough functionality for tool owners to experiment with implementation and, ideally, for some of their users to experiment with using the annotations (but not in anything they publish publicly). We're thinking that that will include [only `@Nullable` and `@NullnessAnnotated`](https://docs.google.com/document/d/16pPBoejDZJa2iz9HeAIh7GShyWOJNTYRN5_6P9xhAgw/edit#heading=h.c5g2ox5eehhj) to start with. That way, we avoid some of the more controversial remaining issues.

I think we'll be ready to commit to a license soon, but I will get you an update on that.

**Comment by cpovirk** [comment]
OK, we're officially going with Apache 2.0. Feel free to send a PR whenever you'd like :)

**Comment by KengoTODA** [comment]
OK I'll make progress later at https://github.com/jspecify/jspecify/compare/introduce-build-and-ci
Thanks!
