### ISSUE TITLE
Consider enabling the discussions tab

### ISSUE THREAD

**Issue by ascopes** [jspecify/jspecify#548]
Would it be possible to enable the discussions  tab on GitHub? This would be a good way for developers to ask general questions and discuss usage without it being filed as an issue/defect directly.

**Comment by Sparky983** [comment]
JSpecify has a [public Google Group](https://groups.google.com/g/jspecify-discuss)

**Comment by agentgt** [comment]
@Sparky983 I guess the problem with that is I see more questions like #492 being filed.

Which I'm all for people asking questions but I and I assume @ascopes  subscribe to this project on spec related issues and its can get very confusing / noisy.

With github you can quickly move question issues to discussions perhaps even automating if it becomes a problem.

**Comment by cpovirk** [comment]
We had talked about enabling the discussions tab not long ago. I think @kevinb9n was hoping to look more into other projects that have used it. (We'd come across it in Caffeine already but not very often elsewhere.) Maybe others can share examples? I do suspect that I'd personally like writing editable Markdown in the discussions tab over writing emails.

**Comment by netdpb** [comment]
I'm happy to enable it if we think it doesn't require significant setup.

**Comment by netdpb** [comment]
It looks easy enough. I suggest we do that around when we announce 1.0.

**Comment by cpovirk** [comment]
It looks like @netdpb set it up in advance of the imminent release.

Should we change the Discuss link in https://jspecify.dev/docs/start-here/ to point there? Should we add a new link, possibly renaming the old? Do we have a preference for which users use (in general or for specific purposes)? It looks like we have a couple other jspecify-discuss references in start-here.md.

Ah, and the footer already has both "Public Group" and "Mail The Team," both of which point to mailing lists.

**Comment by netdpb** [comment]
I didn't think I had done that, but I guess I did.
