### ISSUE TITLE
Remove Javadoc mention of receiver parameters?

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#551]
I know that we'd discussed this a few times, but I can't remember where we landed.

On the one hand, it's nice for the Javadoc to give a complete description of where the annotations are applicable.

On the other hand, the Javadoc description is only complete if you follow a link to the wiki and absorb 1000 words there, since you need to know what counts as a "type usage" (which is different from the locations where `TYPE_USE` annotations are valid). (Hmm, I wonder if we ever considered _defining_ receiver parameters to not be "type usages?" But revisiting that would require lots more discussion of receiver-parameter type-argument annotations.)

And then there's the fact that most users don't even know about receiver parameters. As a result, mentioning them may confuse more than it helps.

I'm not too invested in whether we do this or not, but I am filing this issue to encourage us to make a conscious decision before 1.0 (or to document the prior conscious decision that I have forgotten :)).

**Comment by cpovirk** [comment]
example possible confusion: I can imagine that _someone_ will _someday_ read the sentence as referring to _parameters in general_.

**Comment by netdpb** [comment]
I think we decided to leave their mention in for now because the Javadoc says the annotations apply "to any type usage except the following cases". If we leave them out, then we're saying they _do_ apply to receiver parameter type arguments.

**Comment by cpovirk** [comment]
I think we could finesse that with some rephrasing if we were motivated enough to remove the reference to receiver parameters. But again, my main goal is just to make sure that there was _some_ decision, so: mission accomplished. Thanks.
