### ISSUE TITLE
Shipping a utility class

### ISSUE THREAD

**Issue by stephan-herrmann** [jspecify/jspecify#56]
Some issues mention methods like`requireNonNull()`. Is it in scope for this project to define a minimal set of such utility methods? If any design decisions are based on their existence then I believe we should.

**Comment by kevinb9n** [comment]
(Note that we _might_ even make these few methods public inside Google; it's making them a public part of _Guava_ that would seem quite absurd.)

I'm still open to JSpecify offering this as a *very* small library... that probably few projects would ever use. If not, we would just have a page with code appropriately licensed saying "eh just copy this to your project". Then we would have a page for few projects to ever read. :-)

It gets much dodgier if we start talking about libraries that JSpecify-conformant checkers would be expected to recognize _per se_ and treat specially. I don't think we've had any inclination to do that.
