### ISSUE TITLE
Checking and interpreting type instantiations wrt declared bounds

### ISSUE THREAD

**Issue by abreslav** [jspecify/jspecify#57]
## Previously considered: well-formedness of wildcard types

In #31:

For class `C<T extends @NotNull Object>` we agreed to not require an explicit bound at the instantiation sites, i.e. `C<?>` and `C<? extends Object>` both mean `C<? extends @NotNull Object>`. This is in agreement with the logic of JLS that applies implicit bounds to wildcards (i.e. `Foo<? extends Bar>` means `Foo<? extends Bar&Bounds_of_T>` where `Foo` is declared to be `Foo<T extends Bounds_of_T>`).

### Type variables with `@NotNull` bounds

To illustrate the question, let's consider the following declarations:
```
class A<TA extends @NotNull Object> {
	TA get();
	void set(TA t);
}
```
By our current spec, this is equivalent to:
```
class A<TA extends @NotNull Object> {
	@NotNull TA get();
	void set(@NotNull TA t);
}
```
Observation: I believe we can't allow any instantiation of type `A<...>` to have `set()` that accepts `@Nullable`, because it is not the contract supported by the implementation. In theory, we could allow `get()` to return `@Nullable`, but I'd like to avoid it.

So, a simple rule for such classes would be: 

**`A<@X Y>` means `A<@NotNull Y>` for any nullability annotation `@X`.**

### Type variables with `@Nullable` bounds

Type parameters with nullable bounds get *parametric* at use sites:
```
class A<TA extends @Nullable Object> {
	TA get();
	void set(TA t);
}
```

Usages `TA` being parametric means that (in the body of `A`):
* `A<TA>.get()` can return null
* `A<TA>.set()` may fail when passed a null
* `TA ta = null` is not safe, because `TA` may end up being `@NotNull String`
* `@NotNull Object foo(TA ta) { return ta; }` is not safe, because `TA` may end up being `@Nullable String`
* `@Nullable T getOrNull()`
  * `this.set(this.getOrNull())` - unsafe to pass `@Nullable T` for `T`, because `T` may end up being `@NotNull String`

Here, unlike the previous case, the first intuition is that `A<@Nullable C>` is not the same as `A<@NotNull C>`, because in the first case `get()` can return null, and in the second case it can not.

The intuitive substitution rule is:
**Parametric usages of `T` are replaced with the corresponding arguments including their annotations**

Examples:
* `A<@Nullable String> a; a.get().length()` - not safe to dereference `a.get()` because it's nullable
* `A<@Nullable String> a; a.set(null)` - ok
* `A<@NotNull String> a; a.get().length()` - safe to dereference `a.get()` because it's not null
* `A<@NotNull String> a; a.set(null)` - not safe, because `set()` takes `@NotNull String` 
  * It may seem that the body of `set` has to be null-tolerant (because it must be prepared to `TA` being a nullable type), but it can store the argument in a field which `get` later returns, so we must require that its argument is not null
* `A<@UnknownNulness String> a; a.get().length()` - dereference of `a.get()` is of unknown safety, unsafe under the strict mode, ok under lenient mode
* `A<@UnknownNulness String> a; a.set(null)` - not sure whether we shoudl consider this unsafe under the strict mode, I'd say we shouldn't, and definitely no complaints in the lenient mode

## Type variables with `@NullnessUnknown` bounds

```
class A<TA extends @NullnessUnknown Object> {
	TA get();
	void set(TA t);
}
```
By our current spec, this is equivalent to:
```
class A<TA extends @NullnessUnknown Object> {
	@NullnessUnknown TA get();
	void set(@NullnessUnknown TA t);
}
```

In #45 we discussed the case of substituting for type parameters whose bounds have `@NullnessUnknown`: the common understanding seems to be that the usages of such type variables we consider implicitly also annotated `@NullnessUnknown`, so when we substitute anything for them, they do not turn into `@NotNull`.

So, I'd say this case should be equivalent to the case of `extends @NotNull`:

**`A<@X Y>` means `A<@NullnessUnknown Y>` for any nullability annotation `@X`.**

## Bottomline: substitution rules

> See the [old proposal by @abreslav](https://docs.google.com/document/d/1J44paXrplWzpCsXFpOobeBz_yiVH0W_yfgZR4sJsUfU/edit#heading=h.6du1tuan3i1w)

The corresponding substitution rules are:
* When type variable usage `T` is parametric (i.e. not annotated explicitly, and has `@Nullable` upper bound)
  * `T` [`T` ← `@A C`] := `@A C`, for `A` in `{@Nullable, @NotNull, @NullnessUnknown}`
* When type variable usage `T` is annotated explicitly or implicitly (trough its bound being `@NotNull` or `@NullnessUnknown`)
  * `@A T` [`T` ← `@CA C`] := `@A C`, for `A` in `{@Nullable, @NotNull, @NullnessUnknown}` and *any* `@CA`

**Comment by kevinb9n** [comment]
I think we can close this. I think this discussion did its job and fed into our thought processes when we needed it.

The text is now 2 years stale and hard to see as actionable. In case anything within here isn't solved and we have nothing else tracking it, please file that as an issue.
