### ISSUE TITLE
Legality of type arguments in constructor invocations

### ISSUE THREAD

**Issue by abreslav** [jspecify/jspecify#58]
**This issue speaks of checking expressions, so it shouldn't affect our spec, but I believe it is important to think about the questions it poses**

In #57 we considered well-formedness rules for type instantiations and came to the conclusion that any instantiation of any generic class is OK from our standpoint. I think that in the case of constructor invocations we may want different rules.

Assuming `C` is declared as follows:
```
class C<T extends @NotNull Object> {
    T get();
    void set(T t);
}
```
(which in our current spec means that every occurrence of `T` in the body of `C` is implicitly annotated as `@NotNull`). Let's consider the following constructor invocations:
* `new C<@NotNull String>()` - this is obviously OK
* `new C<@Nullable String>()` - I'd argue that this is misleading, so it should be **rejected with an error**
* `new C<@UnknownNullness String>()`- I'd say this should be allowed, but probably only in the lenient mode
* `new C<P>()` where `P` is a parametric usage of a type parameter `P extends @Nullable Object` - I'd say this should be allowed even in strict mode, to avoid forcing users to inject pointless `@NotNull`

**Comment by kevinb9n** [comment]
I think this sorted itself out.
