### ISSUE TITLE
Usage clarification about nullness semantics in case of interface implementation

### ISSUE THREAD

**Issue by stechio** [jspecify/jspecify#581]
I'd like to ask your opinion about the following case, to clarify some details on the way nullness relates to inheritance.

Let's say that an interface defines a property whose value can be either nullable or non-nullable, depending on the respective implementations (similarly to what happens when some implementations impose `UnsupportedOperationException` restrictions on certain members); since nullable is the least restrictive condition, the property is annotated accordingly:

```java
@NullMarked
public interface MyInterface {
  @Nullable MyType getMyProperty();

  void setMyProperty(@Nullable MyType value);
}
```

A nullable-property implementation would look like this:

```java
@NullMarked
public class MyNullImpl implements MyInterface {
  private MyType myProperty;

  /*
   * NOTE: return value inherits @Nullable annotation from interface,
   * so there is no need to repeat its declaration.
   */
  @Override
  public MyType getMyProperty() {
    return myProperty;
  }

  /*
   * NOTE: `value` parameter inherits @Nullable annotation from interface,
   * so there is no need to repeat its declaration.
   */
  @Override
  public void setMyProperty(MyType value) {
    myProperty = value;
  }
}
```

while a non-nullable-property implementation would look like this:

```java
@NullMarked
public class MyNonNullImpl implements MyInterface {
  private MyType myProperty;

  /*
   * NOTE: return value overrides @Nullable annotation from interface
   * with @NonNull.
   */
  @Override
  public @NonNull MyType getMyProperty() {
    return myProperty;
  }

  /*
   * NOTE: `value` parameter overrides @Nullable annotation from interface
   * with @NonNull.
   */
  @Override
  public void setMyProperty(@NonNull MyType value) {
    myProperty = requireNonNull(value);
  }
}
```

Is the pattern here above correct?

**Comment by cpovirk** [comment]
Thanks, this is a question that we should write more about somewhere.

Our policy is that the nullness of a type usage is determined entirely by the annotations on that type and the enclosing scopes, not by anything from a method that it overrides. We have [a little written about _why_ that is](https://docs.google.com/document/d/1H3TdqjRZQiGEP7ZePLpTnbYxj9s5hJAn9sp6eOiuj_c/edit#heading=h.rsvxffwgolm3), but we should probably write down somewhere explicitly that that _is_ how it is.

Given that, you'd include `@Nullable` in `MyNullImpl`, and you wouldn't need to include any annotations (except `@NullMarked`) in `MyNonNullImpl`:

```java
public class MyNullImpl implements MyInterface {
  ...
  public void setMyProperty(@Nullable MyType value) {
    ...
```

```java
public class MyNonNullImpl implements MyInterface {
  ...
  public void setMyProperty(MyType value) {
    ...
```

We would then reasonably expect that a nullness checker would inform you that `MyNonNullImpl.setMyProperty` doesn't handle all the inputs that `MyInterface.setMyProperty` does. But as you note, there are no great options here: It would seem worse to annotate `MyNonNullImpl.setMyProperty` as having a `@Nullable` argument when we know that it's going to throw an exception for that case :)

The only possibly better solution is to make `MyInterface` generic:

```java
@NullMarked
public interface MyInterface<T extends @Nullable MyType> {
  T getMyProperty();

  void setMyProperty(T value);
}
```

But that may or may not be worth the complexity that it creates (e.g., an inability to call `setMyProperty(nonNullMyType)` on a `MyInterface<?>`, forcing you to write `MyInterface<? super MyType>` (assuming that that even works with your nullness checker) or a more specific type).

**Comment by stechio** [comment]
This is extremely confusing, fuzzy, contradictory, and inconvenient.

First of all, you say that

> nullness of a type usage is determined entirely by the annotations on THAT type and the enclosing scopes, NOT by anything from a method that it overrides [emphasis is mine]

then

> We would then reasonably expect that a nullness checker would inform you that MyNonNullImpl.setMyProperty doesn't handle all the inputs that MyInterface.setMyProperty does.

If nullness of a type usage is determined entirely by the annotations on that type and not by anything from a method that it overrides, your second statement is impossible (a nullness checker cannot relate the annotated MyInterface.setMyProperty to MyNonNullImpl.setMyProperty...).

Moreover, if the nullness annotations I declare on interface (or abstract class) members are not implicitly applied to derived types, it practically makes almost useless to annotate interface (or abstract class) members in the first place (??).

*The fact that any inheritance/inference mechanism is excluded from nullness annotation of type members is super-ugly* — this implies that ALL the object hierarchy is forced to repeat the same declarations over and over... feels horribly painful, almost nightmarish! And rather weird/counterintuitive, considering that, on the contrary, generic parameters enjoy some level of logical propagation (as you implied here above — BTW, my synapses are writhing at the thought that I should abuse generic parameters just to work around the absence of meaningful logical propagation at type member level...).

IMHO, *such severe limitation/design choice should be clearly stated in the [User Guide](https://jspecify.dev/docs/user-guide)*, which currently seems to entirely overlook any relevant usage example about the way nullness annotations relate to the cornerstone mechanism of inheritance.

I was expecting that a specification built on top of the experience of several existing solutions would be simple, elegant and powerful, not intricate, ugly and limping, but apparently this specification is based on some bold assumptions which I still cannot grasp...

**Comment by agentgt** [comment]
@stechio I understand your frustration but perhaps it is best to think of `@Nullable` as a type and thus is more like `Optional`.

```java
public interface MyInterface {
  Optional<MyType> getMyProperty();
}
```

It would be bizarre if a subclass could do:

```java
public class SubMyInterface implements MyInterface {
  MyType getMyProperty();
}
```

I'm not saying the above is the right way or wrong but rather show a different perspective.

**Comment by stechio** [comment]
@agentgt I just think to nullness annotations as an expressive extension to type semantics/behavior; as such, I expect them to be elegantly inherited as part of the type contract, nothing more, nothing less.

**Comment by agentgt** [comment]
> @agentgt I just think to nullness annotations as an expressive extension to type semantics/behavior; as such, I expect them to be elegantly inherited as part of the type contract, nothing more, nothing less.

Yes ideally that would be nice but imagine if some how Valhalla or whatever provides some sort of nullable marker (or the inverse). I think it is more likely that they would implement the way I just showed it.

I don't know what the current syntax is going to be of Valhalla but I doubt this would be ok:

```java
public interface MyInterface {
  MyType? getMyProperty();
}
```

```java
public class SubMyInterface implements MyInterface {
  MyType getMyProperty();
}
```

I also don't think it will be as much of a problem for many once all the IDEs are onboard. In fact Eclipse will automatically propagate nullness annotations when you override/implement. I think IntelliJ does the same but haven't used it lately for null annotations.

**Comment by stechio** [comment]
A fully idiomatic syntax would be nice and convenient, but explicitly propagating the current annotation syntax looks painfully verbose and redundant.

**Comment by stechio** [comment]
(BTW, I understand that member nullness is invariant — once the member is declared as nullable in the supertype, its subtypes cannot override it making it non-nullable, or vice versa)

**Comment by agentgt** [comment]
> A fully idiomatic syntax would be nice and convenient, but explicitly propagating the current annotation syntax looks painfully verbose and redundant.

Java is a very explicit language. We read code more than we write. Thus I actually vastly prefer the annotations being propagated. That is an opinion of course however I don't know for sure but my gut is that it is easier for tools to implement the spec if it follows the explicit model.


Also there is a code changing aspect. Currently some of the tools (Eclipse and I believe Checker) will actually give you a warning/error so these problems are easier to find. If I switch an interface contract to `@Nullable` just like if I were to switch to `Optional` I would like the compiler to fail on the classes that extend or implement.

> current annotation syntax looks painfully verbose and redundant.

I still think it is better than `Optional` and yet some people like the verbosity of that.

Elegance is nice but there are lots of other things at play.

> I was expecting that a specification built on top of the experience of several existing solutions would be simple, elegant and powerful, not intricate, ugly and limping, but apparently this specification is based on some bold assumptions which I still cannot grasp...

One could argue you should be using the interface instead of the concrete type through most interactions. In fact plenty of static analysis tools like ErrorProne will complain when you do

```java
HashMap<String,String> m = new HashMap<>();
// instead of
Map<String,String> m = new HashMap<>();
```

One of the implementations (NullAway) sits on top of errorprone so you will get a warning I think for the above. The above warnings / errors that these tools omit are based on years of experience.

**Comment by kevinb9n** [comment]
Backing up a bit: Your `MyInterface.setMyProperty` method is promising to accept nullable arguments, and `MyNonNullImpl` isn't fulfilling that commitment, so you should expect a warning when compiling the latter. Calls to `((MyInterface) foo).setMyProperty(null)` will produce no warning but could NPE at runtime.

So just checking: is that the behavior you want? If not, what you really want to do is annotate the base method's parameter as `@NonNull`; that leaves subtypes like `MyNullableImpl` free to _also_ accept null if they want to. (Of course, clients of `MyNullableImpl` that use it _via_ the superinterface will get the spurious warning anyway, much like using `StringBuilder` via the `Appendable` interface sticks you with catching fictional `IOException`s.)

So, when you say "nullable is the least restrictive condition", that's correct for return values (or any "out-type" in an API), but the opposite is true for parameter types ("in-types").

**Comment by agentgt** [comment]
> So, when you say "nullable is the least restrictive condition", that's correct for return values (or any "out-type" in an API), but the opposite is true for parameter types ("in-types").

And if one wants to thinks in types this is called PECS (Producer Extends, Consumer Super) or covariance and contravariance.  I'm not sure how common that phrasing is in the Java world these days but it was a while back. 

Probably confusing as one has to know the `super` of `NonNull` is `Nullable` which I'm not sure if you are allowed to express or not in JSpecify. e.g. `<T super @NonNull SomeType>`. Is that documented somewhere or is `<T super @NonNull SomeType>` nonsensical?

**Comment by kevinb9n** [comment]
To be extra clear, type parameters can't have `super`, but wildcards can, and yes you can annotate the lower bound with JSpecify, and should work as you'd expect. Both `Comparator<@Nullable Foo>` and `Comparator<@NonNull Foo>` are assignable to `Comparable<? super @NonNull Foo>`.

**Comment by agentgt** [comment]
Yes sorry the T was a typo. I meant it as a wildcard. Thanks for the answer.

**Comment by agentgt** [comment]
Also FWIW I tested the `? super @NonNull Foo` with Checkerframework and Eclipse and it works as expected (and Eclipse even makes it a warning that it is redundant... Yay Eclipse and more proof that it is underrated!). I was fairly sure it would work but figured perhaps some implementations it would fail for.

Nullaway unfortunately is broken at the moment for JSpecify generics so I can't test it but it might be a good test for NullAway @msridhar .

**Comment by kevinb9n** [comment]
I think this issue is resolvable.

The question of propagation/inheritance that came up is filed as #14.

**Comment by cpovirk** [comment]
I have been hoping to eventually come back and respond to this:

> If nullness of a type usage is determined entirely by the annotations on that type and not by anything from a method that it overrides, your second statement is impossible (a nullness checker cannot relate the annotated MyInterface.setMyProperty to MyNonNullImpl.setMyProperty...).

But it's one of those cases in which exact definitions matter, and I've been pessimistic that I'd get it right in the first few tries :)

I think it might be better for me to appeal to plain Java: I can declare a superclass with a method `Number asNumber()`, and then I can declare a subclass with a method `@Override Integer asNumber()`. In that case, the return type of the subclass's `getNumber()` method is entirely determined by the type written in that class, yet that type is still _checked against_ the corresponding type from the superclass.

(The analogy isn't perfect: If you try to write `@Override String asNumber()`, then Java will stop you. But since nullness checking isn't a built-in language feature at the moment, a questionable _nullness_ in the override's return type won't necessarily stop you.)

There may be better phrasing that someone could suggest for all this.

**Comment by stechio** [comment]
@kevinb9n:

> The question of propagation/inheritance that came up is filed as #14.

*Please, consider to integrate the [User Guide](https://jspecify.dev/docs/user-guide) with an example on propagation/inheritance, as much of what you take for granted on this fundamental construct may be not so obvious to users.* Thanks!
