### ISSUE TITLE
Interaction between Java type inference and nullness

### ISSUE THREAD

**Issue by stephan-herrmann** [jspecify/jspecify#59]
If we treat nullness as an essential property of types, then we would probably like checkers to weave inference of nullness into all of JLS §18.

I could imagine this to fall under "checker detail", but still I'd like to hear what others think.

On the one hand, JLS §18 is quite a beast, and not all implementers of a checker may like to get involved with all that.

OTOH, if target typing doesn't propagate into nullness inference, then nullness concerns may force users to make explicit those type arguments that type inference can actually determine.

**Comment by kevinb9n** [comment]
Note that the only reason we don't want to support annotations on local variable root types is that a checker will do a better job of deciding their nullness than the annotating human ever could, and when the human needs to assert non-nullness they can do it using one of the methods discussed in #176 and we're right back to analyzer-knows-best again.

So, although I understand exactly nothing about type inference, or the specific concern here, I don't think the checker is missing any information, so I don't know where a problem could come from.

I'm going over-optimistically close this; there might be a real problem but we may only make headway with it when we can see it more concretely.

**Comment by mernst** [comment]
> we don't want to support annotations on local variable root types is that a checker will do a better job of deciding their nullness than the annotating human ever could,

Can you provide evidence for this assertion?

**Comment by kevinb9n** [comment]
The discussion is in #114. I'd hoped very much to get your views on it, at least, enough to email you last July with the link and ask for your input.

What I wrote above was overstated.
