### ISSUE TITLE
Improve documentation of `Optional<@NonNull E>`

### ISSUE THREAD

**Issue by donalmurtagh** [jspecify/jspecify#590]
In [the documentation](https://jspecify.dev/docs/user-guide/#using-type-variables-in-generic-types) an example shows this method

```java
Optional<@NonNull E> maybeFirst();
```

The explanation says:

> An `Optional` object can hold only non-null values

This is not necessarily true, because `Optional.empty()` or `Optional.ofNullable(null)` both return an `Optional` that holds a null value.

**Comment by tbroyer** [comment]
No, they return an empty optional. A non-empty optional (one that holds a value) can only hold a non-null value.

**Comment by cpovirk** [comment]
Yeah, if you think of `Optional.empty()` as the more fundamental operation, with `ofNullable` as just a shortcut that uses `empty()` when appropriate, then that is more in line with the language used by the documentation of `Optional`.

It does turn out to be true that an empty `Optional` is implemented (well, assuming we're talking about the JDK one and not [Guava's](https://github.com/google/guava/blob/a4a7f6bd00ca1acd2efcb81e493720569ba58424/guava/src/com/google/common/base/Absent.java#L27) :)) as an object with a possibly null `value` field. But that is more of a performance optimization in the implementation than it is a fact about the `Optional` API.

Even beyond that, though, there's a more general principle: [There aren't "two kinds"](https://github.com/jspecify/jspecify/wiki/nullness-borderline-cases#the-everything-is-projected-case) of `Optional` instances in quite the same way that there are "two kinds" of `List` instances.

I suspect that different approaches to explaining the different facets of this will work better for different people. What we'll ultimately want is probably to compile them all together, clean them up, promote them out of the wiki, and then link to them from the much shorter text that you're referencing.

**Comment by agentgt** [comment]
> This is not necessarily true, because Optional.empty() or Optional.ofNullable(null) both return an Optional that holds a null value.

That is an internal detail and the API does not say that. That is one thing I like that checker stresses that I think maybe should be added to the JSpecify doc as well:

**[Library annotations should reflect the specification, not the implementation ](https://checkerframework.org/manual/#library-tips-specification)**

> 
No, they return an empty optional. A non-empty optional (one that holds a value) can only hold a non-null value.

For those interested this is why `Optional` does not [fully adhere to the Monad laws](https://www.sitepoint.com/how-optional-breaks-the-monad-laws-and-why-it-matters/). 

Also `Optional` is not an ADT. That is ideally it would have been a sealed interface with two subclasses representing both states so you can pattern match on it. I believe Guava does this but not public and in theory there is possible performance gains by this as it avoids conditions/branching. That is I'm not sure if it holding `null` as empty is faster over what Guava does especially given there is only two subclasses (shiplev had some article I recall about this that I can't seem to google).

**Comment by kevinb9n** [comment]
In theory we could address this by adding "(unless the value is absent)", but this doc is already a complex enough wall of text imho. There are a few misconceptions about Optional out there but I _believe_ the text is okay as it is.
