### ISSUE TITLE
Textual explanation for nullability annotations

### ISSUE THREAD

**Issue by dzharkov** [jspecify/jspecify#6]
The question was initially raised by @amaembo:
> JetBrains Nullable annotation has a textual explanation property which says when value could be null. E.g. @Nullable("when logged in anonymously") String getUserName(). The message could be used by static analyser to produce more friendly warnings. E.g. “calling .trim() on result of getUserName() may cause NullPointerException: when logged in anonymously”. Do we need these (not insisting)?

**Comment by cpovirk** [comment]
A few notes about this for any future discussion:
- I worry that tools might try to [interpret the textual explanation programmatically](https://github.com/jspecify/jspecify/issues/149#issuecomment-746789438). If we really want programmatic access to "reasons" or "explanations," we'd probably prefer alternatives (`@KeyFor`, `@Contract`, [aliases](https://github.com/jspecify/jspecify/issues/71#issuecomment-608072853)...).
- Text in the annotation would likely duplicate text in the Javadoc. That's not the end of the world, but it will likely discourage people from including the information in at least one of those two locations. (And in principle, tools could sometimes display information from Javadoc as part of their error messages (by at least quoting information from `@return` or `@param`) -- though Javadoc is not available if you have only a jar of classes.)
- [Javadoc's rendering of annotation values is ugly.](https://github.com/jspecify/jspecify/issues/149#issue-720582979)
- Ideally, tools would preserve explanations even as they perform substitution. This might mean a need to merge explanations from multiple `@Nullable` annotations -- and possibly even from nullness type annotations _other than_ `@Nullable` if we include those.
