### ISSUE TITLE
Reenable Error Prone

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#604]
Doing so naively...

```diff
--- a/build.gradle
+++ b/build.gradle
@@ -19,13 +19,13 @@ plugins {
     id 'com.diffplug.spotless' version '6.25.0'
     id 'com.github.node-gradle.node' version '7.0.2'
     id 'io.github.gradle-nexus.publish-plugin' version '1.3.0' apply false
-    id 'net.ltgt.errorprone' version '3.0.1'
+    id 'net.ltgt.errorprone' version '4.0.1'
     id "biz.aQute.bnd.builder" version "7.0.0"
 }
 
 ext {
     junitVersion = '5.9.3'
-    errorproneVersion = '2.20.0'
+    errorproneVersion = '2.30.0'
 }
 
 repositories { mavenCentral() }
```

...leads to an error...

```
$ JAVA_HOME=$HOME/jdk-21.0.2 ./gradlew clean assemble

FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:classes
\--- :compileJava
     \--- :jar
          +--- :classes (*)
          +--- :compileJava (*)
          +--- :compileJava9Java
          |    \--- :jar (*)
          \--- :java9Classes
               \--- :compileJava9Java (*)

(*) - details omitted (listed previously)


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 777ms
```

...presumably because Error Prone now depends on JSpecify.

It's possible that we should just disable Error Prone, at least for our prod code, given how trivial that prod code (i.e., just the annotations) is :)

**Comment by tbroyer** [comment]
Did you try without the `includeBuild('.')`?
(adapting the conformance-tests project dependencies to use `project(':')` instead of the coordinates)

**Comment by cpovirk** [comment]
Nope, because I remain totally unqualified to maintain a Gradle build :)

Removing `includeBuild('.')` does indeed help. Assuming that I interpreted `project(':')` correctly, I've also added that, and it at least is enough for `./gradlew assemble` to work. I've created #605 to run the rest of the CI tasks.

Thank you!

**Comment by wmdietl** [comment]
#605 needed to be reverted with #609, because it caused a circular dependency: https://github.com/jspecify/jspecify-reference-checker/issues/202.

We can either close this issue or rename it to "Add Error Prone again".

**Comment by cpovirk** [comment]
Oops, I'd forgotten that we had an issue about this, thanks.

Maybe I'll do... both of those things :) Running Error Prone wouldn't be a bad idea (as discussed in #609), but I would be happy to eliminate this one particular way of having to wrestle with the build setup.
