### ISSUE TITLE
How to fix asymmetrically-nullable properties?

### ISSUE THREAD

**Issue by stechio** [jspecify/jspecify#608]
My legacy code has property getters which dynamically initialize their values in case of undefined state, thus ensuring their return values cannot be `null`, ever; conversely, their corresponding setters do accept `null` values as a convenient way to reset to default state, thus forcing getters to initialize on next call:

```java
/*
  NOTE: Here, for the sake of simplicity, myProperty is expressed as a field,
  but in reality it is resolved on-the-fly from an arbitrarily complex structure
  by its getter, and written to that structure by its setter.
 */

@NonNull Object getMyProperty(){
  if (myProperty == null) {
    . . .
  }
  return myProperty;
}

void setMyProperty(@Nullable Object value){
  myProperty = value;
}
```

From a nullness-aware point of view, I understand this behavior is abusive, since getter-setter pairs should declare the same nullness: what do you think would be the best strategy to comply with the nullness semantics yet preserve the same behavior? (Cluttering my interfaces with specialized `resetMyProperty()` methods just to achieve the same result as `setMyProperty(null)` would be really awkward)

**Comment by agentgt** [comment]
I don't see anything wrong (other than myProperty should be copied to a local variable for some tools but you said it is derived so really no problem).

> From a nullness-aware point of view, I understand this behavior is abusive, **since getter-setter pairs should declare the same nullness:** 

getters and setters are not part of the Java language and the ideas of what a get/set pair should do vary greatly by organization. For example some orgs do not allow dynamic behavior (derived) on getter/setter. So you see it is best JSpecify like Java should have no opinion on this.

**Comment by stechio** [comment]
Thanks for your remarks.

I made extra assumptions (like classic JavaBean property convention) because I noticed that JVM-compatible languages like Kotlin get syntactically broken in case of asymmetrically-nullable properties — but that, as you appropriately clarified, is an issue at another abstraction level.

**Comment by cpovirk** [comment]
(Peanut-gallery armchair API-design comment: Especially when languages like Kotlin aren't treating the setter-getter pair as a property, anyway, you might consider a naming convention like `overrideMyProperty(Object)`+`getMyProperty()` for these methods (instead of using `setMyProperty(Object)` for the one). Naturally, even _that_ kind of change may be more trouble than it's worth in a legacy codebase, even if it otherwise seems appealing.)
