### ISSUE TITLE
Revisit substitution for a type parameter `<T extends @NonNull Object>`

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#618]
https://jspecify.dev/docs/spec/#substitution discusses our current handling of this situation, handling that which we sometimes refer to as "the `ImmutableList.Builder` rule." Discussions of that go [way back](https://github.com/jspecify/jspecify/issues/91#issuecomment-581580007), and even today we have have [an issue open for a small detail of the current handling](https://github.com/jspecify/jspecify/issues/521).

@wmdietl was concerned that (if I'm summarizing correctly) a user who writes `NullHostileList<@Nullable String>` might want to receive an error not only when writing the type "`NullHostileList<@Nullable String>`" and when inserting nulls into the list but also when dereferencing an element retrieved from the list: If `NullHostileList` is written without runtime checks, then a null value might make it the whole way through to that point.

We should write up a doc on this before spec 1.0.

**Comment by cpovirk** [comment]
(If we keep the current rule, then the spec should provide better justification (maybe inline but probably by linking to whatever we write). The justification should touch on not just "Why do we want a special case here?" but also "Why do we implement the special case as a special case _in the substitution rules_, rather than through a rule that says that `ImmutableList<@Nullable String>` gets silently reinterpreted to `ImmutableList<@NonNull String>`. That question has become a FAQ among spec enthusiasts.)

**Comment by cpovirk** [comment]
(Some related discussion of this happened in https://github.com/jspecify/jspecify/issues/640.)

**Comment by netdpb** [comment]
Is the task for this issue simply to enhance the non-normative text in the spec, or is it to change the normative text or its meaning?

If it's just to make the non-normative text better, then is it really necessary to do so before we release 1.0?

**Comment by cpovirk** [comment]
This is to discuss whether to change the normative text. (There is also https://github.com/jspecify/jspecify/issues/521, which may end up being only non-normative text, too.)

I think that @wmdietl is no longer has strong concerns about the behavior we currently specify, so I'm hoping that we can dispatch this this _relatively) quickly.

**Comment by cpovirk** [comment]
While people continue to find the current rule a little surprising when they first encounter it, they've so far also felt OK about it after discussion. I'm going to propose in today's meeting that we stick with the current rule. So I'll say here, as well, that now would be the time to let you know if you object or just would like more time to consider this.

**Comment by cpovirk** [comment]
OK, having raised this in the meeting yesterday (and also over email last week) and not heard any concerns, I'm declaring this to be decided: No matter what type argument you pass, every non-null type-variable usage remains non-null.
