### ISSUE TITLE
Distinguish categories of unknownness

### ISSUE THREAD

**Issue by stephan-herrmann** [jspecify/jspecify#62]
I propose we use the word "unknown" with greatest care and use more specific terms wherever possible.

1. Any concrete type without a nullness annotation (explicit or from default) is "**unspecified**", or has "unspecified nullness".
2. A type parameter with no nullness specification for its bounds is "**unconstrained**", or has "unconstrained nullness". The same for wildcards.
3. A local variable that will hold `null` if one branch in the code is taken, and nonnull on others, also has unknown nullness, but here the reason is closely connected to local **flow analysis**.

While (3) is mostly irrelevant for our task (but relevant for warnings issued by checkers), I believe the difference between (1) and (2) is key for getting a convincing story for type parameters / type variables / wildcards.

Avoiding (1) is necessary for soundiness, because practically checkers cannot check against unspecified signatures. Unspecified closely relates to "unchecked".

Avoiding (2) is not necessary at all, if instantiation of such generic types still ensures that all *type arguments* have specified nullness.

As a consequence from this distinction, Eclipse has coined the term of ["pessimistic checking" for an unconstrained type variable](https://help.eclipse.org/2019-06/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_null_type_annotations.htm&anchor=pessimistic_analysis).

**Comment by kevinb9n** [comment]
I think we were all in sync on the conceptual model put forth here, and basically still are.

Just in terms of actual word choices -- I might kinda like "unconstrained" over "parametric" because it more clearly works well for both type variables and wildcards. This may be a term we just need for conversational purposes, though. Officially the stance could be that these (like intersection types) don't have any describable nullness of their own.

**Comment by kevinb9n** [comment]
(I just couldn't quite rationalize keeping this whole issue open, over the unconstrained-vs.-parametric word choice alone. But you can still comment while it's closed if you want to share any opinion.,
