### ISSUE TITLE
"Map.get case" wiki page missing

### ISSUE THREAD

**Issue by stechio** [jspecify/jspecify#625]
I was looking for the page on topic, but its [wiki link](https://github.com/jspecify/jspecify/wiki/71) referenced by [nullness-borderline-cases](https://github.com/jspecify/jspecify/wiki/nullness-borderline-cases#the-something-has-already-gone-wrong-case) is currently broken (lands to [home page](https://github.com/jspecify/jspecify/wiki/)).

**Comment by cpovirk** [comment]
Thanks, I went in and fixed it.

**Comment by stechio** [comment]
@cpovirk I'm sorry, but *the link is still broken*... maybe the page is protected/non-public and you can see it because of your admin privileges? — The landing page shows me this message: "`You do not have permission to update this wiki.`"

**Comment by cpovirk** [comment]
Oh, sorry, I changed a different link, one that may or may not have been broken... I'll take care of it at an actual computer sometime unless someone beats me to it.

**Comment by cpovirk** [comment]
Also, I am having trouble getting GMail to star this email thread. It's cursed! :)

Should be better now, finally. Thanks for catching my mistake.

![image](https://github.com/user-attachments/assets/be0d151a-6a89-4f55-bf98-3f404a9b0b56)
