### ISSUE TITLE
Subtyping rules for array types

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#65]
I presume that we'll follow [Java's precedent](https://docs.oracle.com/javase/specs/jls/se12/html/jls-4.html#jls-4.10.3), which would let "array of non-`null` strings" be assigned to "array of possibly `null` strings," even though that's unsound.

**Comment by kevinb9n** [comment]
Not sure what last comment is referring to. These seem to both compile with javac.

```
ArrayList<?> one = new ArrayList<>();
ArrayList<? extends @Nullable Object> two = new ArrayList<>();
```

**Comment by cpovirk** [comment]
Sorry, I was missing a `[]`. Better now?

**Comment by kevinb9n** [comment]
Gotcha. So we are talking about this difference:

```
    ArrayList<?>[] one = new ArrayList<?>[0];

    // versus...

    @SuppressWarnings("unchecked")
    ArrayList<? extends @Nullable Object>[] two = new ArrayList<?>[0];
```

This was probably a distraction from the main topic.

**Comment by kevinb9n** [comment]
I started trying to make a concrete proposal here for us to agree/disagree with. I'm not really sure how far I got with it, but to avoid losing what I typed here it is.


### Quick reminder / cheat sheet

(in null-marked context: `String` itself excludes null)

* `String[]` --> array of String
* `@Nullable String[]` --> array of (String U _nulltype_)
* `String @Nullable []` --> (array of String) U _nulltype_
* `@Nullable String @Nullable []` --> (array of (String U _nulltype_)) U _nulltype_

Note `String @Nullable []` is a union type, but `@Nullable String[]` is an array type _of_ a union type.

### Subtyping

Subtyping should extend array covariance to the nullness axis:

* Because `String <: Object`, also `String[] <: Object[]` (precedent)
* Because `String <: @Nullable String`, also `String[] <: @Nullable String[]` (new)

### Notes

Creating a `String[]` has initialization concerns similar to fields, to be discussed elsewhere.

Arrays are bug magnets. There's a lot that can be done about it (a topic for another day). I think we should not be concerned about array bug patterns we introduce as long as they are _analogous_ to existing ones (just along the new nullness axis instead).

**Comment by cpovirk** [comment]
(I gave my thumbs up; my post is primarily clarification and expansion on its points, though my post may be slightly more controversial than Kevin's.)

To only slightly oversimplify, I'd describe my perspective as "Don't write any rules about arrays." I think amounts to the effects described above: Normal subtyping holds.

The one subtlety that I could _maybe_ see capturing in a normative rule is something like...

- "An array is essentially an object with operations `E get(int)` and `void set(int, E)` (and `length`)."

...similar to how we _could_ say something about fields like...

- ["A field is essentially a `Holder<Bar>` with operations `void set(Bar)` and `Bar get()`."](https://github.com/jspecify/jspecify/issues/39#issuecomment-892144846)

That ties the conversation back to the initialization concerns already mentioned.

One other thing:

> I think we should not be concerned about array bug patterns we introduce as long as they are _analogous_ to existing ones (just along the new nullness axis instead).

Whenever we write a "long summary" of all this, we'll want to say more about covariance. To recap earlier discussion: Nullness array covariance is not like normal covariance because nullness mistakes aren't caught at array-insertion time (`ArrayStoreException`), only potentially later, after the value is read from the array. It's more like what you get with generic arrays. Arrays of generic types are [somewhere between fictional and warning-worthy](https://github.com/jspecify/jspecify/issues/65#issuecomment-523108960), so arrays of not-necessarily-`@Nullable` types are similar to that. Thus, tools could conceivably want to issue warnings for them. But I don't think we would get into that in any normative text in our spec, especially given that there may be [better ways to avoid problems than just warning all the time](https://github.com/jspecify/jspecify/issues/65#issuecomment-546506264).

**Comment by kevinb9n** [comment]
> * "An array is essentially an object with operations `E get(int)` and `void set(int, E)` (and `length`)."

Here's the fuller model I'm building up for [Data in Java programs](https://docs.google.com/document/d/1J-a_K87P-R3TscD4uW2Qsbt5BlBR_7uX_BekwJ5BLSE/edit). (This isn't a comment on exactly how we would say it in our spec/docs.)

- An array is an object, extremely similar to a class instance
- Seen as a class instance, that class resembles `class Array<E extends @Nullable Object>` in spirit
- This imaginary class has members resembling `public final int length` and `@Override public Array<E> clone()`
- Covariance: if a direct supertype of `SubFoo` is `SuperFoo`, then a direct supertype of `SubFoo[]` is `SuperFoo[]` (and of `SubFoo @Nullable []` is `SuperFoo @Nullable []`)
- `Object @Nullable []` is thus a supertype of every array type, and *its* direct supertype is `Object`
- Just like a class instance contains zero or more variables called fields, identified by name, so an array contains zero or more variables called array components, identified by index.

This model portrays "array component variables" like `foo[5]` and "field variables" like `bar.qux` as the exact same thing (as are the other two kinds of variables, static field variables and local variables). And that seems right to me.


> ...similar to how we _could_ say something about fields like...
> 
> * ["A field is essentially a `Holder<Bar>` with operations `void set(Bar)` and `Bar get()`."](https://github.com/jspecify/jspecify/issues/39#issuecomment-892144846)

Just s/field/variable/ and it will apply to all four kinds of variables.


> Whenever we write a "long summary" of all this, we'll want to say more about covariance. To recap earlier discussion: Nullness array covariance is not like normal covariance because nullness mistakes aren't caught at array-insertion time (`ArrayStoreException`), only potentially later, after the value is read from the array. It's more like what you get with generic arrays. Arrays of generic types are [somewhere between fictional and warning-worthy](https://github.com/jspecify/jspecify/issues/65#issuecomment-523108960), so arrays of not-necessarily-`@Nullable` types are similar to that. Thus, tools could conceivably want to issue warnings for them. But I don't think we would get into that in any normative text in our spec, especially given that there may be [better ways to avoid problems than just warning all the time](https://github.com/jspecify/jspecify/issues/65#issuecomment-546506264).

We can describe the nullness bit as "erased" like type arguments & type variable usages are (they really are "super-erased", in that javac can't see them at all). So, now there are two kinds of "heap pollution", the known kind plus what we could call "null pollution".

Null pollution is arguably a *bit* more genteel than general heap pollution. Because at least for a type like `T[]` you can deterministically and surgically widen it to be pollution-proof: `T @Nullable []`. i.e. in our 2-D type system, one axis is comparatively opaque but the nullness axis is transparent.

**Comment by cpovirk** [comment]
I should have thought to connect to Data in Java Programs.

We should talk more about "super-erased" sometime: I've gotten the impression that it may encompass multiple things:
- Code compiled by a JSpecify-ignorant compiler obviously ignores the annotations.
- The average JSpecify-aware compiler is not going to insert runtime checks (except for Kotlin!).
- Even for tools that do insert runtime checks, they can't always insert them because of _normal_ erasure. For example, it doesn't know if a `List` is a `List<@Nullable Object>` or a `List<[@NonNull] Object>`. That's analogous to how normal erasure sometimes prevents compilers from inserting normal casts because it can't distinguish `List<String>` from `List<Integer>`. (Granted, a smarter compiler or bytecode instrumenter _could_ insert more checks than it does. But it seems reasonable to say that, because tools don't do that for base Java types, we shouldn't worry that they'll do so for nullness-augmented types, either.)

As for pollution-proof: Do we need a full-on `@Nullable T @Nullable []` to achieve that? `T @Nullable []` still lets unchecked code insert unexpected nulls into the array.

**Comment by kevinb9n** [comment]
> We should talk more about "super-erased" sometime: I've gotten the impression that it may encompass multiple things:
> 
> * Code compiled by a JSpecify-ignorant compiler obviously ignores the annotations.
> * The average JSpecify-aware compiler is not going to insert runtime checks (except for Kotlin!).
> * Even for tools that do insert runtime checks, they can't always insert them because of _normal_ erasure.

And your API's consumers might not use any checker so your annotations might be pure documentation (a.k.a. invisible :-)) to them. Things like that. But I'd just come at it from the other direction: users should probably expect the annotations to accomplish *nothing* but what the user themselves sees them doing.


> As for pollution-proof: Do we need a full-on `@Nullable T @Nullable []` to achieve that? `T @Nullable []` still lets unchecked code insert unexpected nulls into the array.

Uh, yeah, for some reason I meant to only emphasize the array components and then I forgot to check my cheat sheet for the syntax.

**Comment by kevinb9n** [comment]
Chris, what do you think would resolve this issue?

**Comment by cpovirk** [comment]
I think we can close it.

- I think that any discussion about "super-erased" is part of the same discussion as "lifecycle" (#225), which I still owe you a response on. I don't see that as a reason to keep _this_ issue open, since that discussion is more general.

- While I've been saying here that I'm kind of uncertain about whether and how to speak to individual Java constructs, I don't think that concern actually applies here: Array types are types, and types need subtyping rules. This is _not_ a case like parameter contravariance (#49) in which we're asking _when to apply_ those rules. (If some tool wants to offer stricter handling of arrays, then more power to it; I'm confident that we'll find a way to express that these are "the rules" but that we understand that different tools may make different decisions for good enough reasons.)

**Comment by kevinb9n** [comment]
Also note that Valhalla will also be doubling down on covariant arrays, making int[] assignable to Integer[]. (They plan to use NPE, not ASE, on null)

**Comment by kevinb9n** [comment]
Okay, closing, reopen if necessary.

**Comment by cpovirk** [comment]
A couple notes about the implications for `toArray` methods:

- A nice thing about covariant arrays is that a type like `ImmutableCollection` can override the no-arg `toArray()` to return `Object[]` instead of the default of `@Nullable Object[]`. (I think this works out OK for Kotlin callers, but it does _not_ work if you try to write a similar hierarchy _in Kotlin_, since Kotlin arrays are _not_ covariant.)
- For the array-accepting `toArray` overload, we're been using the signature [`<T extends @Nullable Object> T[] toArray(T[])`](https://github.com/jspecify/jdk/blob/f206ad5fc3b5b0d5ba7b5ed6d4c87d3012acec84/src/java.base/share/classes/java/util/Collection.java#L356). I just wrote something on that in a comment on the internal review thread for what, if my calculations are correct, will soon be https://github.com/google/guava/pull/6942:
   > Once arrays are covariant, we're stuck: Even if we were to declare these methods to _require_ a nullable array, as in...
   > 
   > ```
   > public <T> @Nullable T[] toArray(@Nullable T[] array) {
   > ```
   > 
   > ...callers would be able to pass a non-nullable array, since it would widen to a nullable array. The only difference is that we'd then force anyone who tries to use the returned array directly to deal with nullable elements. That's probably the worst of both worlds: The original array might still have arrays unsoundly inserted into it, while the returned array, which is likely _not_ to have nulls in it in the common case (of a collection without nulls and an input array of `new Foo[0]`), is the array that forces callers to confront nullness.
- I haven't thought about the "new" (Java 11) `toArray(IntFunction<T[]>)` overload.

**Comment by kevinb9n** [comment]
Re: bullet 2, it's a weird method that is really two in one: (a) the one where you actually expect elements to be written in, and (b) the one where you're just using an empty array as a type token.

In case (a), it's the kind of method I was discussing way up top:

> a method ... accepting an array parameter for its own implementation to write into, is probably irregular/unusual/already-problematic enough that it is not worth fitting the design to that case. And that says that continuing to treat arrays as covariant for our purposes is a defensible choice for usability reasons.

... and I think it's fine to throw this case under the bus. 

In case (b), logically the same type token ought to work whether the caller wants to get a `Foo![]!` or a `Foo?[]!` back out. And that type token itself could be either a `Foo![]!` or a `Foo?[]!`, couldn't it? (aside: it seems like an analyzer should treat a literal `new Foo[0]` or `new Foo[] {}` as having the type `Foo![]!`, as there's just no call for bringing null into the picture, so to speak.) So in theory all four combinations are valid?

(What's more dodgy is trying to get a `Foo![]!` from a `Collection!<Foo?>`, but I believe we've already made our peace with this anomaly is that right? And that's an issue regardless of what gets passed in.)

**Comment by kevinb9n** [comment]
(so to be more clear I'm possibly raising a very minor question over whether `<T extends @Nullable Object> T[] toArray(T[])` is the right signature or not... but mostly I'm just confused, this stuff is hard to think about.)

**Comment by cpovirk** [comment]
I wrote a bunch of theoretical stuff and then deleted it :)

Concretely, it seems like the alternatives would be:

1:

```java
<T> @Nullable T[] toArray(@Nullable T[])
```

I'd already said a little about that alternative [above](https://github.com/jspecify/jspecify/issues/65#issuecomment-1908388582), but: The theory would be that, because the collection might contain nulls or your array might be too large, we might end up inserting a null into the array no matter what. So we at least give it back to you as an array of nullables. But of course you might pass an input array of non-nullables and then choose to use it afterward. That would be unsound but nothing that you couldn't have done to yourself already through array covariance if you had wanted to.

The downside is the inconvenience of the array-of-nullables return type when you know it's not necessary.

2:

```java
<T> T[] toArray(@Nullable T[])
```

With this signature, we'd be allowing you to pass any array type but then give it back to you as an array of non-nullables, thereby giving you the option to either use that type (if you know it's safe) or re-widen it (if not).

The downside is that you might go to the trouble of passing an array of nullables to be safe but then not realize that the nullability is lost along the way.

3:

```java
<T> T[] toArray(T[])
```

This is dangerous is ways similar to (2) but even _more_ inconvenient for someone who is trying to do the right thing and pass a nullable array. I guess the case for it would rest on the idea that most collections don't contain nulls and most inputs are only type tokens, so why complicate the picture with nullness, especially when covariant arrays throw it all out the window?

(I think I see even less case for a potential (4) `<T> @Nullable T[] toArray(T[])`? Like, if you're arguing that the return type needs to reflect that the array might have nulls in it, then why not even optionally allow the input type to reflect that, too?)

(Maybe I'm overlooking other signatures in which `<T extends @Nullable Object>` could be useful?)

Does any of that strike your fancy? I think I'm still happy with the current signature, but I'm not dead certain.

As for the aside:

> it seems like an analyzer should treat a literal `new Foo[0]` or `new Foo[] {}` as having the type `Foo![]!`, as there's just no call for bringing null into the picture, so to speak.

I think we've to some extent made peace with the idea that even `new Foo[5]` could have type `Foo![]!`, since _initialization_ ¯\_(ツ)_/¯

I am too lazy to dig up threads right now to confirm that.

**Comment by netdpb** [comment]
**Decision**: Array subtyping is already and always strange. Java declares them to be covariant, and there's nothing we can do that's better than that.
