### ISSUE TITLE
Rules for raw types

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#66]
Do we need them? If I assign a `List` to a `List<? extends @NotNull Object>`, is that a nullness warning in addition to a rawtypes and unchecked warning? (Or, [in API terms](https://github.com/google/codeanalysis-annotations/issues/64#issue-480192636), what if I override a method to make that change in return type?)

It would be nice to not have to worry about this, but it may come up with class literals and even the odd API, like [`public final class Range<C extends Comparable>`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/Range.html). Could we get away with saying that nullness isn't checked at all whenever a raw type comes into play (or at least with explicitly leaving this checker-defined)?

**Comment by kevinb9n** [comment]
How about we simply adopt a policy of strictly minimizing how much we think about raw types? Do the expedient thing always, and move on. Problems with class literals will get filed as they're found, and there should be VERY few examples where doing what Range did was justified. And folks probably aren't nullifying their code before they even generified it.

**Comment by kevinb9n** [comment]
(if no traffic I'll close this at some point)

**Comment by netdpb** [comment]
**Current decision**: The specification can mostly ignore raw types.

**Argument for changing**: None.

**Timing**: This must be decided before version 1.0 of the spec.

**Proposal for 1.0: Finalize the current decision.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by netdpb** [comment]
**Decision**: The specification can mostly ignore raw types.
