### ISSUE TITLE
NullnessUnspecified in samples

### ISSUE THREAD

**Issue by amaembo** [jspecify/jspecify#685]
Hello!

There are a number of samples mentioning NullnessUnspecified, despite there's no such annotation anymore. E.g.:
https://github.com/jspecify/jspecify/blob/0929ae0e5a30798c66d0c65033880e55a5aaefcd/samples/AnnotatedReceiver.java#L29

Could you please align samples with the released version of jspecify? If it's still considered to add NullnessUnspecified later, it would be nice to separate 'production samples' and 'experimental samples'. Thanks.

**Comment by netdpb** [comment]
Yes, we do have to do this. I noted this back in #361.
