### ISSUE TITLE
Converting from @NullnessUnspecified to @NullnessUnspecified is unsound

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#69]
Probably many of you have realized this from the beginning, but I'm thinking about it for the first time now. And I see that our draft design lists only 2 "permitted [but] possibly unsafe" conversions...

> - conversion from `@Nullable` to `@NullnessUnknown`
> - conversion from `@NullnessUnknown` to `@NotNull`

...which suggests that "`@NullnessUnknown` to `@NullnessUnknown`" might not be at the top of others' minds, too.

As a concrete example, if `ConcurrentHashMap` were a standalone type with unspecified nullness for all types parameters and type usages, then a caller could write:

```
ConcurrentHashMap<@NullnessUnspecified String, @NullnessUnspecified String> map =
    new ConcurrentHashMap<>();
map.put("foo", map.get("foo"));
```

If `@NullnessUnspecified` converts to `@NullnessUnspecified` without a warning, then that code would pass our type checking but blow up at runtime when it tries to insert `null` into the map.

Maybe that's the best we can do -- I've certainly said a couple times that unannotated code could be rough to deal with in the absence of stub annotation files -- but it would be nice if we could do better.

Maybe we end up with rules that issue a warning _whenever_ an expression uses `@NullnessUnspecified`. (This "just give up" attitude fits in spirit with my https://github.com/google/codeanalysis-annotations/issues/33#issuecomment-518794265 :)) It would be nice if we could avoid that in the cases that _are_ known to be safe, like converting `@NullnessUnspecified` to `@Nullable`, but perhaps that's hard to specify or implement?

Or maybe we treat `@NullnessUnspecified` like an extreme version of wildcard capture: Wildcard capture creates a unique type for every occurrence _in an expression_, but `@NullnessUnspecified` would create a unique type for every occurrence _everywhere_ (or close to it). Then those types would behave like the parametric nullness type `T extends @Nullable Something`, differing only in that unsafe operations would generate warnings instead of errors. But that might be too severe:

```
Foo<@NullnessUnspecified Bar> a = ...;
Foo<@NullnessUnspecified Bar> b = a; // warning? but "why?"
```

\[edit: Note that all of this, for better or for worse, arises organically out of [my current mental model for `@NullnessUnspecified`](https://github.com/google/codeanalysis-annotations/issues/33#issuecomment-538138533).\]

Probably there's a smarter way to do it, but I wonder if we can realistically expect tools to all find it unless we provide guidelines. If we're lucky, _maybe_ this is a rare case in which we really can say that our rules [apply to implementation code only](https://github.com/google/codeanalysis-annotations/issues/64#issue-480192636)?

**Comment by Maaartinus** [comment]
@cpovirk 
> Another downside of deciding to warn only if we have nullness information: That decision might make it harder to measure progress in gradually annotating a codebase: It increases the chance that, each time you fix a warning, you are creating new ones.

I can imagine that there's no way for the user to stop warnings in a reasonable time. Once you start to annotate, the number of detectable problem may start to grow for a long and *unpredictable* time. So for `-Werror` people, it's pretty unusable. Moreover, even if they finish in their livetime (which is unsure) they'll go from zero warnings to zero warnings, seeing no progress at all. ;)

I guess, there should be a different progress measure. Something analogous to test coverage... Something increasing with the invested effort - every added annotation improves the score unless it exposes a major problem..... just an idea....

**Comment by cpovirk** [comment]
I think there's probably no action for "the JSpecify group" to take on this:

- Unspec->unspec is definitely unsound. After all, it's essentially the state of Java code today, and Java code has been known to throw NPE :)
- Many tools won't end up reporting errors for _any_ check that involves unspec _at all_, much less one that involves 2 unspecified types. They can do as they want.
- The spec has reasons for defining relations that tools _could_ use to be stricter if they wanted. We may play with such a tool internally to identify, e.g., unannotated JDK APIs used from Guava, but who knows we'll do anything beyond that?
- Our sample inputs include unspec->unspec conversions, labeled with jspecify_nullness_not_enough_information. If some tool author does want to issue warnings for unspec->spec conversions but not unspec->unspec, then that would be something for us to look into changing. We can do that if the need arises.
