### ISSUE TITLE
Applicability of TYPE_USE annotations to class declarations

### ISSUE THREAD

**Issue by dzharkov** [jspecify/jspecify#7]
The question was initially raised by @amaembo:
> TYPE_USE annotation can be applied to class declaration. Does @Nullable class X{} make sense?

**Comment by cpovirk** [comment]
(Aside: Marking `Void` as always `@Nullable` [is done differently in CF](https://github.com/typetools/checker-framework/blob/5d6a41ec67cd87a19c9b2957a27a56fcae6ea7c2/checker/src/main/java/org/checkerframework/checker/nullness/qual/Nullable.java#L31). That's not to say that someone couldn't prefer to do it with a class-declaration annotation.)

@mernst asked about this [in an earlier doc about our sample/test-data format](https://docs.google.com/document/d/1JVH2p61kReO8bW4AKnbkpybPYlUulVmyNrR1WRIEE_k/edit?disco=AAAAG95MUd8&usp=comment_email_discussion&usp_dm=true&ts=5f6645a8).

I think there are a few levels to approach it on:

First: Do we want to define meaning for JSpecify annotations on a class declaration in JSpecify 1.0? The current thinking is "no," though Mike may want to reopen that.

Second: If we don't define such meaning, is it better to declare such annotations _illegal_ or _implementation-defined_? (Note that, as always, users might hand us bytecode with whatever they want in it, and they might be able to suppress errors even when compiling sources with a JSpecify-aware compiler. So our tools may see such annotations, and we'll want them to not explode.)

Digressing for a moment to set the stage: I think this takes us back to discussions about API vs. implementation code. I've grown increasingly dissatisfied with the blanket statement that "We don't care about implementation code": First of all, it doesn't save us from having to define many of the rules we thought it might (e.g., substitution, subtyping). But even beyond that, what is the point of defining the nullness of APIs unless that provides a well-defined signal to their callers' implementation code?

I still think it makes sense that we don't speak specifically about implementation concerns. And as I've said before, we have no true power to "require" any tool to do anything, anyway. Most of what I see us as doing is defining rules (again, like substitution and subtyping) and leaving it up to tool authors what to do with that information, if anything, in any particular case.

Tying that back to this issue: I do think there's still a case to be made that we don't care about defining _the meaning of annotations that are placed inside implementation code_. However, when an annotation is placed _in an API_ -- such as on a class declaration -- then I think we have reason to want to say _something_ about it. I think this fits with the existing text in the design proposal / spec, which mostly [declines to define the legality of annotations in implementation code](https://github.com/jspecify/jspecify/blob/release-0.x/docs/spec.rst#structural-legality) (though I notice a few exceptions, which may generate further discussion).

That can lead us to questions about the future: If we want to give meaning to JSpecify annotations on a class declaration _after_ 1.0, is it better for us to have made them illegal in 1.0 or left them implementation-defined? The downside of making them illegal is that users of JSpecify-aware compilers need to wait for their update to JSpecify 1.1 (or, at minimum, they need to be able to suppress some errors). The downside of making them implementation-defined is that different implementations might pick different semantics (like whether `public class @Nullable Void` marks `Void` as always `@Nullable` or not).

Third: If JSpecify annotations don't support this, other nullness annotations still might. This lets people who want, say, CF semantics use the CF `@Nullable`. However, this may raise questions around [aliasing/implies](https://github.com/jspecify/jspecify/issues/35): If someone asks a JSpecify checker to treat CF `@NonNull` like JSpecify `@NonNull`, then does that mean that checker sees it as an error to put CF `@NonNull` on a class declaration? That could be unfortunate for existing users of this feature (though I'm not sure how common it is outside of `Optional`). But the alternative is to allow users to accidentally put their custom `@Nullable` annotations in locations where JSpecify checkers will ignore them, perhaps silently :(

(Final comment: We may be able to find a better term than "illegal" for that rough concept. I think we've spoken before about "well-formedness," but that may have other connotations that we don't mean to imply here.)

**Comment by cpovirk** [comment]
(Piling on: Especially now that we have `@NonNull`, it's also easy to imagine that someone might try to annotate a class with `@NonNull` when the person actually wants `@NullMarked`.)

**Comment by netdpb** [comment]
The current, working decision, as of release 0.3, is that JSpecify 1.0 will not allow its type-use annotations (`@Nullable` and `@NonNull`) to apply to class declarations. `@Nullable class Foo {}` is not legal.

The argument for changing this decision is that it would allow us to mark a class so that all its type usages are forced to be either non-null or nullable.

However, nobody has made a strong argument that always-nullable or never-nullable type parameters represent an important use case. It's not worth complicating the model.

**I propose the current decision be finalized for 1.0.** If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative.

**Comment by kevinb9n** [comment]
If it's okay, I'll file a separate issue about the implies use case. The possible resolutions for that issue would be "we provide `@Implies`", "we support meta-annotation" -- or, of course, if it's deprioritized or closed, then "neither".

Then, this issue would cover whether our annotations would be allowed on class declarations for _any other purpose_ but that. (The thread above covers the common use case we were aware of, but there could be others.) This part might be easy to get consensus on.

Sound okay?

**Comment by sdeleuze** [comment]
> Then, this issue would cover whether our annotations would be allowed on class declarations for any other purpose but that. (The thread above covers the common use case we were aware of, but there could be others.) This part might be easy to get consensus on.

Ok for that, once clarified I will turn my thumbs down to thumbs up.

> If it's okay, I'll file a separate issue about the implies use case. 

I would maybe suggest waiting we discuss the document I am about to write before creating a new issue if that's ok for you.

**Comment by netdpb** [comment]
For this issue, I'll change the wording of the proposal to this:

**Proposal**: JSpecify 1.0 will not allow its type-use annotations (@Nullable and @NonNull) to apply to general class declarations. However, these annotations applied to _annotation types_ are considered _meaningless but reserved for future use_.  `@Nullable class Foo {}` is not legal, but `@Nullable @interface Bar {}` is meaningless in 1.0 but may be meaningful in a future version of JSpecify.

Note that this doesn't represent a significant change to the previous proposal (https://github.com/jspecify/jspecify/issues/7#issuecomment-2045817216) in that that proposal also considers these annotations to be meaningless on annotation types, but it does clarify that we may assign a meaning to such annotations in the future, whereas we plan not to assign any meaning to them on other class types.

If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative. **Note: A thumbs-up on the previous proposal will be considered a thumbs-up to this proposal as well.**

**Comment by GregDThomas** [comment]
I'm not adding a thumbs-down, as a mere bystander I'm sure I don't fully understand the reasoning behind this, but ..
> @Nullable class Foo {} is not legal, but 
> @Nullable interface Bar {} is [legal] meaningless ...

I can't help but feel that this breaks the principle of least surprise, no? One is legal, the other is not.
Also, what about an interface that has default method? What will the implication be on those default methods? Why is that different from standard class methods?

**Comment by netdpb** [comment]
Thanks for your comment and question!

> > `@Nullable class Foo {}` is not legal, but
> > `@Nullable interface Bar {}` is [legal] meaningless ...

To clarify:
1. We're talking about _annotation types_, so your second example should be `@Nullable @interface Bar {}`. As you say, interfaces and classes are pretty similar and it would be surprising for JSpecify to treat them differently; but annotation types are very different from both, and so it's not so surprising if JSpecify treated them differently.

3. The difference between "not legal" and "meaningless" is a fine one, and maybe "not legal" is a bad phrase. (I'll edit the revised proposal to remove "not legal".) The clarification I'm trying to make here is that although the annotations in `@Nullable class Foo {}` and `@Nullable @interface Bar {}` are both meaningless in JSpecify 1.0, the latter _may have some meaning_ in a future version of JSpecify.

Does that help?

**Comment by GregDThomas** [comment]
It does, yes. Sorry, somehow missed the @interface vs interface distinction!

**Comment by wmdietl** [comment]
I find the [updated proposal text](https://github.com/jspecify/jspecify/issues/7#issuecomment-2099139237) confusing.

`JSpecify 1.0 will not allow its type-use annotations (@Nullable and @NonNull) to apply to general class declarations.`
I'm not sure what a "general class declaration" is, but here the annotations are "not allowed".

Then later:
`The annotation in @Nullable class Foo {} is meaningless, as is the one in @Nullable @interface Bar {}, but the latter may become meaningful in a future version of JSpecify.`
Here the proposal uses "meaningless" for both cases.
So are the annotations "not allowed" or "meaningless"?

**Comment by kevinb9n** [comment]
JSpecify specifies which [type usages](https://github.com/jspecify/jspecify/wiki/type-usages) are nullness-applicable. We may want to add that *only* type usage can be nullness-applicable, not other places where type-use annotations are also automatically accepted.

Have we ever put anything else in this category "meaningless but reserved"? I would much rather not go down that road. I would like putting a nullness annotation on a class declaration to be forever meaningless, because whatever meaning we might like it to have in the future, we would do better to define a new annotation to express that more clearly anyway.

**Comment by cpovirk** [comment]
My perspective would be that we need to make a decision for 1.0, and the only decision we can make for 1.0 is between "This is applicable with meaning _x_" and "This is not applicable." Any discussion of what might happen in the future is out of scope. In that respect, I'd see this issue as the same as all the other 1.0 issues, and I wouldn't try to differentiate is as "reserved," nor would I attempt to commit now to never using it. Neither strikes me as necessary: Those two options are exactly the options that we leave open by saying that the annotation is inapplicable for 1.0. And part of our goal is to avoid having to block 1.0 on even the basic shape of the design of an implication/aliasing system.

**Comment by netdpb** [comment]
# New Proposal

This proposal is essentially the same as [the original proposal](https://github.com/jspecify/jspecify/issues/7#issuecomment-2045817216).

**Proposal**: JSpecify will not allow its type-use annotations (`@Nullable` and `@NonNull`) to apply to class (and interface, and annotation, etc.) declarations.

This proposal does not mean that JSpecify won't implement a mechanism for one annotation to imply another in the future (#35 and friends).

If you agree, please add a thumbs-up emoji (👍) to this comment. If you disagree, please add a thumbs-down emoji (👎) to this comment and briefly explain your disagreement. Please only add a thumbs-down if you feel you can make a strong case why this decision will be materially worse for users or tool providers than an alternative. **Note: A thumbs-up on [the original proposal](https://github.com/jspecify/jspecify/issues/7#issuecomment-2045817216) will be considered a thumbs-up to this proposal as well.**

**Comment by netdpb** [comment]
**Decision**: JSpecify will not allow its type-use annotations (`@Nullable` and `@NonNull`) to apply to class (and interface, and annotation, etc.) declarations.
