### ISSUE TITLE
Special handling for equals(Object)

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#70]
A sentiment that I've heard in past discussions of nullness is: "`Object.equals(Object)` is known to be required to handle a `null` input, so implementations of `equals` shouldn't need to annotate the parameter explicitly."

I personally believe we should require people to annotate it anyway. (This is part of [my general dislike for special cases](https://github.com/google/codeanalysis-annotations/issues/51#issuecomment-514830030) \[edit: link goes to a discussion of `java.lang.Void`\]. FWIW, I believe [the Checker Framework requires it to be annotated](https://checkerframework.org/manual/#nullness-getting-started).) But I'm filing this bug in anticipation that we'll get such a request someday -- maybe from someone who is reading this right now and will tell me that I have it all wrong :) Even if not, we will eventually want to write up a justification of why we're going this direction.

\[note to self / other Googlers: internal issue 12964927\]

**Comment by cpovirk** [comment]
In #301, I just mentioned that https://github.com/uber/NullAway/issues/619 points out that record classes end up with an `equals` method whose parameter is not annotated `@Nullable`.

I don't think that's an argument for special cases for `equals` in general: Record classes are unusual in that you don't write the source code for them. So I'd apply any special case only for record classes.

**Comment by kevinb9n** [comment]
Perhaps it's like this:

Since the `MyRecord.equals` parameter comes from somewhere that is not a null-marked context, it has unspecified nullness. As such tools can treat is as they see fit, and smart ones know to treat it as nullable.
