### ISSUE TITLE
Fix "Start here" links

### ISSUE THREAD

**Issue by sdeleuze** [jspecify/jspecify#703]
It looks like the "Start here" link the in [specs](https://github.com/jspecify/jspecify/blob/main/docs/docs/spec.md) lead to a 404 error. Same for https://github.com/jspecify/jspecify/blob/main/docs/src/pages/start-here.md which has also a broken link.

**Comment by cpovirk** [comment]
Oh, interesting, this is a downside that I hadn't considered to using a documentation system like Docusaurus: If you view the pages at https://jspecify.dev/docs/spec/ and https://jspecify.dev/start-here/, the links are correct. However, if you use the Markdown view of the source of those pages in the GitHub browser, then the links don't work.

Maybe we should see if we can make the pages display a banner in the GitHub view that directs users to jspecify.dev?

Another option would be to use absolute links ("https://jspecify.dev/docs/start-here/") in the site. However, I think that would prevent Docusaurus from checking for (ironically enough) broken links, which it does automatically if we use the "/docs/start-here" style of link. (It would probably also prevent Docusaurus from performing its magic navigation between pages, though I'm not sure how important that is.)

**Comment by sdeleuze** [comment]
Oh, I see, thanks for providing additional context. I guess I had the habit to go to those Markdown pages as we were working on 1.0, but if those links are fine when deployed, I think that's ok-ish as it is and I can close this issue.
