### ISSUE TITLE
Figure out how we talk about "errors" or "warnings" without falling into the "specifying tool behavior" trap

### ISSUE THREAD

**Issue by kevinb9n** [jspecify/jspecify#73]
I'm still trying to home in on a useful mental model for clarifying what the boundaries should be around what we specify vs. what we leave checker-dependent. Since Mike's visit I've been trying (somewhat) to recast my thinking around "code specification, not code analysis".

So I suppose this would lead us to try to talk less about errors and warnings per se. But I do think that we can defensibly speak in terms of three distinct levels of correctness for the reasons I'm about to explain, and we will need *some* terminology for those three levels (like "error/warning/okay", or "error/strictly-error/okay", or something).

So here's my thought. When we say things like "error/warning" we're not really *trying* to dictate how a checker must surface a problem. We can look at it much more simply: t's more that our annotation specifications implicitly determine which situations arising from their use represent logical contradictions. For example, we might say the reason why you can't override `void foo(@Nullable Foo foo)` with `@Override void foo(@NotNull Foo foo)` is that you've created a logical contradiction: the method can't permit null, but if I just upcast suddenly the null can get in. [note: I disown this particular example in #111]

What does this mean for unspec? So far, I still feel very good about rooting it conceptually on the ternary boolean. The direct result of that is that the question above of "is this a logical contradiction" *itself* now can take on three truth values. For the previous example, it is True that it is a logical contradiction; if the two annotations are reversed then it is False that it is a logical contradiction... and finally, if we are overriding an unspec param with a non-null one, then "is that a logical contradiction?" evaluates to Unknown.

So

1. Can we get with this conceptual framework?
2. What shorthand terms can we converge on?

**Comment by cpovirk** [comment]
How would people feel about the following terminology...?

- "mismatch" for what we've been calling "error"
- "not enough information" for what we've been calling "warning"

**Comment by kevinb9n** [comment]
This discussion seems largely outdated and I don't think we benefit from keeping it open for any particular purpose.
