### ISSUE TITLE
Parametric nullability for <T extends @NullnessUnspecified Object>

### ISSUE THREAD

**Issue by cpovirk** [jspecify/jspecify#76]
I think the current proposal is likely to produce the results we want in practice. But it feels like a special case to me, and I think that some of the alternative rules under discussion can make that happen.

---

The design proposal currently has:
> If the bound’s effective specifier is `@NotNull` or `@NullnessUnknown`, then that is the type variable usage’s effective specifier.

For `@NotNull`, I think we all agree that this is desirable.

For `@NullnessUnknown`, I'm hoping to replace this and other one-off rules (like #45) with [my mental model for `@NullnessUnspecified`](https://github.com/google/codeanalysis-annotations/issues/33#issuecomment-538138533) -- which it's sounding like is similar to Kolin's flexible/platform types and to existential types, as laid out by @mernst.

To see what that looks like, let's first look at our existing rule for `@Nullable`. It produces results like this:

```java
@DefaultNotNull
class Manager<T extends @Nullable Object> {
  void log(T obj) {
    Logger.log(obj.toString()); // ERROR: null might be possible
  }

  T create() {
    return canCreate ? doCreate() : null; // ERROR: null might be forbidden
  }
}
```

Now let's look at the current proposal's rule for `@NullnessUnspecified`. It considers both usages of `T` to have unspecified nullness. That demotes both errors to warnings:

```java
[@DefaultNullnessUnspecified]
class Manager<T> {
  void log(T obj) {
    Logger.log(obj.toString()); // WARNING: null might be possible
  }

  T create() {
    return canCreate ? doCreate() : null; // WARNING: null might be forbidden
  }
}
```

I think this is clearly right for `log`. If we apply my mental model of analyzing the code twice, once with unspecified nullness replaced by `@NotNull` and once with it replaced by `@Nullable`:
- If `T` "should" extend `@NotNull`, then the implementation is safe.
- If `T` "should" extend `@Nullable`, then it's not safe.

Under my mental model, we look at both outcomes and say that the code deserves a warning.

But for `create`:
- If `T` "should" extend `@NotNull`, then the implementation is not safe.
- If `T` "should" extend `@Nullable`, then it's _also_ not safe (because of parametric nullability).

On the surface, this suggests that the more appropriate outcome for `create` would be an error.

But that seems wrong: `Manager` is completely unannotated. Maybe `create` is "intended" to have a signature of `@Nullable T create()`. So we _should_ permit that method to return `null` after all -- with a warning, of course.

This whole outcome can fall out of [some generalized alternative rules we've been discussing](https://github.com/google/codeanalysis-annotations/issues/45#issuecomment-547066138)! Specifically:

- if `@DefaultNullnessUnspecified` "contributes to" the effective nullness of `create`'s return type
- if we combine that unspecified nullness with the nullness `T` is instantiated with -- and do so by picking the "most nullable" value

...then we conclude that `create` returns either `@Nullable` or parametric nullness. Returning `null` is safe in the first case but not the second, so we issue a warning, as desired.

**Comment by kevinb9n** [comment]
It's been an eventful 18 months since the last comment on this issue. @cpovirk, can you give a fresh description of what's solved and what's not solved here?

**Comment by cpovirk** [comment]
I think that this was solved with the addition of "assumed parametric nullability": If a type like `List` is unannotated, we're able to detect that `List<@Nullable String>` has `@Nullable` types for, e.g., the return value of `get`.
