### ISSUE TITLE
Use type-checking terminology correctly/consistently (subtyping/assignability/etc.)

### ISSUE THREAD

**Issue by stephan-herrmann** [jspecify/jspecify#80]
Some discussions start of from `@NotNull X <: @NullnessUnspecified X <: @Nullable X`, some without being precise about what the symbol `<:` stands for: subtyping? assignability? compatibility?

To avoid conflicts with the Java type system as defined in JLS, we should at least be aware of its concepts and rules -- ideally, we would define rules for nullness as a consistent extension of the Java type system.

### Subtyping
In JLS the symbol `<:` denotes **subtyping** as defined in [§4.10](https://docs.oracle.com/javase/specs/jls/se13/html/jls-4.html#jls-4.10). For a top-level type component, subtyping is based strictly on `extends` and `implements`.

### Assignability
In **assignment** context ([§5.2](https://docs.oracle.com/javase/specs/jls/se13/html/jls-5.html#jls-5.2)) various **conversions** are accepted, i.e., assigment checking is more lenient than subtyping.

JLS does not have a special symbol to denote assignability.

### Type argument containment
When checking **subtyping** between two **parameterized** types, type arguments are checked for **type argument containment** ([$4.5.1](https://docs.oracle.com/javase/specs/jls/se13/html/jls-4.html#jls-4.5.1)).

This relation is denoted as `T1 <= T2`.

This relation bears in it the following surprise: 

`List<?>` is a subtype of `List<?>`, because `? <= ?`.

But `List<List<?>>` is not a subtype of `List<List<?>>`, because the type arguments `List<?>` are in a subtyping relation, but not in the required containment relation, i.e., `List<?> <= List<?>` is false.

### Widening / narrowing conversions

While widening is unproblematic, narrowing conversions deserve a closer look:

While the generic type `G<T>` is a subtype of its **raw** type `G` ([§4.10.2](https://docs.oracle.com/javase/specs/jls/se13/html/jls-4.html#jls-4.10.2)), the opposite direction marks a narrowing conversion, generally an unchecked narrowing conversion (subject to an "unchecked" warning) ([§5.1.6.2](https://docs.oracle.com/javase/specs/jls/se13/html/jls-5.html#jls-5.1.6.2)).

The similarity between `NullnessUnspecified` and raw types, suggests that the statement `@NullnessUnspecified X <: @Nullable X` is **wrong** (`<:` read as subtyping).

## Application of these rules

Type arguments are checked against type parameter **bounds** using **subtyping** ([§4.5](https://docs.oracle.com/javase/specs/jls/se13/html/jls-4.html#jls-4.5)), not admitting any conversions.

**Assignability** is used notably for assignments and actual arguments in invocations of methods or constructors.

**Type arguments containment** (as mentioned) is a pre-requisite for subtyping of parameterized types and used no-where else.

**Comment by kevinb9n** [comment]
This issue report is very helpful; I'll leave it open until I feel we've got the terms plumbed through our documents correctly.

**Comment by kevinb9n** [comment]
@cpovirk does it still make sense to have this open?

**Comment by cpovirk** [comment]
The remaining holes in https://jspecify.dev/spec are, as far as I know, unrelated to terminology :) Maybe this GitHub issue is a reminder to think about what to do with, e.g., https://jspecify.dev/design-overview, but I don't think it's worth keeping open in this form.
