### ISSUE TITLE
Configurable effect of non-null defaults

### ISSUE THREAD

**Issue by stephan-herrmann** [jspecify/jspecify#81]
While discussing where exactly something like `@DefaultNonnull` has an effect, I repeatedly mentioned that Eclipse defines its `@NonNullByDefault` in a configurable way, passing the final choice to users.

I'm filing this new issues to give the different aspects of this design a home of its own.

**Comment by kevinb9n** [comment]
If someone wants to champion any configurable-default features, please open new issues and please describe a small set of specific use cases in each.
