### ISSUE TITLE
Annotating type parameters and type variables without using default annotations

### ISSUE THREAD

**Issue by kevin1e100** [jspecify/jspecify#89]
This issue is an attempt at breaking out a piece from issue #45.  One problem that came up there is how to "partially annotate" generic classes/interfaces, and in particular, what should happen if just the type parameter bounds are annotated and nothing else (i.e., not in scope of an explicit default annotation, or equivalently, the default annotation in scope is `@DefaultNullnessUnspecified`).  This is an instance of a more general use case, which is fully or partially annotating files but avoiding the use of default annotations for whatever reason.

I'll mention, because I think that might be relevant in this context, that this problem also comes up with generic methods in otherwise unannotated files: What does it mean to annotate type parameters defined by a method in that scenario?

Cases to consider here align with what it should mean to place each available non-default annotation on type parameters (or more specifically, their bounds, assuming that's how we annotate type parameters).  Since there's only upper bounds as this is written, that really only allows the following cases:

* `<T extends @NonNull X>` (presumed examples: `ImmutableList`, `ImmutableMap`)
* `<T extends @Nullable X>` (presumed examples: `List`, `Map`, `Predicate`)
* `<T extends @NullnessUnspecified X>`

The last one is redundant, so I'll ignore it.  Issue #45 discusses in great detail what to do when parameterizing completely unannotated generic classes (which is what that issue was about), so let's keep that question out of this issue if possible

What are the use cases for this?  Two come to my mind:

* Someone wants to partially annotate a file.  This can be valuable for generic methods, since we for now don't allow placing a default annotation on methods.  For generic classes it seems more unusual to do, since presumably the class's declaration will use the type parameter throughout.
* Someone wants to make all annotations explicit, or put another way, they for whatever reason don't want to use default annotations. This is for instance how Android's APIs are currently annotated.

Let's say we can ignore what type variables "mean" since that's apparently not directly relevant: since generic classes aren't types, what will matter is how to parameterized types (and parameterized methods), such as `List<@Nullable String>` and `Predicate<@NonNull String>`.  

There seems to be agreement that some kind of substitution will take place at least in some cases in order to figure out what the members of such a parameterized type are, and what the effective "signature" of a parameterized generic method is.   There's an additional wrinkle though, and that wrinkle is that there might be annotations also directly placed on type variable usages, and we need to somehow take those into account as well (and if it's just by ignoring them).

Issue #45 puts two proposals on the table for how to do this substitution, given a type argument to parameterize the generic class or method with:

* If there's an annotation on a type variable, use it.  Otherwise, substitute, effectively, the intersection of type argument and the type parameter's bound (keep in mind that bound is not `@NullnessUnspecified` in this context), which will always result in `@NonNull` if that's the annotation on the type parameter's bound.
* Substitute the union of the type argument, `@NullnessUnspecified`, and any type-use annotation on a given type variable usage (ignoring the type parameter's bound).

I believe the question of how to handle annotations on type variable usages could be seen orthogonal, seemingly giving a third possible option:

* If there's an annotation on a type variable, use it.  Otherwise, substitute the union of the type argument and `@NullnessUnspecified` (ignoring the type parameter's bound).

What I'd propose to do here is to explore the strengths and weaknesses of each approach to come up with a solution.  @cpovirk do you think we can move this part off of issue #45?

**Comment by kevinb9n** [comment]
@cpovirk or @kevin1e100, would one of you be able to produce a present-day summary of whatever we might need to decide and/or do, here?
