### ISSUE TITLE
Annotation targets and retentions for nullness annotations

### ISSUE THREAD

**Issue by kevin1e100** [jspecify/jspecify#96]
We've talked about using runtime retention for annotations unless there's a good reason not to, I believe.  For nullness at least we're also looking at a combination of type-use annotations, such as `@Nullable`, and declaration annotations, such as `@DefaultNonNull`.  Filing this issue to point out a potential pitfall for reflective tools, specifically on Android:

Type-use annotations can't be encoded in Android apps, currently, so there's no way to do runtime reflection on them.  On the other hand, reflection is possible with declaration annotations.  That creates the potentially confusing situation that runtime libraries that use reflection, when run on Android, may "see" `@DefaultNonNull` surrounding a method but not `@Nullable` on the method's return type, for instance, so they may erroneously conclude that the return type is non-null.

This potential confusion could be avoided with class retention, but that prevents any reflection on nullness annotations, even outside Android, which also seems unfortunate.

I'm not sure we need to do anything here, but I wanted to file this away for posterity.

**Comment by kevinb9n** [comment]
This seems like a dup of #28.

**Comment by cpovirk** [comment]
(The intention was that this issue would capture anything nullness-specific, like Kevin's comments about the absence of type-use annotations at runtime for Android. But I don't think there's been enough concern about that to leave this one open.)
