### ISSUE TITLE
@Generated annotation

### ISSUE THREAD

**Issue by dzharkov** [jspecify/jspecify#97]
It might be something similar to `javax.annotation.Generated` marking the annotated pieces of code as generated (meaning that no test coverage checks, inspections should be run there).
The idea is originated [KT-35777](https://youtrack.jetbrains.com/issue/KT-35777).

It's 100%, not urgent, issue was created just not to forget about the idea.

**Comment by kevinb9n** [comment]
Not clear we would need another version of that annotation.

**Comment by kevinb9n** [comment]
Need for this isn't clear, could be reopened if it arises.
